/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessKeyStrategy
 */
export interface AccessKeyStrategy {
    /**
     * 
     * @type {string}
     * @memberof AccessKeyStrategy
     */
    state?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AccessKeyStrategy
     */
    accessKeys?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof AccessKeyStrategy
     */
    valid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AccessKeyStrategy
     */
    stateAsEnum?: AccessKeyStrategyStateAsEnumEnum;
}


/**
 * @export
 */
export const AccessKeyStrategyStateAsEnumEnum = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
} as const;
export type AccessKeyStrategyStateAsEnumEnum = typeof AccessKeyStrategyStateAsEnumEnum[keyof typeof AccessKeyStrategyStateAsEnumEnum];


/**
 * Check if a given object implements the AccessKeyStrategy interface.
 */
export function instanceOfAccessKeyStrategy(value: object): value is AccessKeyStrategy {
    return true;
}

export function AccessKeyStrategyFromJSON(json: any): AccessKeyStrategy {
    return AccessKeyStrategyFromJSONTyped(json, false);
}

export function AccessKeyStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessKeyStrategy {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'] == null ? undefined : json['state'],
        'accessKeys': json['accessKeys'] == null ? undefined : json['accessKeys'],
        'valid': json['valid'] == null ? undefined : json['valid'],
        'stateAsEnum': json['stateAsEnum'] == null ? undefined : json['stateAsEnum'],
    };
}

export function AccessKeyStrategyToJSON(json: any): AccessKeyStrategy {
    return AccessKeyStrategyToJSONTyped(json, false);
}

export function AccessKeyStrategyToJSONTyped(value?: AccessKeyStrategy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
        'accessKeys': value['accessKeys'],
        'valid': value['valid'],
        'stateAsEnum': value['stateAsEnum'],
    };
}

