/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiProvidersReq
 */
export interface AiProvidersReq {
    /**
     * 
     * @type {string}
     * @memberof AiProvidersReq
     */
    imageGenProvider?: string;
    /**
     * 
     * @type {string}
     * @memberof AiProvidersReq
     */
    videoGenProvider?: string;
}

/**
 * Check if a given object implements the AiProvidersReq interface.
 */
export function instanceOfAiProvidersReq(value: object): value is AiProvidersReq {
    return true;
}

export function AiProvidersReqFromJSON(json: any): AiProvidersReq {
    return AiProvidersReqFromJSONTyped(json, false);
}

export function AiProvidersReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiProvidersReq {
    if (json == null) {
        return json;
    }
    return {
        
        'imageGenProvider': json['imageGenProvider'] == null ? undefined : json['imageGenProvider'],
        'videoGenProvider': json['videoGenProvider'] == null ? undefined : json['videoGenProvider'],
    };
}

export function AiProvidersReqToJSON(json: any): AiProvidersReq {
    return AiProvidersReqToJSONTyped(json, false);
}

export function AiProvidersReqToJSONTyped(value?: AiProvidersReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageGenProvider': value['imageGenProvider'],
        'videoGenProvider': value['videoGenProvider'],
    };
}

