/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataStreamInfo } from './DataStreamInfo';
import {
    DataStreamInfoFromJSON,
    DataStreamInfoFromJSONTyped,
    DataStreamInfoToJSON,
    DataStreamInfoToJSONTyped,
} from './DataStreamInfo';
import type { PropertyInfo } from './PropertyInfo';
import {
    PropertyInfoFromJSON,
    PropertyInfoFromJSONTyped,
    PropertyInfoToJSON,
    PropertyInfoToJSONTyped,
} from './PropertyInfo';

/**
 * 
 * @export
 * @interface AnalyticsInfo
 */
export interface AnalyticsInfo {
    /**
     * 
     * @type {Array<PropertyInfo>}
     * @memberof AnalyticsInfo
     */
    properties?: Array<PropertyInfo>;
    /**
     * 
     * @type {PropertyInfo}
     * @memberof AnalyticsInfo
     */
    nextValidPropertyInfo?: PropertyInfo;
    /**
     * 
     * @type {PropertyInfo}
     * @memberof AnalyticsInfo
     */
    propertyInfo?: PropertyInfo;
    /**
     * 
     * @type {DataStreamInfo}
     * @memberof AnalyticsInfo
     */
    dataStreamInfo?: DataStreamInfo;
}

/**
 * Check if a given object implements the AnalyticsInfo interface.
 */
export function instanceOfAnalyticsInfo(value: object): value is AnalyticsInfo {
    return true;
}

export function AnalyticsInfoFromJSON(json: any): AnalyticsInfo {
    return AnalyticsInfoFromJSONTyped(json, false);
}

export function AnalyticsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': json['properties'] == null ? undefined : ((json['properties'] as Array<any>).map(PropertyInfoFromJSON)),
        'nextValidPropertyInfo': json['nextValidPropertyInfo'] == null ? undefined : PropertyInfoFromJSON(json['nextValidPropertyInfo']),
        'propertyInfo': json['propertyInfo'] == null ? undefined : PropertyInfoFromJSON(json['propertyInfo']),
        'dataStreamInfo': json['dataStreamInfo'] == null ? undefined : DataStreamInfoFromJSON(json['dataStreamInfo']),
    };
}

export function AnalyticsInfoToJSON(json: any): AnalyticsInfo {
    return AnalyticsInfoToJSONTyped(json, false);
}

export function AnalyticsInfoToJSONTyped(value?: AnalyticsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': value['properties'] == null ? undefined : ((value['properties'] as Array<any>).map(PropertyInfoToJSON)),
        'nextValidPropertyInfo': PropertyInfoToJSON(value['nextValidPropertyInfo']),
        'propertyInfo': PropertyInfoToJSON(value['propertyInfo']),
        'dataStreamInfo': DataStreamInfoToJSON(value['dataStreamInfo']),
    };
}

