/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoCallInfo } from './VideoCallInfo';
import {
    VideoCallInfoFromJSON,
    VideoCallInfoFromJSONTyped,
    VideoCallInfoToJSON,
    VideoCallInfoToJSONTyped,
} from './VideoCallInfo';

/**
 * 
 * @export
 * @interface AnswerCallResult
 */
export interface AnswerCallResult {
    /**
     * 
     * @type {number}
     * @memberof AnswerCallResult
     */
    status?: number;
    /**
     * 
     * @type {VideoCallInfo}
     * @memberof AnswerCallResult
     */
    videoCallInfo?: VideoCallInfo;
}

/**
 * Check if a given object implements the AnswerCallResult interface.
 */
export function instanceOfAnswerCallResult(value: object): value is AnswerCallResult {
    return true;
}

export function AnswerCallResultFromJSON(json: any): AnswerCallResult {
    return AnswerCallResultFromJSONTyped(json, false);
}

export function AnswerCallResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerCallResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'videoCallInfo': json['videoCallInfo'] == null ? undefined : VideoCallInfoFromJSON(json['videoCallInfo']),
    };
}

export function AnswerCallResultToJSON(json: any): AnswerCallResult {
    return AnswerCallResultToJSONTyped(json, false);
}

export function AnswerCallResultToJSONTyped(value?: AnswerCallResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'videoCallInfo': VideoCallInfoToJSON(value['videoCallInfo']),
    };
}

