/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeagueColorInfo } from './LeagueColorInfo';
import {
    LeagueColorInfoFromJSON,
    LeagueColorInfoFromJSONTyped,
    LeagueColorInfoToJSON,
    LeagueColorInfoToJSONTyped,
} from './LeagueColorInfo';
import type { StandingsInfoTeamInfo } from './StandingsInfoTeamInfo';
import {
    StandingsInfoTeamInfoFromJSON,
    StandingsInfoTeamInfoFromJSONTyped,
    StandingsInfoTeamInfoToJSON,
    StandingsInfoTeamInfoToJSONTyped,
} from './StandingsInfoTeamInfo';
import type { LeagueInfo } from './LeagueInfo';
import {
    LeagueInfoFromJSON,
    LeagueInfoFromJSONTyped,
    LeagueInfoToJSON,
    LeagueInfoToJSONTyped,
} from './LeagueInfo';
import type { TotalStandings } from './TotalStandings';
import {
    TotalStandingsFromJSON,
    TotalStandingsFromJSONTyped,
    TotalStandingsToJSON,
    TotalStandingsToJSONTyped,
} from './TotalStandings';
import type { SubLeagueInfo } from './SubLeagueInfo';
import {
    SubLeagueInfoFromJSON,
    SubLeagueInfoFromJSONTyped,
    SubLeagueInfoToJSON,
    SubLeagueInfoToJSONTyped,
} from './SubLeagueInfo';

/**
 * 
 * @export
 * @interface APIStandingsInfo2
 */
export interface APIStandingsInfo2 {
    /**
     * 
     * @type {LeagueInfo}
     * @memberof APIStandingsInfo2
     */
    leagueInfo?: LeagueInfo;
    /**
     * 
     * @type {Array<SubLeagueInfo>}
     * @memberof APIStandingsInfo2
     */
    subLeagueInfos?: Array<SubLeagueInfo>;
    /**
     * 
     * @type {Array<StandingsInfoTeamInfo>}
     * @memberof APIStandingsInfo2
     */
    teamInfos?: Array<StandingsInfoTeamInfo>;
    /**
     * 
     * @type {Array<TotalStandings>}
     * @memberof APIStandingsInfo2
     */
    totalStandings?: Array<TotalStandings>;
    /**
     * 
     * @type {Array<TotalStandings>}
     * @memberof APIStandingsInfo2
     */
    halfStandings?: Array<TotalStandings>;
    /**
     * 
     * @type {Array<TotalStandings>}
     * @memberof APIStandingsInfo2
     */
    homeStandings?: Array<TotalStandings>;
    /**
     * 
     * @type {Array<TotalStandings>}
     * @memberof APIStandingsInfo2
     */
    awayStandings?: Array<TotalStandings>;
    /**
     * 
     * @type {Array<TotalStandings>}
     * @memberof APIStandingsInfo2
     */
    homeHalfStandings?: Array<TotalStandings>;
    /**
     * 
     * @type {Array<TotalStandings>}
     * @memberof APIStandingsInfo2
     */
    awayHalfStandings?: Array<TotalStandings>;
    /**
     * 
     * @type {Array<LeagueColorInfo>}
     * @memberof APIStandingsInfo2
     */
    leagueColorInfos?: Array<LeagueColorInfo>;
    /**
     * 
     * @type {number}
     * @memberof APIStandingsInfo2
     */
    lastUpdateTime?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APIStandingsInfo2
     */
    conference?: boolean;
}

/**
 * Check if a given object implements the APIStandingsInfo2 interface.
 */
export function instanceOfAPIStandingsInfo2(value: object): value is APIStandingsInfo2 {
    return true;
}

export function APIStandingsInfo2FromJSON(json: any): APIStandingsInfo2 {
    return APIStandingsInfo2FromJSONTyped(json, false);
}

export function APIStandingsInfo2FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIStandingsInfo2 {
    if (json == null) {
        return json;
    }
    return {
        
        'leagueInfo': json['leagueInfo'] == null ? undefined : LeagueInfoFromJSON(json['leagueInfo']),
        'subLeagueInfos': json['subLeagueInfos'] == null ? undefined : ((json['subLeagueInfos'] as Array<any>).map(SubLeagueInfoFromJSON)),
        'teamInfos': json['teamInfos'] == null ? undefined : ((json['teamInfos'] as Array<any>).map(StandingsInfoTeamInfoFromJSON)),
        'totalStandings': json['totalStandings'] == null ? undefined : ((json['totalStandings'] as Array<any>).map(TotalStandingsFromJSON)),
        'halfStandings': json['halfStandings'] == null ? undefined : ((json['halfStandings'] as Array<any>).map(TotalStandingsFromJSON)),
        'homeStandings': json['homeStandings'] == null ? undefined : ((json['homeStandings'] as Array<any>).map(TotalStandingsFromJSON)),
        'awayStandings': json['awayStandings'] == null ? undefined : ((json['awayStandings'] as Array<any>).map(TotalStandingsFromJSON)),
        'homeHalfStandings': json['homeHalfStandings'] == null ? undefined : ((json['homeHalfStandings'] as Array<any>).map(TotalStandingsFromJSON)),
        'awayHalfStandings': json['awayHalfStandings'] == null ? undefined : ((json['awayHalfStandings'] as Array<any>).map(TotalStandingsFromJSON)),
        'leagueColorInfos': json['leagueColorInfos'] == null ? undefined : ((json['leagueColorInfos'] as Array<any>).map(LeagueColorInfoFromJSON)),
        'lastUpdateTime': json['lastUpdateTime'] == null ? undefined : json['lastUpdateTime'],
        'conference': json['conference'] == null ? undefined : json['conference'],
    };
}

export function APIStandingsInfo2ToJSON(json: any): APIStandingsInfo2 {
    return APIStandingsInfo2ToJSONTyped(json, false);
}

export function APIStandingsInfo2ToJSONTyped(value?: APIStandingsInfo2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leagueInfo': LeagueInfoToJSON(value['leagueInfo']),
        'subLeagueInfos': value['subLeagueInfos'] == null ? undefined : ((value['subLeagueInfos'] as Array<any>).map(SubLeagueInfoToJSON)),
        'teamInfos': value['teamInfos'] == null ? undefined : ((value['teamInfos'] as Array<any>).map(StandingsInfoTeamInfoToJSON)),
        'totalStandings': value['totalStandings'] == null ? undefined : ((value['totalStandings'] as Array<any>).map(TotalStandingsToJSON)),
        'halfStandings': value['halfStandings'] == null ? undefined : ((value['halfStandings'] as Array<any>).map(TotalStandingsToJSON)),
        'homeStandings': value['homeStandings'] == null ? undefined : ((value['homeStandings'] as Array<any>).map(TotalStandingsToJSON)),
        'awayStandings': value['awayStandings'] == null ? undefined : ((value['awayStandings'] as Array<any>).map(TotalStandingsToJSON)),
        'homeHalfStandings': value['homeHalfStandings'] == null ? undefined : ((value['homeHalfStandings'] as Array<any>).map(TotalStandingsToJSON)),
        'awayHalfStandings': value['awayHalfStandings'] == null ? undefined : ((value['awayHalfStandings'] as Array<any>).map(TotalStandingsToJSON)),
        'leagueColorInfos': value['leagueColorInfos'] == null ? undefined : ((value['leagueColorInfos'] as Array<any>).map(LeagueColorInfoToJSON)),
        'lastUpdateTime': value['lastUpdateTime'],
        'conference': value['conference'],
    };
}

