/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentsAttachmentBackground
 */
export interface AttachmentsAttachmentBackground {
    /**
     * 
     * @type {string}
     * @memberof AttachmentsAttachmentBackground
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentsAttachmentBackground
     */
    objectFit?: string;
}

/**
 * Check if a given object implements the AttachmentsAttachmentBackground interface.
 */
export function instanceOfAttachmentsAttachmentBackground(value: object): value is AttachmentsAttachmentBackground {
    return true;
}

export function AttachmentsAttachmentBackgroundFromJSON(json: any): AttachmentsAttachmentBackground {
    return AttachmentsAttachmentBackgroundFromJSONTyped(json, false);
}

export function AttachmentsAttachmentBackgroundFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentsAttachmentBackground {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'objectFit': json['objectFit'] == null ? undefined : json['objectFit'],
    };
}

export function AttachmentsAttachmentBackgroundToJSON(json: any): AttachmentsAttachmentBackground {
    return AttachmentsAttachmentBackgroundToJSONTyped(json, false);
}

export function AttachmentsAttachmentBackgroundToJSONTyped(value?: AttachmentsAttachmentBackground | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'objectFit': value['objectFit'],
    };
}

