/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseSettingsItemDefVisibilityInfo } from './BaseSettingsItemDefVisibilityInfo';
import {
    BaseSettingsItemDefVisibilityInfoFromJSON,
    BaseSettingsItemDefVisibilityInfoFromJSONTyped,
    BaseSettingsItemDefVisibilityInfoToJSON,
    BaseSettingsItemDefVisibilityInfoToJSONTyped,
} from './BaseSettingsItemDefVisibilityInfo';

/**
 * 
 * @export
 * @interface BaseSettingsNavItemDef
 */
export interface BaseSettingsNavItemDef {
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsNavItemDef
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsNavItemDef
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsNavItemDef
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsNavItemDef
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsNavItemDef
     */
    op?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseSettingsNavItemDef
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsNavItemDef
     */
    action?: string;
    /**
     * 
     * @type {{ [key: string]: BaseSettingsItemDefVisibilityInfo; }}
     * @memberof BaseSettingsNavItemDef
     */
    visibilityInfos?: { [key: string]: BaseSettingsItemDefVisibilityInfo; };
    /**
     * 
     * @type {Array<string>}
     * @memberof BaseSettingsNavItemDef
     */
    parsedTags?: Array<string>;
}

/**
 * Check if a given object implements the BaseSettingsNavItemDef interface.
 */
export function instanceOfBaseSettingsNavItemDef(value: object): value is BaseSettingsNavItemDef {
    return true;
}

export function BaseSettingsNavItemDefFromJSON(json: any): BaseSettingsNavItemDef {
    return BaseSettingsNavItemDefFromJSONTyped(json, false);
}

export function BaseSettingsNavItemDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseSettingsNavItemDef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'op': json['op'] == null ? undefined : json['op'],
        'order': json['order'] == null ? undefined : json['order'],
        'action': json['action'] == null ? undefined : json['action'],
        'visibilityInfos': json['visibilityInfos'] == null ? undefined : (mapValues(json['visibilityInfos'], BaseSettingsItemDefVisibilityInfoFromJSON)),
        'parsedTags': json['parsedTags'] == null ? undefined : json['parsedTags'],
    };
}

export function BaseSettingsNavItemDefToJSON(json: any): BaseSettingsNavItemDef {
    return BaseSettingsNavItemDefToJSONTyped(json, false);
}

export function BaseSettingsNavItemDefToJSONTyped(value?: BaseSettingsNavItemDef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'tags': value['tags'],
        'icon': value['icon'],
        'op': value['op'],
        'order': value['order'],
        'action': value['action'],
        'visibilityInfos': value['visibilityInfos'] == null ? undefined : (mapValues(value['visibilityInfos'], BaseSettingsItemDefVisibilityInfoToJSON)),
        'parsedTags': value['parsedTags'],
    };
}

