/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseSettingsShopSettingsSyncProductConfig
 */
export interface BaseSettingsShopSettingsSyncProductConfig {
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsShopSettingsSyncProductConfig
     */
    syncProductStrategy?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseSettingsShopSettingsSyncProductConfig
     */
    flwrInferenceStrategy?: string;
}

/**
 * Check if a given object implements the BaseSettingsShopSettingsSyncProductConfig interface.
 */
export function instanceOfBaseSettingsShopSettingsSyncProductConfig(value: object): value is BaseSettingsShopSettingsSyncProductConfig {
    return true;
}

export function BaseSettingsShopSettingsSyncProductConfigFromJSON(json: any): BaseSettingsShopSettingsSyncProductConfig {
    return BaseSettingsShopSettingsSyncProductConfigFromJSONTyped(json, false);
}

export function BaseSettingsShopSettingsSyncProductConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseSettingsShopSettingsSyncProductConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'syncProductStrategy': json['syncProductStrategy'] == null ? undefined : json['syncProductStrategy'],
        'flwrInferenceStrategy': json['flwrInferenceStrategy'] == null ? undefined : json['flwrInferenceStrategy'],
    };
}

export function BaseSettingsShopSettingsSyncProductConfigToJSON(json: any): BaseSettingsShopSettingsSyncProductConfig {
    return BaseSettingsShopSettingsSyncProductConfigToJSONTyped(json, false);
}

export function BaseSettingsShopSettingsSyncProductConfigToJSONTyped(value?: BaseSettingsShopSettingsSyncProductConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'syncProductStrategy': value['syncProductStrategy'],
        'flwrInferenceStrategy': value['flwrInferenceStrategy'],
    };
}

