/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseSettingsBountyTypeSettingsBountyFeatureInfo
 */
export interface BaseSettingsBountyTypeSettingsBountyFeatureInfo {
    /**
     * 
     * @type {boolean}
     * @memberof BaseSettingsBountyTypeSettingsBountyFeatureInfo
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the BaseSettingsBountyTypeSettingsBountyFeatureInfo interface.
 */
export function instanceOfBaseSettingsBountyTypeSettingsBountyFeatureInfo(value: object): value is BaseSettingsBountyTypeSettingsBountyFeatureInfo {
    return true;
}

export function BaseSettingsBountyTypeSettingsBountyFeatureInfoFromJSON(json: any): BaseSettingsBountyTypeSettingsBountyFeatureInfo {
    return BaseSettingsBountyTypeSettingsBountyFeatureInfoFromJSONTyped(json, false);
}

export function BaseSettingsBountyTypeSettingsBountyFeatureInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseSettingsBountyTypeSettingsBountyFeatureInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function BaseSettingsBountyTypeSettingsBountyFeatureInfoToJSON(json: any): BaseSettingsBountyTypeSettingsBountyFeatureInfo {
    return BaseSettingsBountyTypeSettingsBountyFeatureInfoToJSONTyped(json, false);
}

export function BaseSettingsBountyTypeSettingsBountyFeatureInfoToJSONTyped(value?: BaseSettingsBountyTypeSettingsBountyFeatureInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

