/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';

/**
 * 
 * @export
 * @interface BountyChangesChangesReward
 */
export interface BountyChangesChangesReward {
    /**
     * 
     * @type {Reward}
     * @memberof BountyChangesChangesReward
     */
    newValue?: Reward;
    /**
     * 
     * @type {Reward}
     * @memberof BountyChangesChangesReward
     */
    oldValue?: Reward;
    /**
     * 
     * @type {boolean}
     * @memberof BountyChangesChangesReward
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the BountyChangesChangesReward interface.
 */
export function instanceOfBountyChangesChangesReward(value: object): value is BountyChangesChangesReward {
    return true;
}

export function BountyChangesChangesRewardFromJSON(json: any): BountyChangesChangesReward {
    return BountyChangesChangesRewardFromJSONTyped(json, false);
}

export function BountyChangesChangesRewardFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyChangesChangesReward {
    if (json == null) {
        return json;
    }
    return {
        
        'newValue': json['newValue'] == null ? undefined : RewardFromJSON(json['newValue']),
        'oldValue': json['oldValue'] == null ? undefined : RewardFromJSON(json['oldValue']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function BountyChangesChangesRewardToJSON(json: any): BountyChangesChangesReward {
    return BountyChangesChangesRewardToJSONTyped(json, false);
}

export function BountyChangesChangesRewardToJSONTyped(value?: BountyChangesChangesReward | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newValue': RewardToJSON(value['newValue']),
        'oldValue': RewardToJSON(value['oldValue']),
        'empty': value['empty'],
    };
}

