/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BountyChangesChangesReward } from './BountyChangesChangesReward';
import {
    BountyChangesChangesRewardFromJSON,
    BountyChangesChangesRewardFromJSONTyped,
    BountyChangesChangesRewardToJSON,
    BountyChangesChangesRewardToJSONTyped,
} from './BountyChangesChangesReward';
import type { BountyChangesChangesString } from './BountyChangesChangesString';
import {
    BountyChangesChangesStringFromJSON,
    BountyChangesChangesStringFromJSONTyped,
    BountyChangesChangesStringToJSON,
    BountyChangesChangesStringToJSONTyped,
} from './BountyChangesChangesString';
import type { BountyChangesChangesBountyOrderPaymentInfo } from './BountyChangesChangesBountyOrderPaymentInfo';
import {
    BountyChangesChangesBountyOrderPaymentInfoFromJSON,
    BountyChangesChangesBountyOrderPaymentInfoFromJSONTyped,
    BountyChangesChangesBountyOrderPaymentInfoToJSON,
    BountyChangesChangesBountyOrderPaymentInfoToJSONTyped,
} from './BountyChangesChangesBountyOrderPaymentInfo';
import type { BountyChangesChangesBountyOrderNextStepInfo } from './BountyChangesChangesBountyOrderNextStepInfo';
import {
    BountyChangesChangesBountyOrderNextStepInfoFromJSON,
    BountyChangesChangesBountyOrderNextStepInfoFromJSONTyped,
    BountyChangesChangesBountyOrderNextStepInfoToJSON,
    BountyChangesChangesBountyOrderNextStepInfoToJSONTyped,
} from './BountyChangesChangesBountyOrderNextStepInfo';
import type { BountyChangesChangesBountyOrderChargebackInfo } from './BountyChangesChangesBountyOrderChargebackInfo';
import {
    BountyChangesChangesBountyOrderChargebackInfoFromJSON,
    BountyChangesChangesBountyOrderChargebackInfoFromJSONTyped,
    BountyChangesChangesBountyOrderChargebackInfoToJSON,
    BountyChangesChangesBountyOrderChargebackInfoToJSONTyped,
} from './BountyChangesChangesBountyOrderChargebackInfo';
import type { BountyChangesChangesShippingInfo } from './BountyChangesChangesShippingInfo';
import {
    BountyChangesChangesShippingInfoFromJSON,
    BountyChangesChangesShippingInfoFromJSONTyped,
    BountyChangesChangesShippingInfoToJSON,
    BountyChangesChangesShippingInfoToJSONTyped,
} from './BountyChangesChangesShippingInfo';

/**
 * 
 * @export
 * @interface BountyChangesOrderChanges
 */
export interface BountyChangesOrderChanges {
    /**
     * 
     * @type {BountyChangesChangesString}
     * @memberof BountyChangesOrderChanges
     */
    status?: BountyChangesChangesString;
    /**
     * 
     * @type {BountyChangesChangesString}
     * @memberof BountyChangesOrderChanges
     */
    paymentStatus?: BountyChangesChangesString;
    /**
     * 
     * @type {BountyChangesChangesString}
     * @memberof BountyChangesOrderChanges
     */
    failureMessage?: BountyChangesChangesString;
    /**
     * 
     * @type {BountyChangesChangesString}
     * @memberof BountyChangesOrderChanges
     */
    receiptStatus?: BountyChangesChangesString;
    /**
     * 
     * @type {BountyChangesChangesShippingInfo}
     * @memberof BountyChangesOrderChanges
     */
    shippingInfo?: BountyChangesChangesShippingInfo;
    /**
     * 
     * @type {BountyChangesChangesBountyOrderChargebackInfo}
     * @memberof BountyChangesOrderChanges
     */
    chargebackInfo?: BountyChangesChangesBountyOrderChargebackInfo;
    /**
     * 
     * @type {BountyChangesChangesBountyOrderPaymentInfo}
     * @memberof BountyChangesOrderChanges
     */
    paymentInfo?: BountyChangesChangesBountyOrderPaymentInfo;
    /**
     * 
     * @type {BountyChangesChangesBountyOrderNextStepInfo}
     * @memberof BountyChangesOrderChanges
     */
    nextStepInfo?: BountyChangesChangesBountyOrderNextStepInfo;
    /**
     * 
     * @type {BountyChangesChangesReward}
     * @memberof BountyChangesOrderChanges
     */
    totalPaid?: BountyChangesChangesReward;
    /**
     * 
     * @type {BountyChangesChangesReward}
     * @memberof BountyChangesOrderChanges
     */
    change?: BountyChangesChangesReward;
}

/**
 * Check if a given object implements the BountyChangesOrderChanges interface.
 */
export function instanceOfBountyChangesOrderChanges(value: object): value is BountyChangesOrderChanges {
    return true;
}

export function BountyChangesOrderChangesFromJSON(json: any): BountyChangesOrderChanges {
    return BountyChangesOrderChangesFromJSONTyped(json, false);
}

export function BountyChangesOrderChangesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyChangesOrderChanges {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : BountyChangesChangesStringFromJSON(json['status']),
        'paymentStatus': json['paymentStatus'] == null ? undefined : BountyChangesChangesStringFromJSON(json['paymentStatus']),
        'failureMessage': json['failureMessage'] == null ? undefined : BountyChangesChangesStringFromJSON(json['failureMessage']),
        'receiptStatus': json['receiptStatus'] == null ? undefined : BountyChangesChangesStringFromJSON(json['receiptStatus']),
        'shippingInfo': json['shippingInfo'] == null ? undefined : BountyChangesChangesShippingInfoFromJSON(json['shippingInfo']),
        'chargebackInfo': json['chargebackInfo'] == null ? undefined : BountyChangesChangesBountyOrderChargebackInfoFromJSON(json['chargebackInfo']),
        'paymentInfo': json['paymentInfo'] == null ? undefined : BountyChangesChangesBountyOrderPaymentInfoFromJSON(json['paymentInfo']),
        'nextStepInfo': json['nextStepInfo'] == null ? undefined : BountyChangesChangesBountyOrderNextStepInfoFromJSON(json['nextStepInfo']),
        'totalPaid': json['totalPaid'] == null ? undefined : BountyChangesChangesRewardFromJSON(json['totalPaid']),
        'change': json['change'] == null ? undefined : BountyChangesChangesRewardFromJSON(json['change']),
    };
}

export function BountyChangesOrderChangesToJSON(json: any): BountyChangesOrderChanges {
    return BountyChangesOrderChangesToJSONTyped(json, false);
}

export function BountyChangesOrderChangesToJSONTyped(value?: BountyChangesOrderChanges | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': BountyChangesChangesStringToJSON(value['status']),
        'paymentStatus': BountyChangesChangesStringToJSON(value['paymentStatus']),
        'failureMessage': BountyChangesChangesStringToJSON(value['failureMessage']),
        'receiptStatus': BountyChangesChangesStringToJSON(value['receiptStatus']),
        'shippingInfo': BountyChangesChangesShippingInfoToJSON(value['shippingInfo']),
        'chargebackInfo': BountyChangesChangesBountyOrderChargebackInfoToJSON(value['chargebackInfo']),
        'paymentInfo': BountyChangesChangesBountyOrderPaymentInfoToJSON(value['paymentInfo']),
        'nextStepInfo': BountyChangesChangesBountyOrderNextStepInfoToJSON(value['nextStepInfo']),
        'totalPaid': BountyChangesChangesRewardToJSON(value['totalPaid']),
        'change': BountyChangesChangesRewardToJSON(value['change']),
    };
}

