/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BountyOrderPaymentInfoBillMyBankPayment } from './BountyOrderPaymentInfoBillMyBankPayment';
import {
    BountyOrderPaymentInfoBillMyBankPaymentFromJSON,
    BountyOrderPaymentInfoBillMyBankPaymentFromJSONTyped,
    BountyOrderPaymentInfoBillMyBankPaymentToJSON,
    BountyOrderPaymentInfoBillMyBankPaymentToJSONTyped,
} from './BountyOrderPaymentInfoBillMyBankPayment';
import type { BountyOrderNextStepInfo } from './BountyOrderNextStepInfo';
import {
    BountyOrderNextStepInfoFromJSON,
    BountyOrderNextStepInfoFromJSONTyped,
    BountyOrderNextStepInfoToJSON,
    BountyOrderNextStepInfoToJSONTyped,
} from './BountyOrderNextStepInfo';

/**
 * 
 * @export
 * @interface BountyOrderPaymentInfo
 */
export interface BountyOrderPaymentInfo {
    /**
     * 
     * @type {string}
     * @memberof BountyOrderPaymentInfo
     */
    paymentId?: string;
    /**
     * 
     * @type {string}
     * @memberof BountyOrderPaymentInfo
     */
    paymentMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof BountyOrderPaymentInfo
     */
    paymentStatus?: string;
    /**
     * 
     * @type {BountyOrderPaymentInfoBillMyBankPayment}
     * @memberof BountyOrderPaymentInfo
     */
    bmbPayment?: BountyOrderPaymentInfoBillMyBankPayment;
    /**
     * 
     * @type {string}
     * @memberof BountyOrderPaymentInfo
     */
    failureMessage?: string;
    /**
     * 
     * @type {BountyOrderNextStepInfo}
     * @memberof BountyOrderPaymentInfo
     */
    nextStepInfo?: BountyOrderNextStepInfo;
    /**
     * 
     * @type {string}
     * @memberof BountyOrderPaymentInfo
     */
    paymentMethodAsEnum?: BountyOrderPaymentInfoPaymentMethodAsEnumEnum;
    /**
     * 
     * @type {string}
     * @memberof BountyOrderPaymentInfo
     */
    paymentStatusAsEnum?: BountyOrderPaymentInfoPaymentStatusAsEnumEnum;
}


/**
 * @export
 */
export const BountyOrderPaymentInfoPaymentMethodAsEnumEnum = {
    NONE: 'NONE',
    DEBIT: 'DEBIT',
    CASH: 'CASH',
    STRIPE: 'STRIPE',
    BILLMYBANK: 'BILLMYBANK',
    CHARGEE: 'CHARGEE',
    BILLMYBANK_STAGE: 'BILLMYBANK_STAGE',
    CHARGEE_STAGE: 'CHARGEE_STAGE',
    BILLMYBANK_SANDBOX: 'BILLMYBANK_SANDBOX',
    CHARGEE_SANDBOX: 'CHARGEE_SANDBOX',
    UNKNOWN: 'UNKNOWN'
} as const;
export type BountyOrderPaymentInfoPaymentMethodAsEnumEnum = typeof BountyOrderPaymentInfoPaymentMethodAsEnumEnum[keyof typeof BountyOrderPaymentInfoPaymentMethodAsEnumEnum];

/**
 * @export
 */
export const BountyOrderPaymentInfoPaymentStatusAsEnumEnum = {
    NONE: 'NONE',
    PENDING_PAYMENT: 'PENDING_PAYMENT',
    PROCESSING_PAYMENT: 'PROCESSING_PAYMENT',
    PENDING_CONFIRM: 'PENDING_CONFIRM',
    PAID: 'PAID',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    UNKNOWN: 'UNKNOWN'
} as const;
export type BountyOrderPaymentInfoPaymentStatusAsEnumEnum = typeof BountyOrderPaymentInfoPaymentStatusAsEnumEnum[keyof typeof BountyOrderPaymentInfoPaymentStatusAsEnumEnum];


/**
 * Check if a given object implements the BountyOrderPaymentInfo interface.
 */
export function instanceOfBountyOrderPaymentInfo(value: object): value is BountyOrderPaymentInfo {
    return true;
}

export function BountyOrderPaymentInfoFromJSON(json: any): BountyOrderPaymentInfo {
    return BountyOrderPaymentInfoFromJSONTyped(json, false);
}

export function BountyOrderPaymentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyOrderPaymentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'paymentStatus': json['paymentStatus'] == null ? undefined : json['paymentStatus'],
        'bmbPayment': json['bmbPayment'] == null ? undefined : BountyOrderPaymentInfoBillMyBankPaymentFromJSON(json['bmbPayment']),
        'failureMessage': json['failureMessage'] == null ? undefined : json['failureMessage'],
        'nextStepInfo': json['nextStepInfo'] == null ? undefined : BountyOrderNextStepInfoFromJSON(json['nextStepInfo']),
        'paymentMethodAsEnum': json['paymentMethodAsEnum'] == null ? undefined : json['paymentMethodAsEnum'],
        'paymentStatusAsEnum': json['paymentStatusAsEnum'] == null ? undefined : json['paymentStatusAsEnum'],
    };
}

export function BountyOrderPaymentInfoToJSON(json: any): BountyOrderPaymentInfo {
    return BountyOrderPaymentInfoToJSONTyped(json, false);
}

export function BountyOrderPaymentInfoToJSONTyped(value?: BountyOrderPaymentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'paymentMethod': value['paymentMethod'],
        'paymentStatus': value['paymentStatus'],
        'bmbPayment': BountyOrderPaymentInfoBillMyBankPaymentToJSON(value['bmbPayment']),
        'failureMessage': value['failureMessage'],
        'nextStepInfo': BountyOrderNextStepInfoToJSON(value['nextStepInfo']),
        'paymentMethodAsEnum': value['paymentMethodAsEnum'],
        'paymentStatusAsEnum': value['paymentStatusAsEnum'],
    };
}

