/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BountyAddressedTo
 */
export interface BountyAddressedTo {
    /**
     * 
     * @type {string}
     * @memberof BountyAddressedTo
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof BountyAddressedTo
     */
    appLink?: string;
}

/**
 * Check if a given object implements the BountyAddressedTo interface.
 */
export function instanceOfBountyAddressedTo(value: object): value is BountyAddressedTo {
    return true;
}

export function BountyAddressedToFromJSON(json: any): BountyAddressedTo {
    return BountyAddressedToFromJSONTyped(json, false);
}

export function BountyAddressedToFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyAddressedTo {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'appLink': json['appLink'] == null ? undefined : json['appLink'],
    };
}

export function BountyAddressedToToJSON(json: any): BountyAddressedTo {
    return BountyAddressedToToJSONTyped(json, false);
}

export function BountyAddressedToToJSONTyped(value?: BountyAddressedTo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'appLink': value['appLink'],
    };
}

