/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BountyBountyCategory } from './BountyBountyCategory';
import {
    BountyBountyCategoryFromJSON,
    BountyBountyCategoryFromJSONTyped,
    BountyBountyCategoryToJSON,
    BountyBountyCategoryToJSONTyped,
} from './BountyBountyCategory';

/**
 * 
 * @export
 * @interface BountyChangesChangesMapStringBountyBountyCategory
 */
export interface BountyChangesChangesMapStringBountyBountyCategory {
    /**
     * 
     * @type {{ [key: string]: BountyBountyCategory; }}
     * @memberof BountyChangesChangesMapStringBountyBountyCategory
     */
    newValue?: { [key: string]: BountyBountyCategory; };
    /**
     * 
     * @type {{ [key: string]: BountyBountyCategory; }}
     * @memberof BountyChangesChangesMapStringBountyBountyCategory
     */
    oldValue?: { [key: string]: BountyBountyCategory; };
    /**
     * 
     * @type {boolean}
     * @memberof BountyChangesChangesMapStringBountyBountyCategory
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the BountyChangesChangesMapStringBountyBountyCategory interface.
 */
export function instanceOfBountyChangesChangesMapStringBountyBountyCategory(value: object): value is BountyChangesChangesMapStringBountyBountyCategory {
    return true;
}

export function BountyChangesChangesMapStringBountyBountyCategoryFromJSON(json: any): BountyChangesChangesMapStringBountyBountyCategory {
    return BountyChangesChangesMapStringBountyBountyCategoryFromJSONTyped(json, false);
}

export function BountyChangesChangesMapStringBountyBountyCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyChangesChangesMapStringBountyBountyCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'newValue': json['newValue'] == null ? undefined : (mapValues(json['newValue'], BountyBountyCategoryFromJSON)),
        'oldValue': json['oldValue'] == null ? undefined : (mapValues(json['oldValue'], BountyBountyCategoryFromJSON)),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function BountyChangesChangesMapStringBountyBountyCategoryToJSON(json: any): BountyChangesChangesMapStringBountyBountyCategory {
    return BountyChangesChangesMapStringBountyBountyCategoryToJSONTyped(json, false);
}

export function BountyChangesChangesMapStringBountyBountyCategoryToJSONTyped(value?: BountyChangesChangesMapStringBountyBountyCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newValue': value['newValue'] == null ? undefined : (mapValues(value['newValue'], BountyBountyCategoryToJSON)),
        'oldValue': value['oldValue'] == null ? undefined : (mapValues(value['oldValue'], BountyBountyCategoryToJSON)),
        'empty': value['empty'],
    };
}

