/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BountyReservationInfoSpending
 */
export interface BountyReservationInfoSpending {
    /**
     * 
     * @type {Array<string>}
     * @memberof BountyReservationInfoSpending
     */
    checkIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BountyReservationInfoSpending
     */
    posSubTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof BountyReservationInfoSpending
     */
    posTax?: number;
    /**
     * 
     * @type {number}
     * @memberof BountyReservationInfoSpending
     */
    posTip?: number;
    /**
     * 
     * @type {number}
     * @memberof BountyReservationInfoSpending
     */
    posTotalSpend?: number;
    /**
     * 
     * @type {string}
     * @memberof BountyReservationInfoSpending
     */
    currencyCode?: string;
}

/**
 * Check if a given object implements the BountyReservationInfoSpending interface.
 */
export function instanceOfBountyReservationInfoSpending(value: object): value is BountyReservationInfoSpending {
    return true;
}

export function BountyReservationInfoSpendingFromJSON(json: any): BountyReservationInfoSpending {
    return BountyReservationInfoSpendingFromJSONTyped(json, false);
}

export function BountyReservationInfoSpendingFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyReservationInfoSpending {
    if (json == null) {
        return json;
    }
    return {
        
        'checkIds': json['checkIds'] == null ? undefined : json['checkIds'],
        'posSubTotal': json['posSubTotal'] == null ? undefined : json['posSubTotal'],
        'posTax': json['posTax'] == null ? undefined : json['posTax'],
        'posTip': json['posTip'] == null ? undefined : json['posTip'],
        'posTotalSpend': json['posTotalSpend'] == null ? undefined : json['posTotalSpend'],
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
    };
}

export function BountyReservationInfoSpendingToJSON(json: any): BountyReservationInfoSpending {
    return BountyReservationInfoSpendingToJSONTyped(json, false);
}

export function BountyReservationInfoSpendingToJSONTyped(value?: BountyReservationInfoSpending | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkIds': value['checkIds'],
        'posSubTotal': value['posSubTotal'],
        'posTax': value['posTax'],
        'posTip': value['posTip'],
        'posTotalSpend': value['posTotalSpend'],
        'currencyCode': value['currencyCode'],
    };
}

