/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryTreeGenerationCleanupResponse
 */
export interface CategoryTreeGenerationCleanupResponse {
    /**
     * 
     * @type {string}
     * @memberof CategoryTreeGenerationCleanupResponse
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryTreeGenerationCleanupResponse
     */
    companyId?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryTreeGenerationCleanupResponse
     */
    deletedCount?: number;
}

/**
 * Check if a given object implements the CategoryTreeGenerationCleanupResponse interface.
 */
export function instanceOfCategoryTreeGenerationCleanupResponse(value: object): value is CategoryTreeGenerationCleanupResponse {
    return true;
}

export function CategoryTreeGenerationCleanupResponseFromJSON(json: any): CategoryTreeGenerationCleanupResponse {
    return CategoryTreeGenerationCleanupResponseFromJSONTyped(json, false);
}

export function CategoryTreeGenerationCleanupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeGenerationCleanupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'deletedCount': json['deletedCount'] == null ? undefined : json['deletedCount'],
    };
}

export function CategoryTreeGenerationCleanupResponseToJSON(json: any): CategoryTreeGenerationCleanupResponse {
    return CategoryTreeGenerationCleanupResponseToJSONTyped(json, false);
}

export function CategoryTreeGenerationCleanupResponseToJSONTyped(value?: CategoryTreeGenerationCleanupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'companyId': value['companyId'],
        'deletedCount': value['deletedCount'],
    };
}

