/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChargebackInfo } from './ChargebackInfo';
import {
    ChargebackInfoFromJSON,
    ChargebackInfoFromJSONTyped,
    ChargebackInfoToJSON,
    ChargebackInfoToJSONTyped,
} from './ChargebackInfo';

/**
 * 
 * @export
 * @interface ChangesChargebackInfo
 */
export interface ChangesChargebackInfo {
    /**
     * 
     * @type {ChargebackInfo}
     * @memberof ChangesChargebackInfo
     */
    newValue?: ChargebackInfo;
    /**
     * 
     * @type {ChargebackInfo}
     * @memberof ChangesChargebackInfo
     */
    oldValue?: ChargebackInfo;
    /**
     * 
     * @type {boolean}
     * @memberof ChangesChargebackInfo
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the ChangesChargebackInfo interface.
 */
export function instanceOfChangesChargebackInfo(value: object): value is ChangesChargebackInfo {
    return true;
}

export function ChangesChargebackInfoFromJSON(json: any): ChangesChargebackInfo {
    return ChangesChargebackInfoFromJSONTyped(json, false);
}

export function ChangesChargebackInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangesChargebackInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'newValue': json['newValue'] == null ? undefined : ChargebackInfoFromJSON(json['newValue']),
        'oldValue': json['oldValue'] == null ? undefined : ChargebackInfoFromJSON(json['oldValue']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function ChangesChargebackInfoToJSON(json: any): ChangesChargebackInfo {
    return ChangesChargebackInfoToJSONTyped(json, false);
}

export function ChangesChargebackInfoToJSONTyped(value?: ChangesChargebackInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newValue': ChargebackInfoToJSON(value['newValue']),
        'oldValue': ChargebackInfoToJSON(value['oldValue']),
        'empty': value['empty'],
    };
}

