/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageRead
 */
export interface ChatMessageRead {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageRead
     */
    readAt?: number;
}

/**
 * Check if a given object implements the ChatMessageRead interface.
 */
export function instanceOfChatMessageRead(value: object): value is ChatMessageRead {
    return true;
}

export function ChatMessageReadFromJSON(json: any): ChatMessageRead {
    return ChatMessageReadFromJSONTyped(json, false);
}

export function ChatMessageReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageRead {
    if (json == null) {
        return json;
    }
    return {
        
        'readAt': json['readAt'] == null ? undefined : json['readAt'],
    };
}

export function ChatMessageReadToJSON(json: any): ChatMessageRead {
    return ChatMessageReadToJSONTyped(json, false);
}

export function ChatMessageReadToJSONTyped(value?: ChatMessageRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'readAt': value['readAt'],
    };
}

