/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay
 */
export interface CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay
     */
    opacity?: number;
}

/**
 * Check if a given object implements the CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay interface.
 */
export function instanceOfCoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay(value: object): value is CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay {
    return true;
}

export function CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlayFromJSON(json: any): CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay {
    return CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlayFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlayFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'opacity': json['opacity'] == null ? undefined : json['opacity'],
    };
}

export function CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlayToJSON(json: any): CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay {
    return CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlayToJSONTyped(json, false);
}

export function CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlayToJSONTyped(value?: CoEdgeappServerModelBaseSettingsShopSettingsBackgroundOverlay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'opacity': value['opacity'],
    };
}

