/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse
 */
export interface CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse
     */
    companyId?: string;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse
     */
    deletedCount?: number;
}

/**
 * Check if a given object implements the CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse interface.
 */
export function instanceOfCoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse(value: object): value is CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse {
    return true;
}

export function CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponseFromJSON(json: any): CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse {
    return CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponseFromJSONTyped(json, false);
}

export function CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'deletedCount': json['deletedCount'] == null ? undefined : json['deletedCount'],
    };
}

export function CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponseToJSON(json: any): CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse {
    return CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponseToJSONTyped(json, false);
}

export function CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponseToJSONTyped(value?: CoEdgeappServerRestControllerAIControllerCategoryTreeGenerationCleanupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'companyId': value['companyId'],
        'deletedCount': value['deletedCount'],
    };
}

