/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CoEdgeappServerModelPaymentMethod = {
    STRIPE: 'STRIPE',
    PAYROLL: 'PAYROLL',
    OTHER: 'OTHER'
} as const;
export type CoEdgeappServerModelPaymentMethod = typeof CoEdgeappServerModelPaymentMethod[keyof typeof CoEdgeappServerModelPaymentMethod];


export function instanceOfCoEdgeappServerModelPaymentMethod(value: any): boolean {
    for (const key in CoEdgeappServerModelPaymentMethod) {
        if (Object.prototype.hasOwnProperty.call(CoEdgeappServerModelPaymentMethod, key)) {
            if (CoEdgeappServerModelPaymentMethod[key as keyof typeof CoEdgeappServerModelPaymentMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CoEdgeappServerModelPaymentMethodFromJSON(json: any): CoEdgeappServerModelPaymentMethod {
    return CoEdgeappServerModelPaymentMethodFromJSONTyped(json, false);
}

export function CoEdgeappServerModelPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelPaymentMethod {
    return json as CoEdgeappServerModelPaymentMethod;
}

export function CoEdgeappServerModelPaymentMethodToJSON(value?: CoEdgeappServerModelPaymentMethod | null): any {
    return value as any;
}

export function CoEdgeappServerModelPaymentMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): CoEdgeappServerModelPaymentMethod {
    return value as CoEdgeappServerModelPaymentMethod;
}

