/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerModelBountyOrderDriverLicense
 */
export interface CoEdgeappServerModelBountyOrderDriverLicense {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyOrderDriverLicense
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyOrderDriverLicense
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyOrderDriverLicense
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyOrderDriverLicense
     */
    expDate?: string;
}

/**
 * Check if a given object implements the CoEdgeappServerModelBountyOrderDriverLicense interface.
 */
export function instanceOfCoEdgeappServerModelBountyOrderDriverLicense(value: object): value is CoEdgeappServerModelBountyOrderDriverLicense {
    return true;
}

export function CoEdgeappServerModelBountyOrderDriverLicenseFromJSON(json: any): CoEdgeappServerModelBountyOrderDriverLicense {
    return CoEdgeappServerModelBountyOrderDriverLicenseFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyOrderDriverLicenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBountyOrderDriverLicense {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'state': json['state'] == null ? undefined : json['state'],
        'number': json['number'] == null ? undefined : json['number'],
        'expDate': json['expDate'] == null ? undefined : json['expDate'],
    };
}

export function CoEdgeappServerModelBountyOrderDriverLicenseToJSON(json: any): CoEdgeappServerModelBountyOrderDriverLicense {
    return CoEdgeappServerModelBountyOrderDriverLicenseToJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyOrderDriverLicenseToJSONTyped(value?: CoEdgeappServerModelBountyOrderDriverLicense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'countryCode': value['countryCode'],
        'state': value['state'],
        'number': value['number'],
        'expDate': value['expDate'],
    };
}

