/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerModelBountyBudgetBudgetCurrency
 */
export interface CoEdgeappServerModelBountyBudgetBudgetCurrency {
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerModelBountyBudgetBudgetCurrency
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyBudgetBudgetCurrency
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyBudgetBudgetCurrency
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CoEdgeappServerModelBountyBudgetBudgetCurrency
     */
    valid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyBudgetBudgetCurrency
     */
    typeAsEnum?: CoEdgeappServerModelBountyBudgetBudgetCurrencyTypeAsEnumEnum;
}


/**
 * @export
 */
export const CoEdgeappServerModelBountyBudgetBudgetCurrencyTypeAsEnumEnum = {
    NONE: 'NONE',
    MONEY: 'MONEY',
    POINT: 'POINT',
    VOUCHER: 'VOUCHER',
    BADGE: 'BADGE',
    UNKNOWN: 'UNKNOWN'
} as const;
export type CoEdgeappServerModelBountyBudgetBudgetCurrencyTypeAsEnumEnum = typeof CoEdgeappServerModelBountyBudgetBudgetCurrencyTypeAsEnumEnum[keyof typeof CoEdgeappServerModelBountyBudgetBudgetCurrencyTypeAsEnumEnum];


/**
 * Check if a given object implements the CoEdgeappServerModelBountyBudgetBudgetCurrency interface.
 */
export function instanceOfCoEdgeappServerModelBountyBudgetBudgetCurrency(value: object): value is CoEdgeappServerModelBountyBudgetBudgetCurrency {
    return true;
}

export function CoEdgeappServerModelBountyBudgetBudgetCurrencyFromJSON(json: any): CoEdgeappServerModelBountyBudgetBudgetCurrency {
    return CoEdgeappServerModelBountyBudgetBudgetCurrencyFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyBudgetBudgetCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBountyBudgetBudgetCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'type': json['type'] == null ? undefined : json['type'],
        'valid': json['valid'] == null ? undefined : json['valid'],
        'typeAsEnum': json['typeAsEnum'] == null ? undefined : json['typeAsEnum'],
    };
}

export function CoEdgeappServerModelBountyBudgetBudgetCurrencyToJSON(json: any): CoEdgeappServerModelBountyBudgetBudgetCurrency {
    return CoEdgeappServerModelBountyBudgetBudgetCurrencyToJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyBudgetBudgetCurrencyToJSONTyped(value?: CoEdgeappServerModelBountyBudgetBudgetCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'type': value['type'],
        'valid': value['valid'],
        'typeAsEnum': value['typeAsEnum'],
    };
}

