/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerModelEdgeApiDataSmsVerification
 */
export interface CoEdgeappServerModelEdgeApiDataSmsVerification {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelEdgeApiDataSmsVerification
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelEdgeApiDataSmsVerification
     */
    token?: string;
}

/**
 * Check if a given object implements the CoEdgeappServerModelEdgeApiDataSmsVerification interface.
 */
export function instanceOfCoEdgeappServerModelEdgeApiDataSmsVerification(value: object): value is CoEdgeappServerModelEdgeApiDataSmsVerification {
    return true;
}

export function CoEdgeappServerModelEdgeApiDataSmsVerificationFromJSON(json: any): CoEdgeappServerModelEdgeApiDataSmsVerification {
    return CoEdgeappServerModelEdgeApiDataSmsVerificationFromJSONTyped(json, false);
}

export function CoEdgeappServerModelEdgeApiDataSmsVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelEdgeApiDataSmsVerification {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function CoEdgeappServerModelEdgeApiDataSmsVerificationToJSON(json: any): CoEdgeappServerModelEdgeApiDataSmsVerification {
    return CoEdgeappServerModelEdgeApiDataSmsVerificationToJSONTyped(json, false);
}

export function CoEdgeappServerModelEdgeApiDataSmsVerificationToJSONTyped(value?: CoEdgeappServerModelEdgeApiDataSmsVerification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'token': value['token'],
    };
}

