/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoEdgeappServerModelUserProfileInterest } from './CoEdgeappServerModelUserProfileInterest';
import {
    CoEdgeappServerModelUserProfileInterestFromJSON,
    CoEdgeappServerModelUserProfileInterestFromJSONTyped,
    CoEdgeappServerModelUserProfileInterestToJSON,
    CoEdgeappServerModelUserProfileInterestToJSONTyped,
} from './CoEdgeappServerModelUserProfileInterest';

/**
 * 
 * @export
 * @interface CoEdgeappServerModelUserProfileInterestsInfo
 */
export interface CoEdgeappServerModelUserProfileInterestsInfo {
    /**
     * 
     * @type {{ [key: string]: { [key: string]: CoEdgeappServerModelUserProfileInterest; }; }}
     * @memberof CoEdgeappServerModelUserProfileInterestsInfo
     */
    interests?: { [key: string]: { [key: string]: CoEdgeappServerModelUserProfileInterest; }; };
}

/**
 * Check if a given object implements the CoEdgeappServerModelUserProfileInterestsInfo interface.
 */
export function instanceOfCoEdgeappServerModelUserProfileInterestsInfo(value: object): value is CoEdgeappServerModelUserProfileInterestsInfo {
    return true;
}

export function CoEdgeappServerModelUserProfileInterestsInfoFromJSON(json: any): CoEdgeappServerModelUserProfileInterestsInfo {
    return CoEdgeappServerModelUserProfileInterestsInfoFromJSONTyped(json, false);
}

export function CoEdgeappServerModelUserProfileInterestsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelUserProfileInterestsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'interests': json['interests'] == null ? undefined : json['interests'],
    };
}

export function CoEdgeappServerModelUserProfileInterestsInfoToJSON(json: any): CoEdgeappServerModelUserProfileInterestsInfo {
    return CoEdgeappServerModelUserProfileInterestsInfoToJSONTyped(json, false);
}

export function CoEdgeappServerModelUserProfileInterestsInfoToJSONTyped(value?: CoEdgeappServerModelUserProfileInterestsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interests': value['interests'],
    };
}

