/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo
 */
export interface CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo {
    /**
     * 
     * @type {boolean}
     * @memberof CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo
     */
    allow?: boolean;
}

/**
 * Check if a given object implements the CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo interface.
 */
export function instanceOfCoEdgeappServerModelBaseSettingsItemDefVisibilityInfo(value: object): value is CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo {
    return true;
}

export function CoEdgeappServerModelBaseSettingsItemDefVisibilityInfoFromJSON(json: any): CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo {
    return CoEdgeappServerModelBaseSettingsItemDefVisibilityInfoFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBaseSettingsItemDefVisibilityInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'allow': json['allow'] == null ? undefined : json['allow'],
    };
}

export function CoEdgeappServerModelBaseSettingsItemDefVisibilityInfoToJSON(json: any): CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo {
    return CoEdgeappServerModelBaseSettingsItemDefVisibilityInfoToJSONTyped(json, false);
}

export function CoEdgeappServerModelBaseSettingsItemDefVisibilityInfoToJSONTyped(value?: CoEdgeappServerModelBaseSettingsItemDefVisibilityInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow': value['allow'],
    };
}

