/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoEdgeappServerModelUser } from './CoEdgeappServerModelUser';
import {
    CoEdgeappServerModelUserFromJSON,
    CoEdgeappServerModelUserFromJSONTyped,
    CoEdgeappServerModelUserToJSON,
    CoEdgeappServerModelUserToJSONTyped,
} from './CoEdgeappServerModelUser';
import type { CoEdgeappServerModelIdentityMode } from './CoEdgeappServerModelIdentityMode';
import {
    CoEdgeappServerModelIdentityModeFromJSON,
    CoEdgeappServerModelIdentityModeFromJSONTyped,
    CoEdgeappServerModelIdentityModeToJSON,
    CoEdgeappServerModelIdentityModeToJSONTyped,
} from './CoEdgeappServerModelIdentityMode';

/**
 * 
 * @export
 * @interface CoEdgeappServerModelComment
 */
export interface CoEdgeappServerModelComment {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    commentType?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    commentState?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    commentVisibilityType?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    audienceType?: CoEdgeappServerModelCommentAudienceTypeEnum;
    /**
     * 
     * @type {CoEdgeappServerModelUser}
     * @memberof CoEdgeappServerModelComment
     */
    creator?: CoEdgeappServerModelUser;
    /**
     * 
     * @type {CoEdgeappServerModelUser}
     * @memberof CoEdgeappServerModelComment
     */
    author?: CoEdgeappServerModelUser;
    /**
     * 
     * @type {CoEdgeappServerModelIdentityMode}
     * @memberof CoEdgeappServerModelComment
     */
    identityMode?: CoEdgeappServerModelIdentityMode;
    /**
     * 
     * @type {any}
     * @memberof CoEdgeappServerModelComment
     */
    reward?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    refBountyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelComment
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerModelComment
     */
    sentAt?: number;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerModelComment
     */
    editedAt?: number;
}


/**
 * @export
 */
export const CoEdgeappServerModelCommentAudienceTypeEnum = {
    PUBLIC: 'PUBLIC',
    JOURNAL: 'JOURNAL',
    UNKNOWN: 'UNKNOWN'
} as const;
export type CoEdgeappServerModelCommentAudienceTypeEnum = typeof CoEdgeappServerModelCommentAudienceTypeEnum[keyof typeof CoEdgeappServerModelCommentAudienceTypeEnum];


/**
 * Check if a given object implements the CoEdgeappServerModelComment interface.
 */
export function instanceOfCoEdgeappServerModelComment(value: object): value is CoEdgeappServerModelComment {
    return true;
}

export function CoEdgeappServerModelCommentFromJSON(json: any): CoEdgeappServerModelComment {
    return CoEdgeappServerModelCommentFromJSONTyped(json, false);
}

export function CoEdgeappServerModelCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelComment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
        'commentType': json['commentType'] == null ? undefined : json['commentType'],
        'commentState': json['commentState'] == null ? undefined : json['commentState'],
        'commentVisibilityType': json['commentVisibilityType'] == null ? undefined : json['commentVisibilityType'],
        'audienceType': json['audienceType'] == null ? undefined : json['audienceType'],
        'creator': json['creator'] == null ? undefined : CoEdgeappServerModelUserFromJSON(json['creator']),
        'author': json['author'] == null ? undefined : CoEdgeappServerModelUserFromJSON(json['author']),
        'identityMode': json['identityMode'] == null ? undefined : CoEdgeappServerModelIdentityModeFromJSON(json['identityMode']),
        'reward': json['reward'] == null ? undefined : json['reward'],
        'refBountyId': json['refBountyId'] == null ? undefined : json['refBountyId'],
        'text': json['text'] == null ? undefined : json['text'],
        'sentAt': json['sentAt'] == null ? undefined : json['sentAt'],
        'editedAt': json['editedAt'] == null ? undefined : json['editedAt'],
    };
}

export function CoEdgeappServerModelCommentToJSON(json: any): CoEdgeappServerModelComment {
    return CoEdgeappServerModelCommentToJSONTyped(json, false);
}

export function CoEdgeappServerModelCommentToJSONTyped(value?: CoEdgeappServerModelComment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'entityId': value['entityId'],
        'commentType': value['commentType'],
        'commentState': value['commentState'],
        'commentVisibilityType': value['commentVisibilityType'],
        'audienceType': value['audienceType'],
        'creator': CoEdgeappServerModelUserToJSON(value['creator']),
        'author': CoEdgeappServerModelUserToJSON(value['author']),
        'identityMode': CoEdgeappServerModelIdentityModeToJSON(value['identityMode']),
        'reward': value['reward'],
        'refBountyId': value['refBountyId'],
        'text': value['text'],
        'sentAt': value['sentAt'],
        'editedAt': value['editedAt'],
    };
}

