/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
 */
export interface CoEdgeappServerRestControllerAIControllerProductGeneratorStatus {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    phase?: CoEdgeappServerRestControllerAIControllerProductGeneratorStatusPhaseEnum;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    progressDoneUnits?: number;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    progressTotalUnits?: number;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    generatedProducts?: number;
    /**
     * 
     * @type {number}
     * @memberof CoEdgeappServerRestControllerAIControllerProductGeneratorStatus
     */
    persistedProducts?: number;
}


/**
 * @export
 */
export const CoEdgeappServerRestControllerAIControllerProductGeneratorStatusPhaseEnum = {
    INSTRUCTIONS: 'INSTRUCTIONS',
    IMAGES: 'IMAGES',
    FINALIZING: 'FINALIZING'
} as const;
export type CoEdgeappServerRestControllerAIControllerProductGeneratorStatusPhaseEnum = typeof CoEdgeappServerRestControllerAIControllerProductGeneratorStatusPhaseEnum[keyof typeof CoEdgeappServerRestControllerAIControllerProductGeneratorStatusPhaseEnum];


/**
 * Check if a given object implements the CoEdgeappServerRestControllerAIControllerProductGeneratorStatus interface.
 */
export function instanceOfCoEdgeappServerRestControllerAIControllerProductGeneratorStatus(value: object): value is CoEdgeappServerRestControllerAIControllerProductGeneratorStatus {
    return true;
}

export function CoEdgeappServerRestControllerAIControllerProductGeneratorStatusFromJSON(json: any): CoEdgeappServerRestControllerAIControllerProductGeneratorStatus {
    return CoEdgeappServerRestControllerAIControllerProductGeneratorStatusFromJSONTyped(json, false);
}

export function CoEdgeappServerRestControllerAIControllerProductGeneratorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerRestControllerAIControllerProductGeneratorStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'progressDoneUnits': json['progressDoneUnits'] == null ? undefined : json['progressDoneUnits'],
        'progressTotalUnits': json['progressTotalUnits'] == null ? undefined : json['progressTotalUnits'],
        'generatedProducts': json['generatedProducts'] == null ? undefined : json['generatedProducts'],
        'persistedProducts': json['persistedProducts'] == null ? undefined : json['persistedProducts'],
    };
}

export function CoEdgeappServerRestControllerAIControllerProductGeneratorStatusToJSON(json: any): CoEdgeappServerRestControllerAIControllerProductGeneratorStatus {
    return CoEdgeappServerRestControllerAIControllerProductGeneratorStatusToJSONTyped(json, false);
}

export function CoEdgeappServerRestControllerAIControllerProductGeneratorStatusToJSONTyped(value?: CoEdgeappServerRestControllerAIControllerProductGeneratorStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'companyId': value['companyId'],
        'phase': value['phase'],
        'progressDoneUnits': value['progressDoneUnits'],
        'progressTotalUnits': value['progressTotalUnits'],
        'generatedProducts': value['generatedProducts'],
        'persistedProducts': value['persistedProducts'],
    };
}

