/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoEdgeappServerModelBountyReservationInfo } from './CoEdgeappServerModelBountyReservationInfo';
import {
    CoEdgeappServerModelBountyReservationInfoFromJSON,
    CoEdgeappServerModelBountyReservationInfoFromJSONTyped,
    CoEdgeappServerModelBountyReservationInfoToJSON,
    CoEdgeappServerModelBountyReservationInfoToJSONTyped,
} from './CoEdgeappServerModelBountyReservationInfo';

/**
 * 
 * @export
 * @interface CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo
 */
export interface CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo {
    /**
     * 
     * @type {CoEdgeappServerModelBountyReservationInfo}
     * @memberof CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo
     */
    newValue?: CoEdgeappServerModelBountyReservationInfo;
    /**
     * 
     * @type {CoEdgeappServerModelBountyReservationInfo}
     * @memberof CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo
     */
    oldValue?: CoEdgeappServerModelBountyReservationInfo;
    /**
     * 
     * @type {boolean}
     * @memberof CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo interface.
 */
export function instanceOfCoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo(value: object): value is CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo {
    return true;
}

export function CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfoFromJSON(json: any): CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo {
    return CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfoFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'newValue': json['newValue'] == null ? undefined : CoEdgeappServerModelBountyReservationInfoFromJSON(json['newValue']),
        'oldValue': json['oldValue'] == null ? undefined : CoEdgeappServerModelBountyReservationInfoFromJSON(json['oldValue']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfoToJSON(json: any): CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo {
    return CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfoToJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfoToJSONTyped(value?: CoEdgeappServerModelBountyChangesChangesCoEdgeappServerModelBountyReservationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newValue': CoEdgeappServerModelBountyReservationInfoToJSON(value['newValue']),
        'oldValue': CoEdgeappServerModelBountyReservationInfoToJSON(value['oldValue']),
        'empty': value['empty'],
    };
}

