/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation } from './CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation';
import {
    CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationFromJSON,
    CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationFromJSONTyped,
    CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationToJSON,
    CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationToJSONTyped,
} from './CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation';

/**
 * 
 * @export
 * @interface CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation
 */
export interface CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation {
    /**
     * 
     * @type {CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation}
     * @memberof CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation
     */
    common?: CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation;
    /**
     * 
     * @type {CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation}
     * @memberof CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation
     */
    pickup?: CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation;
    /**
     * 
     * @type {CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation}
     * @memberof CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation
     */
    delivery?: CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperation;
}

/**
 * Check if a given object implements the CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation interface.
 */
export function instanceOfCoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation(value: object): value is CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation {
    return true;
}

export function CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationFromJSON(json: any): CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation {
    return CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'common': json['common'] == null ? undefined : CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationFromJSON(json['common']),
        'pickup': json['pickup'] == null ? undefined : CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationFromJSON(json['pickup']),
        'delivery': json['delivery'] == null ? undefined : CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationFromJSON(json['delivery']),
    };
}

export function CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationToJSON(json: any): CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation {
    return CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationToJSONTyped(json, false);
}

export function CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationToJSONTyped(value?: CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'common': CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationToJSON(value['common']),
        'pickup': CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationToJSON(value['pickup']),
        'delivery': CoEdgeappServerModelBaseSettingsShopSettingsShopOperationShopSpecialHoursOfOperationSpecialHoursOfOperationToJSON(value['delivery']),
    };
}

