/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoEdgeappServerModelBountyMenuInfoPresentationMedia } from './CoEdgeappServerModelBountyMenuInfoPresentationMedia';
import {
    CoEdgeappServerModelBountyMenuInfoPresentationMediaFromJSON,
    CoEdgeappServerModelBountyMenuInfoPresentationMediaFromJSONTyped,
    CoEdgeappServerModelBountyMenuInfoPresentationMediaToJSON,
    CoEdgeappServerModelBountyMenuInfoPresentationMediaToJSONTyped,
} from './CoEdgeappServerModelBountyMenuInfoPresentationMedia';

/**
 * 
 * @export
 * @interface CoEdgeappServerModelBountyMenuInfoSectionPresentation
 */
export interface CoEdgeappServerModelBountyMenuInfoSectionPresentation {
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyMenuInfoSectionPresentation
     */
    subtitle?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyMenuInfoSectionPresentation
     */
    badge?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyMenuInfoSectionPresentation
     */
    accentColor?: string;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyMenuInfoSectionPresentation
     */
    layoutStyle?: string;
    /**
     * 
     * @type {CoEdgeappServerModelBountyMenuInfoPresentationMedia}
     * @memberof CoEdgeappServerModelBountyMenuInfoSectionPresentation
     */
    backgroundMedia?: CoEdgeappServerModelBountyMenuInfoPresentationMedia;
    /**
     * 
     * @type {string}
     * @memberof CoEdgeappServerModelBountyMenuInfoSectionPresentation
     */
    layoutStyleAsEnum?: CoEdgeappServerModelBountyMenuInfoSectionPresentationLayoutStyleAsEnumEnum;
}


/**
 * @export
 */
export const CoEdgeappServerModelBountyMenuInfoSectionPresentationLayoutStyleAsEnumEnum = {
    CAROUSEL: 'CAROUSEL',
    GRID: 'GRID',
    LIST: 'LIST',
    UNKNOWN: 'UNKNOWN'
} as const;
export type CoEdgeappServerModelBountyMenuInfoSectionPresentationLayoutStyleAsEnumEnum = typeof CoEdgeappServerModelBountyMenuInfoSectionPresentationLayoutStyleAsEnumEnum[keyof typeof CoEdgeappServerModelBountyMenuInfoSectionPresentationLayoutStyleAsEnumEnum];


/**
 * Check if a given object implements the CoEdgeappServerModelBountyMenuInfoSectionPresentation interface.
 */
export function instanceOfCoEdgeappServerModelBountyMenuInfoSectionPresentation(value: object): value is CoEdgeappServerModelBountyMenuInfoSectionPresentation {
    return true;
}

export function CoEdgeappServerModelBountyMenuInfoSectionPresentationFromJSON(json: any): CoEdgeappServerModelBountyMenuInfoSectionPresentation {
    return CoEdgeappServerModelBountyMenuInfoSectionPresentationFromJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyMenuInfoSectionPresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoEdgeappServerModelBountyMenuInfoSectionPresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'badge': json['badge'] == null ? undefined : json['badge'],
        'accentColor': json['accentColor'] == null ? undefined : json['accentColor'],
        'layoutStyle': json['layoutStyle'] == null ? undefined : json['layoutStyle'],
        'backgroundMedia': json['backgroundMedia'] == null ? undefined : CoEdgeappServerModelBountyMenuInfoPresentationMediaFromJSON(json['backgroundMedia']),
        'layoutStyleAsEnum': json['layoutStyleAsEnum'] == null ? undefined : json['layoutStyleAsEnum'],
    };
}

export function CoEdgeappServerModelBountyMenuInfoSectionPresentationToJSON(json: any): CoEdgeappServerModelBountyMenuInfoSectionPresentation {
    return CoEdgeappServerModelBountyMenuInfoSectionPresentationToJSONTyped(json, false);
}

export function CoEdgeappServerModelBountyMenuInfoSectionPresentationToJSONTyped(value?: CoEdgeappServerModelBountyMenuInfoSectionPresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subtitle': value['subtitle'],
        'badge': value['badge'],
        'accentColor': value['accentColor'],
        'layoutStyle': value['layoutStyle'],
        'backgroundMedia': CoEdgeappServerModelBountyMenuInfoPresentationMediaToJSON(value['backgroundMedia']),
        'layoutStyleAsEnum': value['layoutStyleAsEnum'],
    };
}

