/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientInfo } from './ClientInfo';
import {
    ClientInfoFromJSON,
    ClientInfoFromJSONTyped,
    ClientInfoToJSON,
    ClientInfoToJSONTyped,
} from './ClientInfo';

/**
 * 
 * @export
 * @interface CompanyData
 */
export interface CompanyData {
    /**
     * 
     * @type {string}
     * @memberof CompanyData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyData
     */
    name?: string;
    /**
     * 
     * @type {ClientInfo}
     * @memberof CompanyData
     */
    clientInfo?: ClientInfo;
    /**
     * 
     * @type {string}
     * @memberof CompanyData
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyData
     */
    orgType?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyData
     */
    pin?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyData
     */
    createdAt?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyData
     */
    status?: CompanyDataStatusEnum;
}


/**
 * @export
 */
export const CompanyDataStatusEnum = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    SUSPENDED: 'SUSPENDED',
    BLACKLISTED: 'BLACKLISTED',
    TO_BE_DELETED: 'TO_BE_DELETED',
    DELETED: 'DELETED',
    UNKNOWN: 'UNKNOWN'
} as const;
export type CompanyDataStatusEnum = typeof CompanyDataStatusEnum[keyof typeof CompanyDataStatusEnum];


/**
 * Check if a given object implements the CompanyData interface.
 */
export function instanceOfCompanyData(value: object): value is CompanyData {
    return true;
}

export function CompanyDataFromJSON(json: any): CompanyData {
    return CompanyDataFromJSONTyped(json, false);
}

export function CompanyDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'clientInfo': json['clientInfo'] == null ? undefined : ClientInfoFromJSON(json['clientInfo']),
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'orgType': json['orgType'] == null ? undefined : json['orgType'],
        'pin': json['pin'] == null ? undefined : json['pin'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CompanyDataToJSON(json: any): CompanyData {
    return CompanyDataToJSONTyped(json, false);
}

export function CompanyDataToJSONTyped(value?: CompanyData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'clientInfo': ClientInfoToJSON(value['clientInfo']),
        'countryCode': value['countryCode'],
        'orgType': value['orgType'],
        'pin': value['pin'],
        'createdAt': value['createdAt'],
        'status': value['status'],
    };
}

