/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemDefVisibilityInfo } from './ItemDefVisibilityInfo';
import {
    ItemDefVisibilityInfoFromJSON,
    ItemDefVisibilityInfoFromJSONTyped,
    ItemDefVisibilityInfoToJSON,
    ItemDefVisibilityInfoToJSONTyped,
} from './ItemDefVisibilityInfo';

/**
 * 
 * @export
 * @interface DrawerItemDef
 */
export interface DrawerItemDef {
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    op?: string;
    /**
     * 
     * @type {number}
     * @memberof DrawerItemDef
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawerItemDef
     */
    color?: string;
    /**
     * 
     * @type {{ [key: string]: ItemDefVisibilityInfo; }}
     * @memberof DrawerItemDef
     */
    visibilityInfos?: { [key: string]: ItemDefVisibilityInfo; };
    /**
     * 
     * @type {Array<string>}
     * @memberof DrawerItemDef
     */
    parsedTags?: Array<string>;
}

/**
 * Check if a given object implements the DrawerItemDef interface.
 */
export function instanceOfDrawerItemDef(value: object): value is DrawerItemDef {
    return true;
}

export function DrawerItemDefFromJSON(json: any): DrawerItemDef {
    return DrawerItemDefFromJSONTyped(json, false);
}

export function DrawerItemDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawerItemDef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'op': json['op'] == null ? undefined : json['op'],
        'order': json['order'] == null ? undefined : json['order'],
        'action': json['action'] == null ? undefined : json['action'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'color': json['color'] == null ? undefined : json['color'],
        'visibilityInfos': json['visibilityInfos'] == null ? undefined : (mapValues(json['visibilityInfos'], ItemDefVisibilityInfoFromJSON)),
        'parsedTags': json['parsedTags'] == null ? undefined : json['parsedTags'],
    };
}

export function DrawerItemDefToJSON(json: any): DrawerItemDef {
    return DrawerItemDefToJSONTyped(json, false);
}

export function DrawerItemDefToJSONTyped(value?: DrawerItemDef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'tags': value['tags'],
        'icon': value['icon'],
        'op': value['op'],
        'order': value['order'],
        'action': value['action'],
        'parentId': value['parentId'],
        'color': value['color'],
        'visibilityInfos': value['visibilityInfos'] == null ? undefined : (mapValues(value['visibilityInfos'], ItemDefVisibilityInfoToJSON)),
        'parsedTags': value['parsedTags'],
    };
}

