/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';

/**
 * 
 * @export
 * @interface Earnings
 */
export interface Earnings {
    /**
     * 
     * @type {Reward}
     * @memberof Earnings
     */
    earnedAmount?: Reward;
    /**
     * 
     * @type {Reward}
     * @memberof Earnings
     */
    maxAmount?: Reward;
}

/**
 * Check if a given object implements the Earnings interface.
 */
export function instanceOfEarnings(value: object): value is Earnings {
    return true;
}

export function EarningsFromJSON(json: any): Earnings {
    return EarningsFromJSONTyped(json, false);
}

export function EarningsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Earnings {
    if (json == null) {
        return json;
    }
    return {
        
        'earnedAmount': json['earnedAmount'] == null ? undefined : RewardFromJSON(json['earnedAmount']),
        'maxAmount': json['maxAmount'] == null ? undefined : RewardFromJSON(json['maxAmount']),
    };
}

export function EarningsToJSON(json: any): Earnings {
    return EarningsToJSONTyped(json, false);
}

export function EarningsToJSONTyped(value?: Earnings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'earnedAmount': RewardToJSON(value['earnedAmount']),
        'maxAmount': RewardToJSON(value['maxAmount']),
    };
}

