/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EdgeApiDataSurveyResp } from './EdgeApiDataSurveyResp';
import {
    EdgeApiDataSurveyRespFromJSON,
    EdgeApiDataSurveyRespFromJSONTyped,
    EdgeApiDataSurveyRespToJSON,
    EdgeApiDataSurveyRespToJSONTyped,
} from './EdgeApiDataSurveyResp';
import type { Attachments } from './Attachments';
import {
    AttachmentsFromJSON,
    AttachmentsFromJSONTyped,
    AttachmentsToJSON,
    AttachmentsToJSONTyped,
} from './Attachments';

/**
 * 
 * @export
 * @interface EdgeApiDataSurveyBundleResp
 */
export interface EdgeApiDataSurveyBundleResp {
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataSurveyBundleResp
     */
    bountyId?: string;
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataSurveyBundleResp
     */
    bountyType?: EdgeApiDataSurveyBundleRespBountyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataSurveyBundleResp
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataSurveyBundleResp
     */
    description?: string;
    /**
     * 
     * @type {Attachments}
     * @memberof EdgeApiDataSurveyBundleResp
     */
    attachments?: Attachments;
    /**
     * 
     * @type {Array<EdgeApiDataSurveyResp>}
     * @memberof EdgeApiDataSurveyBundleResp
     */
    surveys?: Array<EdgeApiDataSurveyResp>;
}


/**
 * @export
 */
export const EdgeApiDataSurveyBundleRespBountyTypeEnum = {
    NONE: 'NONE',
    QUESTION: 'QUESTION',
    THREAD: 'THREAD',
    TALENT_SEARCH: 'TALENT_SEARCH',
    TALENT_RECOMMENDATION: 'TALENT_RECOMMENDATION',
    TMOB_CHALLENGE: 'TMOB_CHALLENGE',
    TMOB_COACHING: 'TMOB_COACHING',
    ORDER: 'ORDER',
    REALESTATE_CUSTOMER: 'REALESTATE_CUSTOMER',
    REALESTATE_RECOMMENDATION: 'REALESTATE_RECOMMENDATION',
    SURVEY: 'SURVEY',
    CLASSIFIED: 'CLASSIFIED',
    PRODUCT: 'PRODUCT',
    MENU: 'MENU',
    BUNDLE: 'BUNDLE',
    STORY: 'STORY',
    SCORE: 'SCORE',
    SERIES: 'SERIES',
    CHECKLIST: 'CHECKLIST',
    SUPPORT: 'SUPPORT',
    AI_BOT: 'AI_BOT',
    DEAL: 'DEAL',
    PROMOTION: 'PROMOTION',
    AUTOSUGGESTION: 'AUTOSUGGESTION',
    APPROVAL: 'APPROVAL',
    MCQ: 'MCQ',
    FUNDING: 'FUNDING',
    AUCTION: 'AUCTION',
    ROLEPLAY: 'ROLEPLAY',
    PRIVATE_LISTING: 'PRIVATE_LISTING',
    QUEST: 'QUEST',
    LIVE_STREAM: 'LIVE_STREAM',
    ALBUM: 'ALBUM',
    NEWS: 'NEWS',
    BANNER: 'BANNER',
    MATCH: 'MATCH',
    CONTEST: 'CONTEST',
    TRIVIA: 'TRIVIA',
    LOTTERY: 'LOTTERY',
    BADGE_COLLECTION: 'BADGE_COLLECTION',
    RAFFLE: 'RAFFLE',
    CALENDAR_EVENT: 'CALENDAR_EVENT',
    CURRENCY: 'CURRENCY',
    RESERVATION: 'RESERVATION',
    QUICK_CLAIM: 'QUICK_CLAIM',
    CAMPAIGN: 'CAMPAIGN',
    EXPRESS_CAMPAIGN: 'EXPRESS_CAMPAIGN',
    GEO_LOCATION: 'GEO_LOCATION',
    FEEDBACK: 'FEEDBACK',
    SUBSCRIPTION: 'SUBSCRIPTION',
    SUBSCRIPTION_TIER: 'SUBSCRIPTION_TIER',
    UNKNOWN: 'UNKNOWN'
} as const;
export type EdgeApiDataSurveyBundleRespBountyTypeEnum = typeof EdgeApiDataSurveyBundleRespBountyTypeEnum[keyof typeof EdgeApiDataSurveyBundleRespBountyTypeEnum];


/**
 * Check if a given object implements the EdgeApiDataSurveyBundleResp interface.
 */
export function instanceOfEdgeApiDataSurveyBundleResp(value: object): value is EdgeApiDataSurveyBundleResp {
    return true;
}

export function EdgeApiDataSurveyBundleRespFromJSON(json: any): EdgeApiDataSurveyBundleResp {
    return EdgeApiDataSurveyBundleRespFromJSONTyped(json, false);
}

export function EdgeApiDataSurveyBundleRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): EdgeApiDataSurveyBundleResp {
    if (json == null) {
        return json;
    }
    return {
        
        'bountyId': json['bountyId'] == null ? undefined : json['bountyId'],
        'bountyType': json['bountyType'] == null ? undefined : json['bountyType'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'attachments': json['attachments'] == null ? undefined : AttachmentsFromJSON(json['attachments']),
        'surveys': json['surveys'] == null ? undefined : ((json['surveys'] as Array<any>).map(EdgeApiDataSurveyRespFromJSON)),
    };
}

export function EdgeApiDataSurveyBundleRespToJSON(json: any): EdgeApiDataSurveyBundleResp {
    return EdgeApiDataSurveyBundleRespToJSONTyped(json, false);
}

export function EdgeApiDataSurveyBundleRespToJSONTyped(value?: EdgeApiDataSurveyBundleResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bountyId': value['bountyId'],
        'bountyType': value['bountyType'],
        'title': value['title'],
        'description': value['description'],
        'attachments': AttachmentsToJSON(value['attachments']),
        'surveys': value['surveys'] == null ? undefined : ((value['surveys'] as Array<any>).map(EdgeApiDataSurveyRespToJSON)),
    };
}

