/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShoppingCart } from './ShoppingCart';
import {
    ShoppingCartFromJSON,
    ShoppingCartFromJSONTyped,
    ShoppingCartToJSON,
    ShoppingCartToJSONTyped,
} from './ShoppingCart';

/**
 * 
 * @export
 * @interface EdgeApiDataPageShoppingCart
 */
export interface EdgeApiDataPageShoppingCart {
    /**
     * 
     * @type {number}
     * @memberof EdgeApiDataPageShoppingCart
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof EdgeApiDataPageShoppingCart
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof EdgeApiDataPageShoppingCart
     */
    length?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EdgeApiDataPageShoppingCart
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {Array<ShoppingCart>}
     * @memberof EdgeApiDataPageShoppingCart
     */
    list?: Array<ShoppingCart>;
}

/**
 * Check if a given object implements the EdgeApiDataPageShoppingCart interface.
 */
export function instanceOfEdgeApiDataPageShoppingCart(value: object): value is EdgeApiDataPageShoppingCart {
    return true;
}

export function EdgeApiDataPageShoppingCartFromJSON(json: any): EdgeApiDataPageShoppingCart {
    return EdgeApiDataPageShoppingCartFromJSONTyped(json, false);
}

export function EdgeApiDataPageShoppingCartFromJSONTyped(json: any, ignoreDiscriminator: boolean): EdgeApiDataPageShoppingCart {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'start': json['start'] == null ? undefined : json['start'],
        'length': json['length'] == null ? undefined : json['length'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(ShoppingCartFromJSON)),
    };
}

export function EdgeApiDataPageShoppingCartToJSON(json: any): EdgeApiDataPageShoppingCart {
    return EdgeApiDataPageShoppingCartToJSONTyped(json, false);
}

export function EdgeApiDataPageShoppingCartToJSONTyped(value?: EdgeApiDataPageShoppingCart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'start': value['start'],
        'length': value['length'],
        'hasNextPage': value['hasNextPage'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(ShoppingCartToJSON)),
    };
}

