/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Badges } from './Badges';
import {
    BadgesFromJSON,
    BadgesFromJSONTyped,
    BadgesToJSON,
    BadgesToJSONTyped,
} from './Badges';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';
import type { UserReputation } from './UserReputation';
import {
    UserReputationFromJSON,
    UserReputationFromJSONTyped,
    UserReputationToJSON,
    UserReputationToJSONTyped,
} from './UserReputation';

/**
 * 
 * @export
 * @interface EdgeApiDataManageUserData
 */
export interface EdgeApiDataManageUserData {
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataManageUserData
     */
    name?: string;
    /**
     * 
     * @type {Array<UserReputation>}
     * @memberof EdgeApiDataManageUserData
     */
    reputations?: Array<UserReputation>;
    /**
     * 
     * @type {Badges}
     * @memberof EdgeApiDataManageUserData
     */
    badges?: Badges;
    /**
     * 
     * @type {Array<string>}
     * @memberof EdgeApiDataManageUserData
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataManageUserData
     */
    segment?: EdgeApiDataManageUserDataSegmentEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EdgeApiDataManageUserData
     */
    livePayment?: boolean;
    /**
     * 
     * @type {Reward}
     * @memberof EdgeApiDataManageUserData
     */
    pointsBalance?: Reward;
}


/**
 * @export
 */
export const EdgeApiDataManageUserDataSegmentEnum = {
    REGULAR: 'REGULAR',
    TEST: 'TEST'
} as const;
export type EdgeApiDataManageUserDataSegmentEnum = typeof EdgeApiDataManageUserDataSegmentEnum[keyof typeof EdgeApiDataManageUserDataSegmentEnum];


/**
 * Check if a given object implements the EdgeApiDataManageUserData interface.
 */
export function instanceOfEdgeApiDataManageUserData(value: object): value is EdgeApiDataManageUserData {
    return true;
}

export function EdgeApiDataManageUserDataFromJSON(json: any): EdgeApiDataManageUserData {
    return EdgeApiDataManageUserDataFromJSONTyped(json, false);
}

export function EdgeApiDataManageUserDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EdgeApiDataManageUserData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'reputations': json['reputations'] == null ? undefined : ((json['reputations'] as Array<any>).map(UserReputationFromJSON)),
        'badges': json['badges'] == null ? undefined : BadgesFromJSON(json['badges']),
        'roles': json['roles'] == null ? undefined : json['roles'],
        'segment': json['segment'] == null ? undefined : json['segment'],
        'livePayment': json['livePayment'] == null ? undefined : json['livePayment'],
        'pointsBalance': json['pointsBalance'] == null ? undefined : RewardFromJSON(json['pointsBalance']),
    };
}

export function EdgeApiDataManageUserDataToJSON(json: any): EdgeApiDataManageUserData {
    return EdgeApiDataManageUserDataToJSONTyped(json, false);
}

export function EdgeApiDataManageUserDataToJSONTyped(value?: EdgeApiDataManageUserData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'reputations': value['reputations'] == null ? undefined : ((value['reputations'] as Array<any>).map(UserReputationToJSON)),
        'badges': BadgesToJSON(value['badges']),
        'roles': value['roles'],
        'segment': value['segment'],
        'livePayment': value['livePayment'],
        'pointsBalance': RewardToJSON(value['pointsBalance']),
    };
}

