/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EdgeApiDataPushNotificationCampaignRequestMessage
 */
export interface EdgeApiDataPushNotificationCampaignRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof EdgeApiDataPushNotificationCampaignRequestMessage
     */
    countryCodes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataPushNotificationCampaignRequestMessage
     */
    gender?: string;
    /**
     * 
     * @type {number}
     * @memberof EdgeApiDataPushNotificationCampaignRequestMessage
     */
    minAge?: number;
    /**
     * 
     * @type {number}
     * @memberof EdgeApiDataPushNotificationCampaignRequestMessage
     */
    maxAge?: number;
    /**
     * 
     * @type {string}
     * @memberof EdgeApiDataPushNotificationCampaignRequestMessage
     */
    text?: string;
}

/**
 * Check if a given object implements the EdgeApiDataPushNotificationCampaignRequestMessage interface.
 */
export function instanceOfEdgeApiDataPushNotificationCampaignRequestMessage(value: object): value is EdgeApiDataPushNotificationCampaignRequestMessage {
    return true;
}

export function EdgeApiDataPushNotificationCampaignRequestMessageFromJSON(json: any): EdgeApiDataPushNotificationCampaignRequestMessage {
    return EdgeApiDataPushNotificationCampaignRequestMessageFromJSONTyped(json, false);
}

export function EdgeApiDataPushNotificationCampaignRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EdgeApiDataPushNotificationCampaignRequestMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCodes': json['countryCodes'] == null ? undefined : json['countryCodes'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'minAge': json['minAge'] == null ? undefined : json['minAge'],
        'maxAge': json['maxAge'] == null ? undefined : json['maxAge'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function EdgeApiDataPushNotificationCampaignRequestMessageToJSON(json: any): EdgeApiDataPushNotificationCampaignRequestMessage {
    return EdgeApiDataPushNotificationCampaignRequestMessageToJSONTyped(json, false);
}

export function EdgeApiDataPushNotificationCampaignRequestMessageToJSONTyped(value?: EdgeApiDataPushNotificationCampaignRequestMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'countryCodes': value['countryCodes'],
        'gender': value['gender'],
        'minAge': value['minAge'],
        'maxAge': value['maxAge'],
        'text': value['text'],
    };
}

