/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Rewards } from './Rewards';
import {
    RewardsFromJSON,
    RewardsFromJSONTyped,
    RewardsToJSON,
    RewardsToJSONTyped,
} from './Rewards';

/**
 * 
 * @export
 * @interface EdgeApiDataAccountAmountResp
 */
export interface EdgeApiDataAccountAmountResp {
    /**
     * 
     * @type {Rewards}
     * @memberof EdgeApiDataAccountAmountResp
     */
    available?: Rewards;
    /**
     * 
     * @type {Rewards}
     * @memberof EdgeApiDataAccountAmountResp
     */
    onHold?: Rewards;
}

/**
 * Check if a given object implements the EdgeApiDataAccountAmountResp interface.
 */
export function instanceOfEdgeApiDataAccountAmountResp(value: object): value is EdgeApiDataAccountAmountResp {
    return true;
}

export function EdgeApiDataAccountAmountRespFromJSON(json: any): EdgeApiDataAccountAmountResp {
    return EdgeApiDataAccountAmountRespFromJSONTyped(json, false);
}

export function EdgeApiDataAccountAmountRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): EdgeApiDataAccountAmountResp {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'] == null ? undefined : RewardsFromJSON(json['available']),
        'onHold': json['onHold'] == null ? undefined : RewardsFromJSON(json['onHold']),
    };
}

export function EdgeApiDataAccountAmountRespToJSON(json: any): EdgeApiDataAccountAmountResp {
    return EdgeApiDataAccountAmountRespToJSONTyped(json, false);
}

export function EdgeApiDataAccountAmountRespToJSONTyped(value?: EdgeApiDataAccountAmountResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': RewardsToJSON(value['available']),
        'onHold': RewardsToJSON(value['onHold']),
    };
}

