/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterFilterVal
 */
export interface FilterFilterVal {
    /**
     * 
     * @type {string}
     * @memberof FilterFilterVal
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterFilterVal
     */
    codes?: Array<string>;
}

/**
 * Check if a given object implements the FilterFilterVal interface.
 */
export function instanceOfFilterFilterVal(value: object): value is FilterFilterVal {
    return true;
}

export function FilterFilterValFromJSON(json: any): FilterFilterVal {
    return FilterFilterValFromJSONTyped(json, false);
}

export function FilterFilterValFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterFilterVal {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'codes': json['codes'] == null ? undefined : json['codes'],
    };
}

export function FilterFilterValToJSON(json: any): FilterFilterVal {
    return FilterFilterValToJSONTyped(json, false);
}

export function FilterFilterValToJSONTyped(value?: FilterFilterVal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'codes': value['codes'],
    };
}

