/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeofencesGeoPoint
 */
export interface GeofencesGeoPoint {
    /**
     * 
     * @type {number}
     * @memberof GeofencesGeoPoint
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof GeofencesGeoPoint
     */
    lon?: number;
}

/**
 * Check if a given object implements the GeofencesGeoPoint interface.
 */
export function instanceOfGeofencesGeoPoint(value: object): value is GeofencesGeoPoint {
    return true;
}

export function GeofencesGeoPointFromJSON(json: any): GeofencesGeoPoint {
    return GeofencesGeoPointFromJSONTyped(json, false);
}

export function GeofencesGeoPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeofencesGeoPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
    };
}

export function GeofencesGeoPointToJSON(json: any): GeofencesGeoPoint {
    return GeofencesGeoPointToJSONTyped(json, false);
}

export function GeofencesGeoPointToJSONTyped(value?: GeofencesGeoPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lon': value['lon'],
    };
}

