/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChargeInfo } from './ChargeInfo';
import {
    ChargeInfoFromJSON,
    ChargeInfoFromJSONTyped,
    ChargeInfoToJSON,
    ChargeInfoToJSONTyped,
} from './ChargeInfo';
import type { OrderSummary } from './OrderSummary';
import {
    OrderSummaryFromJSON,
    OrderSummaryFromJSONTyped,
    OrderSummaryToJSON,
    OrderSummaryToJSONTyped,
} from './OrderSummary';

/**
 * 
 * @export
 * @interface InvoiceInfo
 */
export interface InvoiceInfo {
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfo
     */
    coupon?: string;
    /**
     * 
     * @type {OrderSummary}
     * @memberof InvoiceInfo
     */
    summary?: OrderSummary;
    /**
     * 
     * @type {{ [key: string]: ChargeInfo; }}
     * @memberof InvoiceInfo
     */
    cardCharges?: { [key: string]: ChargeInfo; };
    /**
     * 
     * @type {string}
     * @memberof InvoiceInfo
     */
    paymentType?: InvoiceInfoPaymentTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof InvoiceInfo
     */
    livePayment?: boolean;
}


/**
 * @export
 */
export const InvoiceInfoPaymentTypeEnum = {
    NONE: 'NONE',
    WITH_CC: 'WITH_CC',
    AT_DELIVERY: 'AT_DELIVERY',
    UNKNOWN: 'UNKNOWN'
} as const;
export type InvoiceInfoPaymentTypeEnum = typeof InvoiceInfoPaymentTypeEnum[keyof typeof InvoiceInfoPaymentTypeEnum];


/**
 * Check if a given object implements the InvoiceInfo interface.
 */
export function instanceOfInvoiceInfo(value: object): value is InvoiceInfo {
    return true;
}

export function InvoiceInfoFromJSON(json: any): InvoiceInfo {
    return InvoiceInfoFromJSONTyped(json, false);
}

export function InvoiceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'coupon': json['coupon'] == null ? undefined : json['coupon'],
        'summary': json['summary'] == null ? undefined : OrderSummaryFromJSON(json['summary']),
        'cardCharges': json['cardCharges'] == null ? undefined : (mapValues(json['cardCharges'], ChargeInfoFromJSON)),
        'paymentType': json['paymentType'] == null ? undefined : json['paymentType'],
        'livePayment': json['livePayment'] == null ? undefined : json['livePayment'],
    };
}

export function InvoiceInfoToJSON(json: any): InvoiceInfo {
    return InvoiceInfoToJSONTyped(json, false);
}

export function InvoiceInfoToJSONTyped(value?: InvoiceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coupon': value['coupon'],
        'summary': OrderSummaryToJSON(value['summary']),
        'cardCharges': value['cardCharges'] == null ? undefined : (mapValues(value['cardCharges'], ChargeInfoToJSON)),
        'paymentType': value['paymentType'],
        'livePayment': value['livePayment'],
    };
}

