/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventsInfo } from './EventsInfo';
import {
    EventsInfoFromJSON,
    EventsInfoFromJSONTyped,
    EventsInfoToJSON,
    EventsInfoToJSONTyped,
} from './EventsInfo';

/**
 * 
 * @export
 * @interface ISportsApiResultListEventsInfo
 */
export interface ISportsApiResultListEventsInfo {
    /**
     * 
     * @type {Array<EventsInfo>}
     * @memberof ISportsApiResultListEventsInfo
     */
    data?: Array<EventsInfo>;
}

/**
 * Check if a given object implements the ISportsApiResultListEventsInfo interface.
 */
export function instanceOfISportsApiResultListEventsInfo(value: object): value is ISportsApiResultListEventsInfo {
    return true;
}

export function ISportsApiResultListEventsInfoFromJSON(json: any): ISportsApiResultListEventsInfo {
    return ISportsApiResultListEventsInfoFromJSONTyped(json, false);
}

export function ISportsApiResultListEventsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISportsApiResultListEventsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EventsInfoFromJSON)),
    };
}

export function ISportsApiResultListEventsInfoToJSON(json: any): ISportsApiResultListEventsInfo {
    return ISportsApiResultListEventsInfoToJSONTyped(json, false);
}

export function ISportsApiResultListEventsInfoToJSONTyped(value?: ISportsApiResultListEventsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EventsInfoToJSON)),
    };
}

