/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface LogEntry
 */
export interface LogEntry {
    /**
     * 
     * @type {string}
     * @memberof LogEntry
     */
    id?: string;
    /**
     * 
     * @type {User}
     * @memberof LogEntry
     */
    actor?: User;
    /**
     * 
     * @type {string}
     * @memberof LogEntry
     */
    verb?: string;
    /**
     * 
     * @type {string}
     * @memberof LogEntry
     */
    objectType?: string;
    /**
     * 
     * @type {string}
     * @memberof LogEntry
     */
    objectId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogEntry
     */
    extra?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof LogEntry
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof LogEntry
     */
    createdAt?: number;
}

/**
 * Check if a given object implements the LogEntry interface.
 */
export function instanceOfLogEntry(value: object): value is LogEntry {
    return true;
}

export function LogEntryFromJSON(json: any): LogEntry {
    return LogEntryFromJSONTyped(json, false);
}

export function LogEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'actor': json['actor'] == null ? undefined : UserFromJSON(json['actor']),
        'verb': json['verb'] == null ? undefined : json['verb'],
        'objectType': json['objectType'] == null ? undefined : json['objectType'],
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'extra': json['extra'] == null ? undefined : json['extra'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function LogEntryToJSON(json: any): LogEntry {
    return LogEntryToJSONTyped(json, false);
}

export function LogEntryToJSONTyped(value?: LogEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'actor': UserToJSON(value['actor']),
        'verb': value['verb'],
        'objectType': value['objectType'],
        'objectId': value['objectId'],
        'extra': value['extra'],
        'description': value['description'],
        'createdAt': value['createdAt'],
    };
}

