/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderPaymentInfo } from './OrderPaymentInfo';
import {
    OrderPaymentInfoFromJSON,
    OrderPaymentInfoFromJSONTyped,
    OrderPaymentInfoToJSON,
    OrderPaymentInfoToJSONTyped,
} from './OrderPaymentInfo';

/**
 * 
 * @export
 * @interface OrderPaymentInfo2
 */
export interface OrderPaymentInfo2 {
    /**
     * 
     * @type {OrderPaymentInfo}
     * @memberof OrderPaymentInfo2
     */
    newValue?: OrderPaymentInfo;
    /**
     * 
     * @type {OrderPaymentInfo}
     * @memberof OrderPaymentInfo2
     */
    oldValue?: OrderPaymentInfo;
    /**
     * 
     * @type {boolean}
     * @memberof OrderPaymentInfo2
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the OrderPaymentInfo2 interface.
 */
export function instanceOfOrderPaymentInfo2(value: object): value is OrderPaymentInfo2 {
    return true;
}

export function OrderPaymentInfo2FromJSON(json: any): OrderPaymentInfo2 {
    return OrderPaymentInfo2FromJSONTyped(json, false);
}

export function OrderPaymentInfo2FromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPaymentInfo2 {
    if (json == null) {
        return json;
    }
    return {
        
        'newValue': json['newValue'] == null ? undefined : OrderPaymentInfoFromJSON(json['newValue']),
        'oldValue': json['oldValue'] == null ? undefined : OrderPaymentInfoFromJSON(json['oldValue']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function OrderPaymentInfo2ToJSON(json: any): OrderPaymentInfo2 {
    return OrderPaymentInfo2ToJSONTyped(json, false);
}

export function OrderPaymentInfo2ToJSONTyped(value?: OrderPaymentInfo2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newValue': OrderPaymentInfoToJSON(value['newValue']),
        'oldValue': OrderPaymentInfoToJSON(value['oldValue']),
        'empty': value['empty'],
    };
}

