/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListDef } from './ListDef';
import {
    ListDefFromJSON,
    ListDefFromJSONTyped,
    ListDefToJSON,
    ListDefToJSONTyped,
} from './ListDef';

/**
 * 
 * @export
 * @interface PageListDef
 */
export interface PageListDef {
    /**
     * 
     * @type {number}
     * @memberof PageListDef
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PageListDef
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof PageListDef
     */
    length?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageListDef
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {Array<ListDef>}
     * @memberof PageListDef
     */
    list?: Array<ListDef>;
}

/**
 * Check if a given object implements the PageListDef interface.
 */
export function instanceOfPageListDef(value: object): value is PageListDef {
    return true;
}

export function PageListDefFromJSON(json: any): PageListDef {
    return PageListDefFromJSONTyped(json, false);
}

export function PageListDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageListDef {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'start': json['start'] == null ? undefined : json['start'],
        'length': json['length'] == null ? undefined : json['length'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(ListDefFromJSON)),
    };
}

export function PageListDefToJSON(json: any): PageListDef {
    return PageListDefToJSONTyped(json, false);
}

export function PageListDefToJSONTyped(value?: PageListDef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'start': value['start'],
        'length': value['length'],
        'hasNextPage': value['hasNextPage'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(ListDefToJSON)),
    };
}

