/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInvite } from './UserInvite';
import {
    UserInviteFromJSON,
    UserInviteFromJSONTyped,
    UserInviteToJSON,
    UserInviteToJSONTyped,
} from './UserInvite';

/**
 * 
 * @export
 * @interface PageUserInvite
 */
export interface PageUserInvite {
    /**
     * 
     * @type {number}
     * @memberof PageUserInvite
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserInvite
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserInvite
     */
    length?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserInvite
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {Array<UserInvite>}
     * @memberof PageUserInvite
     */
    list?: Array<UserInvite>;
}

/**
 * Check if a given object implements the PageUserInvite interface.
 */
export function instanceOfPageUserInvite(value: object): value is PageUserInvite {
    return true;
}

export function PageUserInviteFromJSON(json: any): PageUserInvite {
    return PageUserInviteFromJSONTyped(json, false);
}

export function PageUserInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageUserInvite {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'start': json['start'] == null ? undefined : json['start'],
        'length': json['length'] == null ? undefined : json['length'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(UserInviteFromJSON)),
    };
}

export function PageUserInviteToJSON(json: any): PageUserInvite {
    return PageUserInviteToJSONTyped(json, false);
}

export function PageUserInviteToJSONTyped(value?: PageUserInvite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'start': value['start'],
        'length': value['length'],
        'hasNextPage': value['hasNextPage'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(UserInviteToJSON)),
    };
}

