/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PosApiDataStrainResp2
 */
export interface PosApiDataStrainResp2 {
    /**
     * 
     * @type {string}
     * @memberof PosApiDataStrainResp2
     */
    strainId?: string;
    /**
     * 
     * @type {string}
     * @memberof PosApiDataStrainResp2
     */
    strainName?: string;
}

/**
 * Check if a given object implements the PosApiDataStrainResp2 interface.
 */
export function instanceOfPosApiDataStrainResp2(value: object): value is PosApiDataStrainResp2 {
    return true;
}

export function PosApiDataStrainResp2FromJSON(json: any): PosApiDataStrainResp2 {
    return PosApiDataStrainResp2FromJSONTyped(json, false);
}

export function PosApiDataStrainResp2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PosApiDataStrainResp2 {
    if (json == null) {
        return json;
    }
    return {
        
        'strainId': json['strainId'] == null ? undefined : json['strainId'],
        'strainName': json['strainName'] == null ? undefined : json['strainName'],
    };
}

export function PosApiDataStrainResp2ToJSON(json: any): PosApiDataStrainResp2 {
    return PosApiDataStrainResp2ToJSONTyped(json, false);
}

export function PosApiDataStrainResp2ToJSONTyped(value?: PosApiDataStrainResp2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strainId': value['strainId'],
        'strainName': value['strainName'],
    };
}

