/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfo } from './PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfo';
import {
    PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfoFromJSON,
    PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfoFromJSONTyped,
    PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfoToJSON,
    PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfoToJSONTyped,
} from './PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfo';

/**
 * 
 * @export
 * @interface PrivateCompanySettingsAnalyticsInfoDataStreamInfo
 */
export interface PrivateCompanySettingsAnalyticsInfoDataStreamInfo {
    /**
     * 
     * @type {string}
     * @memberof PrivateCompanySettingsAnalyticsInfoDataStreamInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateCompanySettingsAnalyticsInfoDataStreamInfo
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateCompanySettingsAnalyticsInfoDataStreamInfo
     */
    type?: string;
    /**
     * 
     * @type {PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfo}
     * @memberof PrivateCompanySettingsAnalyticsInfoDataStreamInfo
     */
    webStreamData?: PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfo;
    /**
     * 
     * @type {number}
     * @memberof PrivateCompanySettingsAnalyticsInfoDataStreamInfo
     */
    createdAt?: number;
    /**
     * 
     * @type {number}
     * @memberof PrivateCompanySettingsAnalyticsInfoDataStreamInfo
     */
    updatedAt?: number;
}

/**
 * Check if a given object implements the PrivateCompanySettingsAnalyticsInfoDataStreamInfo interface.
 */
export function instanceOfPrivateCompanySettingsAnalyticsInfoDataStreamInfo(value: object): value is PrivateCompanySettingsAnalyticsInfoDataStreamInfo {
    return true;
}

export function PrivateCompanySettingsAnalyticsInfoDataStreamInfoFromJSON(json: any): PrivateCompanySettingsAnalyticsInfoDataStreamInfo {
    return PrivateCompanySettingsAnalyticsInfoDataStreamInfoFromJSONTyped(json, false);
}

export function PrivateCompanySettingsAnalyticsInfoDataStreamInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateCompanySettingsAnalyticsInfoDataStreamInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'type': json['type'] == null ? undefined : json['type'],
        'webStreamData': json['webStreamData'] == null ? undefined : PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfoFromJSON(json['webStreamData']),
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function PrivateCompanySettingsAnalyticsInfoDataStreamInfoToJSON(json: any): PrivateCompanySettingsAnalyticsInfoDataStreamInfo {
    return PrivateCompanySettingsAnalyticsInfoDataStreamInfoToJSONTyped(json, false);
}

export function PrivateCompanySettingsAnalyticsInfoDataStreamInfoToJSONTyped(value?: PrivateCompanySettingsAnalyticsInfoDataStreamInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'displayName': value['displayName'],
        'type': value['type'],
        'webStreamData': PrivateCompanySettingsAnalyticsInfoDataStreamInfoWebStreamDataInfoToJSON(value['webStreamData']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

