/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Prices } from './Prices';
import {
    PricesFromJSON,
    PricesFromJSONTyped,
    PricesToJSON,
    PricesToJSONTyped,
} from './Prices';
import type { ChemicalInfo } from './ChemicalInfo';
import {
    ChemicalInfoFromJSON,
    ChemicalInfoFromJSONTyped,
    ChemicalInfoToJSON,
    ChemicalInfoToJSONTyped,
} from './ChemicalInfo';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';
import type { OnlineProductInfo } from './OnlineProductInfo';
import {
    OnlineProductInfoFromJSON,
    OnlineProductInfoFromJSONTyped,
    OnlineProductInfoToJSON,
    OnlineProductInfoToJSONTyped,
} from './OnlineProductInfo';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';
import type { ShippingFee } from './ShippingFee';
import {
    ShippingFeeFromJSON,
    ShippingFeeFromJSONTyped,
    ShippingFeeToJSON,
    ShippingFeeToJSONTyped,
} from './ShippingFee';
import type { Strain } from './Strain';
import {
    StrainFromJSON,
    StrainFromJSONTyped,
    StrainToJSON,
    StrainToJSONTyped,
} from './Strain';

/**
 * 
 * @export
 * @interface ProductSpecificInfo
 */
export interface ProductSpecificInfo {
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    sku?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    shopifyStoreName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    shopifyVariantId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    optionKey1?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    optionKey2?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    optionKey3?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    manufacturer?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSpecificInfo
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    weightUnit?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSpecificInfo
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductSpecificInfo
     */
    maxAllowedQty?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    inventoryPolicy?: string;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    price?: Price;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    originalPrice?: Price;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    resellerPrice?: Price;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    priceType?: string;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    msrp?: Price;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    costPerItem?: Price;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    otdPrice?: Price;
    /**
     * 
     * @type {Prices}
     * @memberof ProductSpecificInfo
     */
    altPrices?: Prices;
    /**
     * 
     * @type {ShippingFee}
     * @memberof ProductSpecificInfo
     */
    extraDeliveryFee?: ShippingFee;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    barcode?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    attachmentIds?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSpecificInfo
     */
    requiresShipping?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSpecificInfo
     */
    taxable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    taxCode?: string;
    /**
     * 
     * @type {OnlineProductInfo}
     * @memberof ProductSpecificInfo
     */
    onlineProductInfo?: OnlineProductInfo;
    /**
     * 
     * @type {number}
     * @memberof ProductSpecificInfo
     */
    sortWeight?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    sortUnit?: string;
    /**
     * 
     * @type {Strain}
     * @memberof ProductSpecificInfo
     */
    strain?: Strain;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    certificateOfAuthenticityUrl?: string;
    /**
     * 
     * @type {{ [key: string]: ChemicalInfo; }}
     * @memberof ProductSpecificInfo
     */
    chemicalCompositions?: { [key: string]: ChemicalInfo; };
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    effectivePrice?: Price;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    primaryAttachmentId?: string;
    /**
     * 
     * @type {Reward}
     * @memberof ProductSpecificInfo
     */
    extraDeliveryFeeReward?: Reward;
    /**
     * 
     * @type {Price}
     * @memberof ProductSpecificInfo
     */
    effectiveOriginalPrice?: Price;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    weightUnitAsEnum?: ProductSpecificInfoWeightUnitAsEnumEnum;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecificInfo
     */
    inventoryPolicyAsEnum?: ProductSpecificInfoInventoryPolicyAsEnumEnum;
}


/**
 * @export
 */
export const ProductSpecificInfoWeightUnitAsEnumEnum = {
    EA: 'EA',
    MG: 'MG',
    G: 'G',
    KG: 'KG',
    LB: 'LB',
    OZ: 'OZ',
    FLWR: 'FLWR',
    FLWR_2: 'FLWR_2',
    FLWR_4: 'FLWR_4'
} as const;
export type ProductSpecificInfoWeightUnitAsEnumEnum = typeof ProductSpecificInfoWeightUnitAsEnumEnum[keyof typeof ProductSpecificInfoWeightUnitAsEnumEnum];

/**
 * @export
 */
export const ProductSpecificInfoInventoryPolicyAsEnumEnum = {
    DENY: 'DENY',
    CONTINUE: 'CONTINUE'
} as const;
export type ProductSpecificInfoInventoryPolicyAsEnumEnum = typeof ProductSpecificInfoInventoryPolicyAsEnumEnum[keyof typeof ProductSpecificInfoInventoryPolicyAsEnumEnum];


/**
 * Check if a given object implements the ProductSpecificInfo interface.
 */
export function instanceOfProductSpecificInfo(value: object): value is ProductSpecificInfo {
    return true;
}

export function ProductSpecificInfoFromJSON(json: any): ProductSpecificInfo {
    return ProductSpecificInfoFromJSONTyped(json, false);
}

export function ProductSpecificInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSpecificInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'sku': json['sku'] == null ? undefined : json['sku'],
        'shopifyStoreName': json['shopifyStoreName'] == null ? undefined : json['shopifyStoreName'],
        'shopifyVariantId': json['shopifyVariantId'] == null ? undefined : json['shopifyVariantId'],
        'name': json['name'] == null ? undefined : json['name'],
        'optionKey1': json['optionKey1'] == null ? undefined : json['optionKey1'],
        'optionKey2': json['optionKey2'] == null ? undefined : json['optionKey2'],
        'optionKey3': json['optionKey3'] == null ? undefined : json['optionKey3'],
        'manufacturer': json['manufacturer'] == null ? undefined : json['manufacturer'],
        'model': json['model'] == null ? undefined : json['model'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'weightUnit': json['weightUnit'] == null ? undefined : json['weightUnit'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'maxAllowedQty': json['maxAllowedQty'] == null ? undefined : json['maxAllowedQty'],
        'inventoryPolicy': json['inventoryPolicy'] == null ? undefined : json['inventoryPolicy'],
        'price': json['price'] == null ? undefined : PriceFromJSON(json['price']),
        'originalPrice': json['originalPrice'] == null ? undefined : PriceFromJSON(json['originalPrice']),
        'resellerPrice': json['resellerPrice'] == null ? undefined : PriceFromJSON(json['resellerPrice']),
        'priceType': json['priceType'] == null ? undefined : json['priceType'],
        'msrp': json['msrp'] == null ? undefined : PriceFromJSON(json['msrp']),
        'costPerItem': json['costPerItem'] == null ? undefined : PriceFromJSON(json['costPerItem']),
        'otdPrice': json['otdPrice'] == null ? undefined : PriceFromJSON(json['otdPrice']),
        'altPrices': json['altPrices'] == null ? undefined : PricesFromJSON(json['altPrices']),
        'extraDeliveryFee': json['extraDeliveryFee'] == null ? undefined : ShippingFeeFromJSON(json['extraDeliveryFee']),
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'attachmentIds': json['attachmentIds'] == null ? undefined : json['attachmentIds'],
        'requiresShipping': json['requiresShipping'] == null ? undefined : json['requiresShipping'],
        'taxable': json['taxable'] == null ? undefined : json['taxable'],
        'taxCode': json['taxCode'] == null ? undefined : json['taxCode'],
        'onlineProductInfo': json['onlineProductInfo'] == null ? undefined : OnlineProductInfoFromJSON(json['onlineProductInfo']),
        'sortWeight': json['sortWeight'] == null ? undefined : json['sortWeight'],
        'sortUnit': json['sortUnit'] == null ? undefined : json['sortUnit'],
        'strain': json['strain'] == null ? undefined : StrainFromJSON(json['strain']),
        'certificateOfAuthenticityUrl': json['certificateOfAuthenticityUrl'] == null ? undefined : json['certificateOfAuthenticityUrl'],
        'chemicalCompositions': json['chemicalCompositions'] == null ? undefined : (mapValues(json['chemicalCompositions'], ChemicalInfoFromJSON)),
        'effectivePrice': json['effectivePrice'] == null ? undefined : PriceFromJSON(json['effectivePrice']),
        'primaryAttachmentId': json['primaryAttachmentId'] == null ? undefined : json['primaryAttachmentId'],
        'extraDeliveryFeeReward': json['extraDeliveryFeeReward'] == null ? undefined : RewardFromJSON(json['extraDeliveryFeeReward']),
        'effectiveOriginalPrice': json['effectiveOriginalPrice'] == null ? undefined : PriceFromJSON(json['effectiveOriginalPrice']),
        'weightUnitAsEnum': json['weightUnitAsEnum'] == null ? undefined : json['weightUnitAsEnum'],
        'inventoryPolicyAsEnum': json['inventoryPolicyAsEnum'] == null ? undefined : json['inventoryPolicyAsEnum'],
    };
}

export function ProductSpecificInfoToJSON(json: any): ProductSpecificInfo {
    return ProductSpecificInfoToJSONTyped(json, false);
}

export function ProductSpecificInfoToJSONTyped(value?: ProductSpecificInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sku': value['sku'],
        'shopifyStoreName': value['shopifyStoreName'],
        'shopifyVariantId': value['shopifyVariantId'],
        'name': value['name'],
        'optionKey1': value['optionKey1'],
        'optionKey2': value['optionKey2'],
        'optionKey3': value['optionKey3'],
        'manufacturer': value['manufacturer'],
        'model': value['model'],
        'weight': value['weight'],
        'weightUnit': value['weightUnit'],
        'quantity': value['quantity'],
        'maxAllowedQty': value['maxAllowedQty'],
        'inventoryPolicy': value['inventoryPolicy'],
        'price': PriceToJSON(value['price']),
        'originalPrice': PriceToJSON(value['originalPrice']),
        'resellerPrice': PriceToJSON(value['resellerPrice']),
        'priceType': value['priceType'],
        'msrp': PriceToJSON(value['msrp']),
        'costPerItem': PriceToJSON(value['costPerItem']),
        'otdPrice': PriceToJSON(value['otdPrice']),
        'altPrices': PricesToJSON(value['altPrices']),
        'extraDeliveryFee': ShippingFeeToJSON(value['extraDeliveryFee']),
        'barcode': value['barcode'],
        'attachmentIds': value['attachmentIds'],
        'requiresShipping': value['requiresShipping'],
        'taxable': value['taxable'],
        'taxCode': value['taxCode'],
        'onlineProductInfo': OnlineProductInfoToJSON(value['onlineProductInfo']),
        'sortWeight': value['sortWeight'],
        'sortUnit': value['sortUnit'],
        'strain': StrainToJSON(value['strain']),
        'certificateOfAuthenticityUrl': value['certificateOfAuthenticityUrl'],
        'chemicalCompositions': value['chemicalCompositions'] == null ? undefined : (mapValues(value['chemicalCompositions'], ChemicalInfoToJSON)),
        'effectivePrice': PriceToJSON(value['effectivePrice']),
        'primaryAttachmentId': value['primaryAttachmentId'],
        'extraDeliveryFeeReward': RewardToJSON(value['extraDeliveryFeeReward']),
        'effectiveOriginalPrice': PriceToJSON(value['effectiveOriginalPrice']),
        'weightUnitAsEnum': value['weightUnitAsEnum'],
        'inventoryPolicyAsEnum': value['inventoryPolicyAsEnum'],
    };
}

