/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Discount } from './Discount';
import {
    DiscountFromJSON,
    DiscountFromJSONTyped,
    DiscountToJSON,
    DiscountToJSONTyped,
} from './Discount';
import type { Bounty } from './Bounty';
import {
    BountyFromJSON,
    BountyFromJSONTyped,
    BountyToJSON,
    BountyToJSONTyped,
} from './Bounty';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';

/**
 * 
 * @export
 * @interface Promotion
 */
export interface Promotion {
    /**
     * 
     * @type {string}
     * @memberof Promotion
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Promotion
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Promotion
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Promotion
     */
    couponCode?: string;
    /**
     * 
     * @type {Discount}
     * @memberof Promotion
     */
    discount?: Discount;
    /**
     * 
     * @type {number}
     * @memberof Promotion
     */
    startsAt?: number;
    /**
     * 
     * @type {number}
     * @memberof Promotion
     */
    endsAt?: number;
    /**
     * 
     * @type {number}
     * @memberof Promotion
     */
    ttl?: number;
    /**
     * 
     * @type {string}
     * @memberof Promotion
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: Bounty; }}
     * @memberof Promotion
     */
    products?: { [key: string]: Bounty; };
    /**
     * 
     * @type {Reward}
     * @memberof Promotion
     */
    deliveryFee?: Reward;
    /**
     * 
     * @type {number}
     * @memberof Promotion
     */
    maxUsageQty?: number;
    /**
     * 
     * @type {number}
     * @memberof Promotion
     */
    maxOverallUsageQty?: number;
}

/**
 * Check if a given object implements the Promotion interface.
 */
export function instanceOfPromotion(value: object): value is Promotion {
    return true;
}

export function PromotionFromJSON(json: any): Promotion {
    return PromotionFromJSONTyped(json, false);
}

export function PromotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Promotion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'state': json['state'] == null ? undefined : json['state'],
        'couponCode': json['couponCode'] == null ? undefined : json['couponCode'],
        'discount': json['discount'] == null ? undefined : DiscountFromJSON(json['discount']),
        'startsAt': json['startsAt'] == null ? undefined : json['startsAt'],
        'endsAt': json['endsAt'] == null ? undefined : json['endsAt'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'description': json['description'] == null ? undefined : json['description'],
        'products': json['products'] == null ? undefined : (mapValues(json['products'], BountyFromJSON)),
        'deliveryFee': json['deliveryFee'] == null ? undefined : RewardFromJSON(json['deliveryFee']),
        'maxUsageQty': json['maxUsageQty'] == null ? undefined : json['maxUsageQty'],
        'maxOverallUsageQty': json['maxOverallUsageQty'] == null ? undefined : json['maxOverallUsageQty'],
    };
}

export function PromotionToJSON(json: any): Promotion {
    return PromotionToJSONTyped(json, false);
}

export function PromotionToJSONTyped(value?: Promotion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'state': value['state'],
        'couponCode': value['couponCode'],
        'discount': DiscountToJSON(value['discount']),
        'startsAt': value['startsAt'],
        'endsAt': value['endsAt'],
        'ttl': value['ttl'],
        'description': value['description'],
        'products': value['products'] == null ? undefined : (mapValues(value['products'], BountyToJSON)),
        'deliveryFee': RewardToJSON(value['deliveryFee']),
        'maxUsageQty': value['maxUsageQty'],
        'maxOverallUsageQty': value['maxOverallUsageQty'],
    };
}

