/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Phone } from './Phone';
import {
    PhoneFromJSON,
    PhoneFromJSONTyped,
    PhoneToJSON,
    PhoneToJSONTyped,
} from './Phone';
import type { Spending } from './Spending';
import {
    SpendingFromJSON,
    SpendingFromJSONTyped,
    SpendingToJSON,
    SpendingToJSONTyped,
} from './Spending';

/**
 * 
 * @export
 * @interface ReservationInfo
 */
export interface ReservationInfo {
    /**
     * 
     * @type {number}
     * @memberof ReservationInfo
     */
    restaurantId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationInfo
     */
    date?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationInfo
     */
    partySize?: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    email?: string;
    /**
     * 
     * @type {Phone}
     * @memberof ReservationInfo
     */
    phone?: Phone;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    reservationAttribute?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    specialRequest?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    restaurantName?: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationInfo
     */
    updatedAt?: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    guestId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    reservationId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationInfo
     */
    confirmationNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInfo
     */
    notes?: string;
    /**
     * 
     * @type {Spending}
     * @memberof ReservationInfo
     */
    spending?: Spending;
    /**
     * 
     * @type {boolean}
     * @memberof ReservationInfo
     */
    validForReservation?: boolean;
}

/**
 * Check if a given object implements the ReservationInfo interface.
 */
export function instanceOfReservationInfo(value: object): value is ReservationInfo {
    return true;
}

export function ReservationInfoFromJSON(json: any): ReservationInfo {
    return ReservationInfoFromJSONTyped(json, false);
}

export function ReservationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'restaurantId': json['restaurantId'] == null ? undefined : json['restaurantId'],
        'date': json['date'] == null ? undefined : json['date'],
        'partySize': json['partySize'] == null ? undefined : json['partySize'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : PhoneFromJSON(json['phone']),
        'reservationAttribute': json['reservationAttribute'] == null ? undefined : json['reservationAttribute'],
        'specialRequest': json['specialRequest'] == null ? undefined : json['specialRequest'],
        'restaurantName': json['restaurantName'] == null ? undefined : json['restaurantName'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'guestId': json['guestId'] == null ? undefined : json['guestId'],
        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'status': json['status'] == null ? undefined : json['status'],
        'confirmationNumber': json['confirmationNumber'] == null ? undefined : json['confirmationNumber'],
        'message': json['message'] == null ? undefined : json['message'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'spending': json['spending'] == null ? undefined : SpendingFromJSON(json['spending']),
        'validForReservation': json['validForReservation'] == null ? undefined : json['validForReservation'],
    };
}

export function ReservationInfoToJSON(json: any): ReservationInfo {
    return ReservationInfoToJSONTyped(json, false);
}

export function ReservationInfoToJSONTyped(value?: ReservationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'restaurantId': value['restaurantId'],
        'date': value['date'],
        'partySize': value['partySize'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'phone': PhoneToJSON(value['phone']),
        'reservationAttribute': value['reservationAttribute'],
        'specialRequest': value['specialRequest'],
        'restaurantName': value['restaurantName'],
        'updatedAt': value['updatedAt'],
        'guestId': value['guestId'],
        'reservationId': value['reservationId'],
        'status': value['status'],
        'confirmationNumber': value['confirmationNumber'],
        'message': value['message'],
        'notes': value['notes'],
        'spending': SpendingToJSON(value['spending']),
        'validForReservation': value['validForReservation'],
    };
}

