/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiBountyDemoFeedGeneratorInput } from './AiBountyDemoFeedGeneratorInput';
import {
    AiBountyDemoFeedGeneratorInputFromJSON,
    AiBountyDemoFeedGeneratorInputFromJSONTyped,
    AiBountyDemoFeedGeneratorInputToJSON,
    AiBountyDemoFeedGeneratorInputToJSONTyped,
} from './AiBountyDemoFeedGeneratorInput';

/**
 * 
 * @export
 * @interface RestControllerAIControllerStartDemoFeedSeedingRequest
 */
export interface RestControllerAIControllerStartDemoFeedSeedingRequest {
    /**
     * 
     * @type {string}
     * @memberof RestControllerAIControllerStartDemoFeedSeedingRequest
     */
    companyId?: string;
    /**
     * 
     * @type {AiBountyDemoFeedGeneratorInput}
     * @memberof RestControllerAIControllerStartDemoFeedSeedingRequest
     */
    input?: AiBountyDemoFeedGeneratorInput;
}

/**
 * Check if a given object implements the RestControllerAIControllerStartDemoFeedSeedingRequest interface.
 */
export function instanceOfRestControllerAIControllerStartDemoFeedSeedingRequest(value: object): value is RestControllerAIControllerStartDemoFeedSeedingRequest {
    return true;
}

export function RestControllerAIControllerStartDemoFeedSeedingRequestFromJSON(json: any): RestControllerAIControllerStartDemoFeedSeedingRequest {
    return RestControllerAIControllerStartDemoFeedSeedingRequestFromJSONTyped(json, false);
}

export function RestControllerAIControllerStartDemoFeedSeedingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestControllerAIControllerStartDemoFeedSeedingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'input': json['input'] == null ? undefined : AiBountyDemoFeedGeneratorInputFromJSON(json['input']),
    };
}

export function RestControllerAIControllerStartDemoFeedSeedingRequestToJSON(json: any): RestControllerAIControllerStartDemoFeedSeedingRequest {
    return RestControllerAIControllerStartDemoFeedSeedingRequestToJSONTyped(json, false);
}

export function RestControllerAIControllerStartDemoFeedSeedingRequestToJSONTyped(value?: RestControllerAIControllerStartDemoFeedSeedingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'input': AiBountyDemoFeedGeneratorInputToJSON(value['input']),
    };
}

