/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SearchField = {
    NONE: 'NONE',
    USER_NAME: 'USER_NAME',
    USER_FIRST_NAME: 'USER_FIRST_NAME',
    USER_LAST_NAME: 'USER_LAST_NAME',
    USER_LATINIZED_NAME: 'USER_LATINIZED_NAME',
    USER_EMAIL: 'USER_EMAIL',
    USER_COUNTRY_CODE: 'USER_COUNTRY_CODE',
    USER_CITY: 'USER_CITY',
    EMPLOYER_NAME: 'EMPLOYER_NAME',
    BOUNTY_TITLE: 'BOUNTY_TITLE',
    BOUNTY_DESCRIPTION: 'BOUNTY_DESCRIPTION',
    BOUNTY_CREATOR_NAME: 'BOUNTY_CREATOR_NAME',
    APPLICANT_POSITION: 'APPLICANT_POSITION',
    REFERRAL_CODE: 'REFERRAL_CODE',
    PIN: 'PIN',
    COUNTRY: 'COUNTRY',
    COMPANY_NAME: 'COMPANY_NAME',
    PHONE: 'PHONE',
    UNKNOWN: 'UNKNOWN'
} as const;
export type SearchField = typeof SearchField[keyof typeof SearchField];


export function instanceOfSearchField(value: any): boolean {
    for (const key in SearchField) {
        if (Object.prototype.hasOwnProperty.call(SearchField, key)) {
            if (SearchField[key as keyof typeof SearchField] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SearchFieldFromJSON(json: any): SearchField {
    return SearchFieldFromJSONTyped(json, false);
}

export function SearchFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchField {
    return json as SearchField;
}

export function SearchFieldToJSON(value?: SearchField | null): any {
    return value as any;
}

export function SearchFieldToJSONTyped(value: any, ignoreDiscriminator: boolean): SearchField {
    return value as SearchField;
}

