/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
 */
export interface ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult {
    /**
     * 
     * @type {string}
     * @memberof ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
     */
    tierBountyId?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
     */
    expectedKeys?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
     */
    grantedKeys?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult
     */
    revokedKeys?: Set<string>;
}

/**
 * Check if a given object implements the ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult interface.
 */
export function instanceOfServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult(value: object): value is ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult {
    return true;
}

export function ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultFromJSON(json: any): ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult {
    return ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultFromJSONTyped(json, false);
}

export function ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscriptionId'] == null ? undefined : json['subscriptionId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'tierBountyId': json['tierBountyId'] == null ? undefined : json['tierBountyId'],
        'expectedKeys': json['expectedKeys'] == null ? undefined : new Set(json['expectedKeys']),
        'grantedKeys': json['grantedKeys'] == null ? undefined : new Set(json['grantedKeys']),
        'revokedKeys': json['revokedKeys'] == null ? undefined : new Set(json['revokedKeys']),
    };
}

export function ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultToJSON(json: any): ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult {
    return ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultToJSONTyped(json, false);
}

export function ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultToJSONTyped(value?: ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionId': value['subscriptionId'],
        'userId': value['userId'],
        'tierBountyId': value['tierBountyId'],
        'expectedKeys': value['expectedKeys'] == null ? undefined : Array.from(value['expectedKeys'] as Set<any>),
        'grantedKeys': value['grantedKeys'] == null ? undefined : Array.from(value['grantedKeys'] as Set<any>),
        'revokedKeys': value['revokedKeys'] == null ? undefined : Array.from(value['revokedKeys'] as Set<any>),
    };
}

