/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionAdminActionAvailability
 */
export interface SubscriptionAdminActionAvailability {
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canRebuildEntitlements?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canReconcileFromStripe?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canReplayWebhook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canCancelImmediately?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canReverseCancellation?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canForceEntitlementSync?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminActionAvailability
     */
    canRefreshStripeLinkage?: boolean;
}

/**
 * Check if a given object implements the SubscriptionAdminActionAvailability interface.
 */
export function instanceOfSubscriptionAdminActionAvailability(value: object): value is SubscriptionAdminActionAvailability {
    return true;
}

export function SubscriptionAdminActionAvailabilityFromJSON(json: any): SubscriptionAdminActionAvailability {
    return SubscriptionAdminActionAvailabilityFromJSONTyped(json, false);
}

export function SubscriptionAdminActionAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionAdminActionAvailability {
    if (json == null) {
        return json;
    }
    return {
        
        'canRebuildEntitlements': json['canRebuildEntitlements'] == null ? undefined : json['canRebuildEntitlements'],
        'canReconcileFromStripe': json['canReconcileFromStripe'] == null ? undefined : json['canReconcileFromStripe'],
        'canReplayWebhook': json['canReplayWebhook'] == null ? undefined : json['canReplayWebhook'],
        'canCancelImmediately': json['canCancelImmediately'] == null ? undefined : json['canCancelImmediately'],
        'canReverseCancellation': json['canReverseCancellation'] == null ? undefined : json['canReverseCancellation'],
        'canForceEntitlementSync': json['canForceEntitlementSync'] == null ? undefined : json['canForceEntitlementSync'],
        'canRefreshStripeLinkage': json['canRefreshStripeLinkage'] == null ? undefined : json['canRefreshStripeLinkage'],
    };
}

export function SubscriptionAdminActionAvailabilityToJSON(json: any): SubscriptionAdminActionAvailability {
    return SubscriptionAdminActionAvailabilityToJSONTyped(json, false);
}

export function SubscriptionAdminActionAvailabilityToJSONTyped(value?: SubscriptionAdminActionAvailability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'canRebuildEntitlements': value['canRebuildEntitlements'],
        'canReconcileFromStripe': value['canReconcileFromStripe'],
        'canReplayWebhook': value['canReplayWebhook'],
        'canCancelImmediately': value['canCancelImmediately'],
        'canReverseCancellation': value['canReverseCancellation'],
        'canForceEntitlementSync': value['canForceEntitlementSync'],
        'canRefreshStripeLinkage': value['canRefreshStripeLinkage'],
    };
}

