/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionAdminSummaryView
 */
export interface SubscriptionAdminSummaryView {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAdminSummaryView
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAdminSummaryView
     */
    subscriptionBountyId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAdminSummaryView
     */
    currentTierBountyId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAdminSummaryView
     */
    state?: SubscriptionAdminSummaryViewStateEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAdminSummaryView
     */
    cadence?: SubscriptionAdminSummaryViewCadenceEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminSummaryView
     */
    entitlementDrift?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminSummaryView
     */
    stripeLinkageDrift?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAdminSummaryView
     */
    catalogMappingDrift?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAdminSummaryView
     */
    healthStatus?: SubscriptionAdminSummaryViewHealthStatusEnum;
    /**
     * 
     * @type {Set<string>}
     * @memberof SubscriptionAdminSummaryView
     */
    driftKinds?: Set<SubscriptionAdminSummaryViewDriftKindsEnum>;
}


/**
 * @export
 */
export const SubscriptionAdminSummaryViewStateEnum = {
    INCOMPLETE: 'INCOMPLETE',
    TRIALING: 'TRIALING',
    ACTIVE: 'ACTIVE',
    PAST_DUE: 'PAST_DUE',
    CANCELED: 'CANCELED',
    EXPIRED: 'EXPIRED',
    UNKNOWN: 'UNKNOWN'
} as const;
export type SubscriptionAdminSummaryViewStateEnum = typeof SubscriptionAdminSummaryViewStateEnum[keyof typeof SubscriptionAdminSummaryViewStateEnum];

/**
 * @export
 */
export const SubscriptionAdminSummaryViewCadenceEnum = {
    MONTHLY: 'MONTHLY',
    YEARLY: 'YEARLY',
    UNKNOWN: 'UNKNOWN'
} as const;
export type SubscriptionAdminSummaryViewCadenceEnum = typeof SubscriptionAdminSummaryViewCadenceEnum[keyof typeof SubscriptionAdminSummaryViewCadenceEnum];

/**
 * @export
 */
export const SubscriptionAdminSummaryViewHealthStatusEnum = {
    HEALTHY: 'HEALTHY',
    WARNING: 'WARNING',
    BROKEN: 'BROKEN'
} as const;
export type SubscriptionAdminSummaryViewHealthStatusEnum = typeof SubscriptionAdminSummaryViewHealthStatusEnum[keyof typeof SubscriptionAdminSummaryViewHealthStatusEnum];

/**
 * @export
 */
export const SubscriptionAdminSummaryViewDriftKindsEnum = {
    MISSING_STRIPE_SUBSCRIPTION_ID: 'MISSING_STRIPE_SUBSCRIPTION_ID',
    MISSING_STRIPE_CUSTOMER_ID: 'MISSING_STRIPE_CUSTOMER_ID',
    UNKNOWN_STRIPE_PRICE_MAPPING: 'UNKNOWN_STRIPE_PRICE_MAPPING',
    TIER_PRICE_MISMATCH: 'TIER_PRICE_MISMATCH',
    TIER_PRODUCT_MISMATCH: 'TIER_PRODUCT_MISMATCH',
    MISSING_ENTITLEMENTS: 'MISSING_ENTITLEMENTS',
    STALE_ENTITLEMENTS: 'STALE_ENTITLEMENTS',
    INVALID_TIER_REFERENCE: 'INVALID_TIER_REFERENCE',
    OUTDATED_LAST_EVENT_MARKER: 'OUTDATED_LAST_EVENT_MARKER'
} as const;
export type SubscriptionAdminSummaryViewDriftKindsEnum = typeof SubscriptionAdminSummaryViewDriftKindsEnum[keyof typeof SubscriptionAdminSummaryViewDriftKindsEnum];


/**
 * Check if a given object implements the SubscriptionAdminSummaryView interface.
 */
export function instanceOfSubscriptionAdminSummaryView(value: object): value is SubscriptionAdminSummaryView {
    return true;
}

export function SubscriptionAdminSummaryViewFromJSON(json: any): SubscriptionAdminSummaryView {
    return SubscriptionAdminSummaryViewFromJSONTyped(json, false);
}

export function SubscriptionAdminSummaryViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionAdminSummaryView {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscriptionId'] == null ? undefined : json['subscriptionId'],
        'subscriptionBountyId': json['subscriptionBountyId'] == null ? undefined : json['subscriptionBountyId'],
        'currentTierBountyId': json['currentTierBountyId'] == null ? undefined : json['currentTierBountyId'],
        'state': json['state'] == null ? undefined : json['state'],
        'cadence': json['cadence'] == null ? undefined : json['cadence'],
        'entitlementDrift': json['entitlementDrift'] == null ? undefined : json['entitlementDrift'],
        'stripeLinkageDrift': json['stripeLinkageDrift'] == null ? undefined : json['stripeLinkageDrift'],
        'catalogMappingDrift': json['catalogMappingDrift'] == null ? undefined : json['catalogMappingDrift'],
        'healthStatus': json['healthStatus'] == null ? undefined : json['healthStatus'],
        'driftKinds': json['driftKinds'] == null ? undefined : new Set(json['driftKinds']),
    };
}

export function SubscriptionAdminSummaryViewToJSON(json: any): SubscriptionAdminSummaryView {
    return SubscriptionAdminSummaryViewToJSONTyped(json, false);
}

export function SubscriptionAdminSummaryViewToJSONTyped(value?: SubscriptionAdminSummaryView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionId': value['subscriptionId'],
        'subscriptionBountyId': value['subscriptionBountyId'],
        'currentTierBountyId': value['currentTierBountyId'],
        'state': value['state'],
        'cadence': value['cadence'],
        'entitlementDrift': value['entitlementDrift'],
        'stripeLinkageDrift': value['stripeLinkageDrift'],
        'catalogMappingDrift': value['catalogMappingDrift'],
        'healthStatus': value['healthStatus'],
        'driftKinds': value['driftKinds'] == null ? undefined : Array.from(value['driftKinds'] as Set<any>),
    };
}

