/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketQrCodeInfo } from './TicketQrCodeInfo';
import {
    TicketQrCodeInfoFromJSON,
    TicketQrCodeInfoFromJSONTyped,
    TicketQrCodeInfoToJSON,
    TicketQrCodeInfoToJSONTyped,
} from './TicketQrCodeInfo';

/**
 * 
 * @export
 * @interface Ticket
 */
export interface Ticket {
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    seatId?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    type?: string;
    /**
     * 
     * @type {TicketQrCodeInfo}
     * @memberof Ticket
     */
    qrCodeInfoJson?: TicketQrCodeInfo;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    typeAsEnum?: TicketTypeAsEnumEnum;
}


/**
 * @export
 */
export const TicketTypeAsEnumEnum = {
    NONE: 'NONE',
    GENERAL: 'GENERAL',
    MULTI_USE: 'MULTI_USE',
    SINGLE_USE: 'SINGLE_USE',
    UNKNOWN: 'UNKNOWN'
} as const;
export type TicketTypeAsEnumEnum = typeof TicketTypeAsEnumEnum[keyof typeof TicketTypeAsEnumEnum];


/**
 * Check if a given object implements the Ticket interface.
 */
export function instanceOfTicket(value: object): value is Ticket {
    return true;
}

export function TicketFromJSON(json: any): Ticket {
    return TicketFromJSONTyped(json, false);
}

export function TicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ticket {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'seatId': json['seatId'] == null ? undefined : json['seatId'],
        'type': json['type'] == null ? undefined : json['type'],
        'qrCodeInfoJson': json['qrCodeInfoJson'] == null ? undefined : TicketQrCodeInfoFromJSON(json['qrCodeInfoJson']),
        'typeAsEnum': json['typeAsEnum'] == null ? undefined : json['typeAsEnum'],
    };
}

export function TicketToJSON(json: any): Ticket {
    return TicketToJSONTyped(json, false);
}

export function TicketToJSONTyped(value?: Ticket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventId': value['eventId'],
        'seatId': value['seatId'],
        'type': value['type'],
        'qrCodeInfoJson': TicketQrCodeInfoToJSON(value['qrCodeInfoJson']),
        'typeAsEnum': value['typeAsEnum'],
    };
}

