/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranslateTextResult
 */
export interface TranslateTextResult {
    /**
     * 
     * @type {string}
     * @memberof TranslateTextResult
     */
    translatedText?: string;
}

/**
 * Check if a given object implements the TranslateTextResult interface.
 */
export function instanceOfTranslateTextResult(value: object): value is TranslateTextResult {
    return true;
}

export function TranslateTextResultFromJSON(json: any): TranslateTextResult {
    return TranslateTextResultFromJSONTyped(json, false);
}

export function TranslateTextResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslateTextResult {
    if (json == null) {
        return json;
    }
    return {
        
        'translatedText': json['translatedText'] == null ? undefined : json['translatedText'],
    };
}

export function TranslateTextResultToJSON(json: any): TranslateTextResult {
    return TranslateTextResultToJSONTyped(json, false);
}

export function TranslateTextResultToJSONTyped(value?: TranslateTextResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translatedText': value['translatedText'],
    };
}

