/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionAdminSummaryView } from './SubscriptionAdminSummaryView';
import {
    SubscriptionAdminSummaryViewFromJSON,
    SubscriptionAdminSummaryViewFromJSONTyped,
    SubscriptionAdminSummaryViewToJSON,
    SubscriptionAdminSummaryViewToJSONTyped,
} from './SubscriptionAdminSummaryView';

/**
 * 
 * @export
 * @interface UserSubscriptionAdminView
 */
export interface UserSubscriptionAdminView {
    /**
     * 
     * @type {string}
     * @memberof UserSubscriptionAdminView
     */
    userId?: string;
    /**
     * 
     * @type {Array<SubscriptionAdminSummaryView>}
     * @memberof UserSubscriptionAdminView
     */
    subscriptions?: Array<SubscriptionAdminSummaryView>;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionAdminView
     */
    totalSubscriptions?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionAdminView
     */
    activeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionAdminView
     */
    trialingCount?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionAdminView
     */
    pastDueCount?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionAdminView
     */
    terminalCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserSubscriptionAdminView
     */
    hasAnyDrift?: boolean;
}

/**
 * Check if a given object implements the UserSubscriptionAdminView interface.
 */
export function instanceOfUserSubscriptionAdminView(value: object): value is UserSubscriptionAdminView {
    return true;
}

export function UserSubscriptionAdminViewFromJSON(json: any): UserSubscriptionAdminView {
    return UserSubscriptionAdminViewFromJSONTyped(json, false);
}

export function UserSubscriptionAdminViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSubscriptionAdminView {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'subscriptions': json['subscriptions'] == null ? undefined : ((json['subscriptions'] as Array<any>).map(SubscriptionAdminSummaryViewFromJSON)),
        'totalSubscriptions': json['totalSubscriptions'] == null ? undefined : json['totalSubscriptions'],
        'activeCount': json['activeCount'] == null ? undefined : json['activeCount'],
        'trialingCount': json['trialingCount'] == null ? undefined : json['trialingCount'],
        'pastDueCount': json['pastDueCount'] == null ? undefined : json['pastDueCount'],
        'terminalCount': json['terminalCount'] == null ? undefined : json['terminalCount'],
        'hasAnyDrift': json['hasAnyDrift'] == null ? undefined : json['hasAnyDrift'],
    };
}

export function UserSubscriptionAdminViewToJSON(json: any): UserSubscriptionAdminView {
    return UserSubscriptionAdminViewToJSONTyped(json, false);
}

export function UserSubscriptionAdminViewToJSONTyped(value?: UserSubscriptionAdminView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'subscriptions': value['subscriptions'] == null ? undefined : ((value['subscriptions'] as Array<any>).map(SubscriptionAdminSummaryViewToJSON)),
        'totalSubscriptions': value['totalSubscriptions'],
        'activeCount': value['activeCount'],
        'trialingCount': value['trialingCount'],
        'pastDueCount': value['pastDueCount'],
        'terminalCount': value['terminalCount'],
        'hasAnyDrift': value['hasAnyDrift'],
    };
}

