/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileSelfOnboardingInfo } from './UserProfileSelfOnboardingInfo';
import {
    UserProfileSelfOnboardingInfoFromJSON,
    UserProfileSelfOnboardingInfoFromJSONTyped,
    UserProfileSelfOnboardingInfoToJSON,
    UserProfileSelfOnboardingInfoToJSONTyped,
} from './UserProfileSelfOnboardingInfo';
import type { UserProfileMedicalInfo } from './UserProfileMedicalInfo';
import {
    UserProfileMedicalInfoFromJSON,
    UserProfileMedicalInfoFromJSONTyped,
    UserProfileMedicalInfoToJSON,
    UserProfileMedicalInfoToJSONTyped,
} from './UserProfileMedicalInfo';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { UserProfileBasicInfo } from './UserProfileBasicInfo';
import {
    UserProfileBasicInfoFromJSON,
    UserProfileBasicInfoFromJSONTyped,
    UserProfileBasicInfoToJSON,
    UserProfileBasicInfoToJSONTyped,
} from './UserProfileBasicInfo';
import type { Badges } from './Badges';
import {
    BadgesFromJSON,
    BadgesFromJSONTyped,
    BadgesToJSON,
    BadgesToJSONTyped,
} from './Badges';
import type { UserProfileDriverLicenseInfo } from './UserProfileDriverLicenseInfo';
import {
    UserProfileDriverLicenseInfoFromJSON,
    UserProfileDriverLicenseInfoFromJSONTyped,
    UserProfileDriverLicenseInfoToJSON,
    UserProfileDriverLicenseInfoToJSONTyped,
} from './UserProfileDriverLicenseInfo';
import type { UserProfileWebsiteInfo } from './UserProfileWebsiteInfo';
import {
    UserProfileWebsiteInfoFromJSON,
    UserProfileWebsiteInfoFromJSONTyped,
    UserProfileWebsiteInfoToJSON,
    UserProfileWebsiteInfoToJSONTyped,
} from './UserProfileWebsiteInfo';
import type { Attachments } from './Attachments';
import {
    AttachmentsFromJSON,
    AttachmentsFromJSONTyped,
    AttachmentsToJSON,
    AttachmentsToJSONTyped,
} from './Attachments';
import type { UserProfileAgeRange } from './UserProfileAgeRange';
import {
    UserProfileAgeRangeFromJSON,
    UserProfileAgeRangeFromJSONTyped,
    UserProfileAgeRangeToJSON,
    UserProfileAgeRangeToJSONTyped,
} from './UserProfileAgeRange';
import type { UserProfileInterestsInfo } from './UserProfileInterestsInfo';
import {
    UserProfileInterestsInfoFromJSON,
    UserProfileInterestsInfoFromJSONTyped,
    UserProfileInterestsInfoToJSON,
    UserProfileInterestsInfoToJSONTyped,
} from './UserProfileInterestsInfo';
import type { UserProfileStats } from './UserProfileStats';
import {
    UserProfileStatsFromJSON,
    UserProfileStatsFromJSONTyped,
    UserProfileStatsToJSON,
    UserProfileStatsToJSONTyped,
} from './UserProfileStats';

/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {User}
     * @memberof UserProfile
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    shortId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    avgStartRating?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    linkedInAccountLink?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    joiningStrategy?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    streamKey?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    visibilityRoles?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    userType?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    coverImageUrl?: string;
    /**
     * 
     * @type {Attachments}
     * @memberof UserProfile
     */
    attachments?: Attachments;
    /**
     * 
     * @type {{ [key: string]: UserProfileWebsiteInfo; }}
     * @memberof UserProfile
     */
    websites?: { [key: string]: UserProfileWebsiteInfo; };
    /**
     * 
     * @type {Badges}
     * @memberof UserProfile
     */
    badges?: Badges;
    /**
     * 
     * @type {UserProfileStats}
     * @memberof UserProfile
     */
    stats?: UserProfileStats;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    createdAt?: number;
    /**
     * 
     * @type {UserProfileBasicInfo}
     * @memberof UserProfile
     */
    basicInfo?: UserProfileBasicInfo;
    /**
     * 
     * @type {UserProfileMedicalInfo}
     * @memberof UserProfile
     */
    medicalInfo?: UserProfileMedicalInfo;
    /**
     * 
     * @type {UserProfileDriverLicenseInfo}
     * @memberof UserProfile
     */
    driverLicenseInfo?: UserProfileDriverLicenseInfo;
    /**
     * 
     * @type {UserProfileInterestsInfo}
     * @memberof UserProfile
     */
    interestsInfo?: UserProfileInterestsInfo;
    /**
     * 
     * @type {UserProfileAgeRange}
     * @memberof UserProfile
     */
    ageRange?: UserProfileAgeRange;
    /**
     * 
     * @type {UserProfileSelfOnboardingInfo}
     * @memberof UserProfile
     */
    selfOnboardingInfo?: UserProfileSelfOnboardingInfo;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    livePaymentMode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    segment?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    entityId?: string;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'shortId': json['shortId'] == null ? undefined : json['shortId'],
        'description': json['description'] == null ? undefined : json['description'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'avgStartRating': json['avgStartRating'] == null ? undefined : json['avgStartRating'],
        'linkedInAccountLink': json['linkedInAccountLink'] == null ? undefined : json['linkedInAccountLink'],
        'joiningStrategy': json['joiningStrategy'] == null ? undefined : json['joiningStrategy'],
        'streamKey': json['streamKey'] == null ? undefined : json['streamKey'],
        'visibilityRoles': json['visibilityRoles'] == null ? undefined : json['visibilityRoles'],
        'userType': json['userType'] == null ? undefined : json['userType'],
        'coverImageUrl': json['coverImageUrl'] == null ? undefined : json['coverImageUrl'],
        'attachments': json['attachments'] == null ? undefined : AttachmentsFromJSON(json['attachments']),
        'websites': json['websites'] == null ? undefined : (mapValues(json['websites'], UserProfileWebsiteInfoFromJSON)),
        'badges': json['badges'] == null ? undefined : BadgesFromJSON(json['badges']),
        'stats': json['stats'] == null ? undefined : UserProfileStatsFromJSON(json['stats']),
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'basicInfo': json['basicInfo'] == null ? undefined : UserProfileBasicInfoFromJSON(json['basicInfo']),
        'medicalInfo': json['medicalInfo'] == null ? undefined : UserProfileMedicalInfoFromJSON(json['medicalInfo']),
        'driverLicenseInfo': json['driverLicenseInfo'] == null ? undefined : UserProfileDriverLicenseInfoFromJSON(json['driverLicenseInfo']),
        'interestsInfo': json['interestsInfo'] == null ? undefined : UserProfileInterestsInfoFromJSON(json['interestsInfo']),
        'ageRange': json['ageRange'] == null ? undefined : UserProfileAgeRangeFromJSON(json['ageRange']),
        'selfOnboardingInfo': json['selfOnboardingInfo'] == null ? undefined : UserProfileSelfOnboardingInfoFromJSON(json['selfOnboardingInfo']),
        'livePaymentMode': json['livePaymentMode'] == null ? undefined : json['livePaymentMode'],
        'segment': json['segment'] == null ? undefined : json['segment'],
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(value?: UserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
        'shortId': value['shortId'],
        'description': value['description'],
        'rating': value['rating'],
        'avgStartRating': value['avgStartRating'],
        'linkedInAccountLink': value['linkedInAccountLink'],
        'joiningStrategy': value['joiningStrategy'],
        'streamKey': value['streamKey'],
        'visibilityRoles': value['visibilityRoles'],
        'userType': value['userType'],
        'coverImageUrl': value['coverImageUrl'],
        'attachments': AttachmentsToJSON(value['attachments']),
        'websites': value['websites'] == null ? undefined : (mapValues(value['websites'], UserProfileWebsiteInfoToJSON)),
        'badges': BadgesToJSON(value['badges']),
        'stats': UserProfileStatsToJSON(value['stats']),
        'createdAt': value['createdAt'],
        'basicInfo': UserProfileBasicInfoToJSON(value['basicInfo']),
        'medicalInfo': UserProfileMedicalInfoToJSON(value['medicalInfo']),
        'driverLicenseInfo': UserProfileDriverLicenseInfoToJSON(value['driverLicenseInfo']),
        'interestsInfo': UserProfileInterestsInfoToJSON(value['interestsInfo']),
        'ageRange': UserProfileAgeRangeToJSON(value['ageRange']),
        'selfOnboardingInfo': UserProfileSelfOnboardingInfoToJSON(value['selfOnboardingInfo']),
        'livePaymentMode': value['livePaymentMode'],
        'segment': value['segment'],
        'entityId': value['entityId'],
    };
}

