//
// AiControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AiControllerAPI {

    /**

     - parameter input: (body)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: StartStickerGenerationResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func generateStickers(input: Input, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> StartStickerGenerationResponse {
        return try await generateStickersWithRequestBuilder(input: input, UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - POST /api/v1/ai/generate/stickers
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter input: (body)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<StartStickerGenerationResponse> 
     */
    open class func generateStickersWithRequestBuilder(input: Input, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<StartStickerGenerationResponse> {
        let localVariablePath = "/api/v1/ai/generate/stickers"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: input)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StartStickerGenerationResponse>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter bountyId: (path)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: StickerCollectionGeneratorStatus
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getGenerateStickersStatus(bountyId: String, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> StickerCollectionGeneratorStatus {
        return try await getGenerateStickersStatusWithRequestBuilder(bountyId: bountyId, UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - GET /api/v1/ai/generate/stickers/{bountyId}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter bountyId: (path)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<StickerCollectionGeneratorStatus> 
     */
    open class func getGenerateStickersStatusWithRequestBuilder(bountyId: String, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<StickerCollectionGeneratorStatus> {
        var localVariablePath = "/api/v1/ai/generate/stickers/{bountyId}"
        let bountyIdPreEscape = "\(APIHelper.mapValueToPathItem(bountyId))"
        let bountyIdPostEscape = bountyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bountyId}", with: bountyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StickerCollectionGeneratorStatus>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: StickerGeneratorMeta
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func meta(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> StickerGeneratorMeta {
        return try await metaWithRequestBuilder(UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - GET /api/v1/ai/generate/stickers/meta
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<StickerGeneratorMeta> 
     */
    open class func metaWithRequestBuilder(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<StickerGeneratorMeta> {
        let localVariablePath = "/api/v1/ai/generate/stickers/meta"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StickerGeneratorMeta>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
