//
// ApiControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ApiControllerAPI {

    /**
     * enum for parameter entityType
     */
    public enum EntityType_deleteApiV1EntitiesByEntityTypeByEntityIdTags: String, CaseIterable {
        case _none = "NONE"
        case unknown = "UNKNOWN"
        case user = "USER"
        case bounty = "BOUNTY"
        case response = "RESPONSE"
        case comment = "COMMENT"
        case chat = "CHAT"
        case message = "MESSAGE"
        case attachment = "ATTACHMENT"
        case pushNotification = "PUSH_NOTIFICATION"
        case address = "ADDRESS"
        case seat = "SEAT"
        case event = "EVENT"
        case venue = "VENUE"
        case ticket = "TICKET"
        case category = "CATEGORY"
        case subscription = "SUBSCRIPTION"
        case system = "SYSTEM"
    }

    /**

     - parameter entityId: (path)  
     - parameter entityType: (path)  
     - parameter tags: (body)  
     - parameter reason: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteApiV1EntitiesByEntityTypeByEntityIdTags(entityId: String, entityType: EntityType_deleteApiV1EntitiesByEntityTypeByEntityIdTags, tags: Tags, reason: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> [String: String] {
        return try await deleteApiV1EntitiesByEntityTypeByEntityIdTagsWithRequestBuilder(entityId: entityId, entityType: entityType, tags: tags, reason: reason, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - DELETE /api/v1/entities/{entity_type}/{entity_id}/tags
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter entityId: (path)  
     - parameter entityType: (path)  
     - parameter tags: (body)  
     - parameter reason: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func deleteApiV1EntitiesByEntityTypeByEntityIdTagsWithRequestBuilder(entityId: String, entityType: EntityType_deleteApiV1EntitiesByEntityTypeByEntityIdTags, tags: Tags, reason: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<[String: String]> {
        var localVariablePath = "/api/v1/entities/{entity_type}/{entity_id}/tags"
        let entityIdPreEscape = "\(APIHelper.mapValueToPathItem(entityId))"
        let entityIdPostEscape = entityIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{entity_id}", with: entityIdPostEscape, options: .literal, range: nil)
        let entityTypePreEscape = "\(entityType.rawValue)"
        let entityTypePostEscape = entityTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{entity_type}", with: entityTypePostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: tags)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "reason": (wrappedValue: reason?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> [String: String] {
        return try await getApiV1WithRequestBuilder(xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func getApiV1WithRequestBuilder(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<[String: String]> {
        let localVariablePath = "/api/v1/"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter url: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataResolveAttachmentResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1AttachmentsResolve(url: [String]? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataResolveAttachmentResult {
        return try await getApiV1AttachmentsResolveWithRequestBuilder(url: url, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/attachments/resolve
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter url: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataResolveAttachmentResult> 
     */
    open class func getApiV1AttachmentsResolveWithRequestBuilder(url: [String]? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataResolveAttachmentResult> {
        let localVariablePath = "/api/v1/attachments/resolve"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "url": (wrappedValue: url?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataResolveAttachmentResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter origin: (header)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1DownloadSampleProducts(origin: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> [String: String] {
        return try await getApiV1DownloadSampleProductsWithRequestBuilder(origin: origin, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/download/sample/products
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter origin: (header)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func getApiV1DownloadSampleProductsWithRequestBuilder(origin: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<[String: String]> {
        let localVariablePath = "/api/v1/download/sample/products"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Origin": origin?.encodeToJSON(),
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter bountyId: (path)  
     - parameter excludeAnon: (query)  (optional, default to false)
     - parameter includeNextActivities: (query)  (optional, default to false)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataLeaderboardResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1EntitiesByBountyIdLeaderboard(bountyId: String, excludeAnon: Bool? = nil, includeNextActivities: Bool? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataLeaderboardResult {
        return try await getApiV1EntitiesByBountyIdLeaderboardWithRequestBuilder(bountyId: bountyId, excludeAnon: excludeAnon, includeNextActivities: includeNextActivities, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/entities/{bounty_id}/leaderboard
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter bountyId: (path)  
     - parameter excludeAnon: (query)  (optional, default to false)
     - parameter includeNextActivities: (query)  (optional, default to false)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataLeaderboardResult> 
     */
    open class func getApiV1EntitiesByBountyIdLeaderboardWithRequestBuilder(bountyId: String, excludeAnon: Bool? = nil, includeNextActivities: Bool? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataLeaderboardResult> {
        var localVariablePath = "/api/v1/entities/{bounty_id}/leaderboard"
        let bountyIdPreEscape = "\(APIHelper.mapValueToPathItem(bountyId))"
        let bountyIdPostEscape = bountyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bounty_id}", with: bountyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "exclude_anon": (wrappedValue: excludeAnon?.encodeToJSON(), isExplode: true),
            "include_next_activities": (wrappedValue: includeNextActivities?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataLeaderboardResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter entityType
     */
    public enum EntityType_getApiV1EntitiesByEntityTypeByEntityIdTagsHistory: String, CaseIterable {
        case _none = "NONE"
        case unknown = "UNKNOWN"
        case user = "USER"
        case bounty = "BOUNTY"
        case response = "RESPONSE"
        case comment = "COMMENT"
        case chat = "CHAT"
        case message = "MESSAGE"
        case attachment = "ATTACHMENT"
        case pushNotification = "PUSH_NOTIFICATION"
        case address = "ADDRESS"
        case seat = "SEAT"
        case event = "EVENT"
        case venue = "VENUE"
        case ticket = "TICKET"
        case category = "CATEGORY"
        case subscription = "SUBSCRIPTION"
        case system = "SYSTEM"
    }

    /**

     - parameter entityId: (path)  
     - parameter entityType: (path)  
     - parameter start: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 10)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataAuditLogResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1EntitiesByEntityTypeByEntityIdTagsHistory(entityId: String, entityType: EntityType_getApiV1EntitiesByEntityTypeByEntityIdTagsHistory, start: Int? = nil, limit: Int? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataAuditLogResult {
        return try await getApiV1EntitiesByEntityTypeByEntityIdTagsHistoryWithRequestBuilder(entityId: entityId, entityType: entityType, start: start, limit: limit, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/entities/{entity_type}/{entity_id}/tags/history
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter entityId: (path)  
     - parameter entityType: (path)  
     - parameter start: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 10)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataAuditLogResult> 
     */
    open class func getApiV1EntitiesByEntityTypeByEntityIdTagsHistoryWithRequestBuilder(entityId: String, entityType: EntityType_getApiV1EntitiesByEntityTypeByEntityIdTagsHistory, start: Int? = nil, limit: Int? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataAuditLogResult> {
        var localVariablePath = "/api/v1/entities/{entity_type}/{entity_id}/tags/history"
        let entityIdPreEscape = "\(APIHelper.mapValueToPathItem(entityId))"
        let entityIdPostEscape = entityIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{entity_id}", with: entityIdPostEscape, options: .literal, range: nil)
        let entityTypePreEscape = "\(entityType.rawValue)"
        let entityTypePostEscape = entityTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{entity_type}", with: entityTypePostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start": (wrappedValue: start?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataAuditLogResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter listId: (path)  
     - parameter q: (query)  (optional)
     - parameter category: (query)  (optional)
     - parameter tag: (query)  (optional)
     - parameter zone: (query)  (optional)
     - parameter clientId: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataGetFiltersResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1FiltersByListid(listId: String, q: String? = nil, category: [String]? = nil, tag: [String]? = nil, zone: String? = nil, clientId: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataGetFiltersResult {
        return try await getApiV1FiltersByListidWithRequestBuilder(listId: listId, q: q, category: category, tag: tag, zone: zone, clientId: clientId, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/filters/{listId}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter listId: (path)  
     - parameter q: (query)  (optional)
     - parameter category: (query)  (optional)
     - parameter tag: (query)  (optional)
     - parameter zone: (query)  (optional)
     - parameter clientId: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataGetFiltersResult> 
     */
    open class func getApiV1FiltersByListidWithRequestBuilder(listId: String, q: String? = nil, category: [String]? = nil, tag: [String]? = nil, zone: String? = nil, clientId: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataGetFiltersResult> {
        var localVariablePath = "/api/v1/filters/{listId}"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{listId}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category?.encodeToJSON(), isExplode: true),
            "tag": (wrappedValue: tag?.encodeToJSON(), isExplode: true),
            "zone": (wrappedValue: zone?.encodeToJSON(), isExplode: true),
            "clientId": (wrappedValue: clientId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataGetFiltersResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter xClientGeoLocation: (header)  (optional)
     - parameter xClientGeoLatLng: (header)  (optional)
     - parameter xClientRTT: (header)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: GeoIPInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1Geoip(xClientGeoLocation: String? = nil, xClientGeoLatLng: String? = nil, xClientRTT: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> GeoIPInfo {
        return try await getApiV1GeoipWithRequestBuilder(xClientGeoLocation: xClientGeoLocation, xClientGeoLatLng: xClientGeoLatLng, xClientRTT: xClientRTT, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/geoip
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter xClientGeoLocation: (header)  (optional)
     - parameter xClientGeoLatLng: (header)  (optional)
     - parameter xClientRTT: (header)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<GeoIPInfo> 
     */
    open class func getApiV1GeoipWithRequestBuilder(xClientGeoLocation: String? = nil, xClientGeoLatLng: String? = nil, xClientRTT: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<GeoIPInfo> {
        let localVariablePath = "/api/v1/geoip"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Client-Geo-Location": xClientGeoLocation?.encodeToJSON(),
            "X-Client-Geo-LatLng": xClientGeoLatLng?.encodeToJSON(),
            "X-Client-RTT": xClientRTT?.encodeToJSON(),
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GeoIPInfo>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter searchMode
     */
    public enum SearchMode_getApiV1LookupsByLookupType: String, CaseIterable {
        case _default = "DEFAULT"
        case regular = "REGULAR"
        case test = "TEST"
        case all = "ALL"
    }

    /**

     - parameter lookupType: (path)  
     - parameter q: (query)  (optional)
     - parameter limit: (query)  (optional)
     - parameter query: (query)  (optional)
     - parameter searchMode: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataLookupResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1LookupsByLookupType(lookupType: String, q: String? = nil, limit: String? = nil, query: [String]? = nil, searchMode: SearchMode_getApiV1LookupsByLookupType? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataLookupResult {
        return try await getApiV1LookupsByLookupTypeWithRequestBuilder(lookupType: lookupType, q: q, limit: limit, query: query, searchMode: searchMode, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/lookups/{lookup_type}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter lookupType: (path)  
     - parameter q: (query)  (optional)
     - parameter limit: (query)  (optional)
     - parameter query: (query)  (optional)
     - parameter searchMode: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataLookupResult> 
     */
    open class func getApiV1LookupsByLookupTypeWithRequestBuilder(lookupType: String, q: String? = nil, limit: String? = nil, query: [String]? = nil, searchMode: SearchMode_getApiV1LookupsByLookupType? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataLookupResult> {
        var localVariablePath = "/api/v1/lookups/{lookup_type}"
        let lookupTypePreEscape = "\(APIHelper.mapValueToPathItem(lookupType))"
        let lookupTypePostEscape = lookupTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{lookup_type}", with: lookupTypePostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "query": (wrappedValue: query?.encodeToJSON(), isExplode: true),
            "searchMode": (wrappedValue: searchMode?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataLookupResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter groupId: (path)  
     - parameter memberId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataMemberDeletePermissionResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1PermissionByGroupidDeleteMemberByMemberid(groupId: String, memberId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataMemberDeletePermissionResult {
        return try await getApiV1PermissionByGroupidDeleteMemberByMemberidWithRequestBuilder(groupId: groupId, memberId: memberId, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/permission/{groupId}/delete_member/{memberId}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter groupId: (path)  
     - parameter memberId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataMemberDeletePermissionResult> 
     */
    open class func getApiV1PermissionByGroupidDeleteMemberByMemberidWithRequestBuilder(groupId: String, memberId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataMemberDeletePermissionResult> {
        var localVariablePath = "/api/v1/permission/{groupId}/delete_member/{memberId}"
        let groupIdPreEscape = "\(APIHelper.mapValueToPathItem(groupId))"
        let groupIdPostEscape = groupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{groupId}", with: groupIdPostEscape, options: .literal, range: nil)
        let memberIdPreEscape = "\(APIHelper.mapValueToPathItem(memberId))"
        let memberIdPostEscape = memberIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{memberId}", with: memberIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataMemberDeletePermissionResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter entityType: (query)  (optional)
     - parameter bountyType: (query)  (optional)
     - parameter start: (query)  (optional)
     - parameter length: (query)  (optional)
     - parameter ignoreCache: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataListPromotionsResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1Promotions(entityType: [String]? = nil, bountyType: [String]? = nil, start: [String]? = nil, length: [String]? = nil, ignoreCache: Bool? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataListPromotionsResult {
        return try await getApiV1PromotionsWithRequestBuilder(entityType: entityType, bountyType: bountyType, start: start, length: length, ignoreCache: ignoreCache, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/promotions
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter entityType: (query)  (optional)
     - parameter bountyType: (query)  (optional)
     - parameter start: (query)  (optional)
     - parameter length: (query)  (optional)
     - parameter ignoreCache: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataListPromotionsResult> 
     */
    open class func getApiV1PromotionsWithRequestBuilder(entityType: [String]? = nil, bountyType: [String]? = nil, start: [String]? = nil, length: [String]? = nil, ignoreCache: Bool? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataListPromotionsResult> {
        let localVariablePath = "/api/v1/promotions"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "entityType": (wrappedValue: entityType?.encodeToJSON(), isExplode: true),
            "bountyType": (wrappedValue: bountyType?.encodeToJSON(), isExplode: true),
            "start": (wrappedValue: start?.encodeToJSON(), isExplode: true),
            "length": (wrappedValue: length?.encodeToJSON(), isExplode: true),
            "ignoreCache": (wrappedValue: ignoreCache?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataListPromotionsResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter bountyId: (query)  (optional)
     - parameter bountyType: (query)  (optional)
     - parameter chatType: (query)  (optional)
     - parameter version: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataCannedResponseResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1RepliesSmart(bountyId: [String]? = nil, bountyType: [String]? = nil, chatType: [String]? = nil, version: [String]? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataCannedResponseResult {
        return try await getApiV1RepliesSmartWithRequestBuilder(bountyId: bountyId, bountyType: bountyType, chatType: chatType, version: version, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/replies/smart
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter bountyId: (query)  (optional)
     - parameter bountyType: (query)  (optional)
     - parameter chatType: (query)  (optional)
     - parameter version: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataCannedResponseResult> 
     */
    open class func getApiV1RepliesSmartWithRequestBuilder(bountyId: [String]? = nil, bountyType: [String]? = nil, chatType: [String]? = nil, version: [String]? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataCannedResponseResult> {
        let localVariablePath = "/api/v1/replies/smart"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "bountyId": (wrappedValue: bountyId?.encodeToJSON(), isExplode: true),
            "bountyType": (wrappedValue: bountyType?.encodeToJSON(), isExplode: true),
            "chatType": (wrappedValue: chatType?.encodeToJSON(), isExplode: true),
            "version": (wrappedValue: version?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataCannedResponseResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter responseStates
     */
    public enum ResponseStates_getApiV1ResponsesByBountyType: String, CaseIterable {
        case _none = "NONE"
        case draft = "DRAFT"
        case approval = "APPROVAL"
        case pending = "PENDING"
        case active = "ACTIVE"
        case acked = "ACKED"
        case progressing = "PROGRESSING"
        case accepted = "ACCEPTED"
        case refused = "REFUSED"
        case paying = "PAYING"
        case paid = "PAID"
        case retracted = "RETRACTED"
        case rejected = "REJECTED"
        case deleted = "DELETED"
        case unknown = "UNKNOWN"
    }

    /**
     * enum for parameter searchMode
     */
    public enum SearchMode_getApiV1ResponsesByBountyType: String, CaseIterable {
        case _default = "DEFAULT"
        case regular = "REGULAR"
        case test = "TEST"
        case all = "ALL"
    }

    /**

     - parameter bountyType: (path)  
     - parameter userId: (query)  (optional)
     - parameter bountyId: (query)  (optional)
     - parameter searchCriteria: (query)  (optional)
     - parameter country: (query)  (optional)
     - parameter responseStates: (query)  (optional)
     - parameter gender: (query)  (optional)
     - parameter start: (query)  (optional)
     - parameter length: (query)  (optional)
     - parameter order: (query)  (optional)
     - parameter searchMode: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataResponseListResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1ResponsesByBountyType(bountyType: String, userId: String? = nil, bountyId: String? = nil, searchCriteria: String? = nil, country: [String]? = nil, responseStates: [ResponseStates_getApiV1ResponsesByBountyType]? = nil, gender: [String]? = nil, start: Int? = nil, length: Int? = nil, order: String? = nil, searchMode: SearchMode_getApiV1ResponsesByBountyType? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataResponseListResult {
        return try await getApiV1ResponsesByBountyTypeWithRequestBuilder(bountyType: bountyType, userId: userId, bountyId: bountyId, searchCriteria: searchCriteria, country: country, responseStates: responseStates, gender: gender, start: start, length: length, order: order, searchMode: searchMode, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/responses/{bounty_type}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter bountyType: (path)  
     - parameter userId: (query)  (optional)
     - parameter bountyId: (query)  (optional)
     - parameter searchCriteria: (query)  (optional)
     - parameter country: (query)  (optional)
     - parameter responseStates: (query)  (optional)
     - parameter gender: (query)  (optional)
     - parameter start: (query)  (optional)
     - parameter length: (query)  (optional)
     - parameter order: (query)  (optional)
     - parameter searchMode: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataResponseListResult> 
     */
    open class func getApiV1ResponsesByBountyTypeWithRequestBuilder(bountyType: String, userId: String? = nil, bountyId: String? = nil, searchCriteria: String? = nil, country: [String]? = nil, responseStates: [ResponseStates_getApiV1ResponsesByBountyType]? = nil, gender: [String]? = nil, start: Int? = nil, length: Int? = nil, order: String? = nil, searchMode: SearchMode_getApiV1ResponsesByBountyType? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataResponseListResult> {
        var localVariablePath = "/api/v1/responses/{bounty_type}"
        let bountyTypePreEscape = "\(APIHelper.mapValueToPathItem(bountyType))"
        let bountyTypePostEscape = bountyTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bounty_type}", with: bountyTypePostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "userId": (wrappedValue: userId?.encodeToJSON(), isExplode: true),
            "bountyId": (wrappedValue: bountyId?.encodeToJSON(), isExplode: true),
            "searchCriteria": (wrappedValue: searchCriteria?.encodeToJSON(), isExplode: true),
            "country": (wrappedValue: country?.encodeToJSON(), isExplode: true),
            "responseStates": (wrappedValue: responseStates?.encodeToJSON(), isExplode: true),
            "gender": (wrappedValue: gender?.encodeToJSON(), isExplode: true),
            "start": (wrappedValue: start?.encodeToJSON(), isExplode: true),
            "length": (wrappedValue: length?.encodeToJSON(), isExplode: true),
            "order": (wrappedValue: order?.encodeToJSON(), isExplode: true),
            "searchMode": (wrappedValue: searchMode?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataResponseListResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter clientId: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataUserInfoResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1UserInfo(clientId: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataUserInfoResult {
        return try await getApiV1UserInfoWithRequestBuilder(clientId: clientId, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/user/info
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter clientId: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataUserInfoResult> 
     */
    open class func getApiV1UserInfoWithRequestBuilder(clientId: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataUserInfoResult> {
        let localVariablePath = "/api/v1/user/info"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "clientId": (wrappedValue: clientId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataUserInfoResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter userId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataUserPrivateInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1UsersByUserIdPrivate(userId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataUserPrivateInfo {
        return try await getApiV1UsersByUserIdPrivateWithRequestBuilder(userId: userId, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/users/{user_id}/private
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter userId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataUserPrivateInfo> 
     */
    open class func getApiV1UsersByUserIdPrivateWithRequestBuilder(userId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataUserPrivateInfo> {
        var localVariablePath = "/api/v1/users/{user_id}/private"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataUserPrivateInfo>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter userId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataFollowResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1UsersByUseridFollowers(userId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataFollowResult {
        return try await getApiV1UsersByUseridFollowersWithRequestBuilder(userId: userId, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/users/{userId}/followers
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter userId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataFollowResult> 
     */
    open class func getApiV1UsersByUseridFollowersWithRequestBuilder(userId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataFollowResult> {
        var localVariablePath = "/api/v1/users/{userId}/followers"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataFollowResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter userId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataFollowResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getApiV1UsersByUseridFollowing(userId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataFollowResult {
        return try await getApiV1UsersByUseridFollowingWithRequestBuilder(userId: userId, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - GET /api/v1/users/{userId}/following
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter userId: (path)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataFollowResult> 
     */
    open class func getApiV1UsersByUseridFollowingWithRequestBuilder(userId: String, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataFollowResult> {
        var localVariablePath = "/api/v1/users/{userId}/following"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataFollowResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataValidateAddressResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1AddressesValidate(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataValidateAddressResult {
        return try await postApiV1AddressesValidateWithRequestBuilder(xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - POST /api/v1/addresses/validate
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataValidateAddressResult> 
     */
    open class func postApiV1AddressesValidateWithRequestBuilder(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataValidateAddressResult> {
        let localVariablePath = "/api/v1/addresses/validate"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataValidateAddressResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter entityType
     */
    public enum EntityType_postApiV1EntitiesByEntityTypeByEntityIdTags: String, CaseIterable {
        case _none = "NONE"
        case unknown = "UNKNOWN"
        case user = "USER"
        case bounty = "BOUNTY"
        case response = "RESPONSE"
        case comment = "COMMENT"
        case chat = "CHAT"
        case message = "MESSAGE"
        case attachment = "ATTACHMENT"
        case pushNotification = "PUSH_NOTIFICATION"
        case address = "ADDRESS"
        case seat = "SEAT"
        case event = "EVENT"
        case venue = "VENUE"
        case ticket = "TICKET"
        case category = "CATEGORY"
        case subscription = "SUBSCRIPTION"
        case system = "SYSTEM"
    }

    /**

     - parameter entityId: (path)  
     - parameter entityType: (path)  
     - parameter tags: (body)  
     - parameter reason: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1EntitiesByEntityTypeByEntityIdTags(entityId: String, entityType: EntityType_postApiV1EntitiesByEntityTypeByEntityIdTags, tags: Tags, reason: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> [String: String] {
        return try await postApiV1EntitiesByEntityTypeByEntityIdTagsWithRequestBuilder(entityId: entityId, entityType: entityType, tags: tags, reason: reason, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - POST /api/v1/entities/{entity_type}/{entity_id}/tags
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter entityId: (path)  
     - parameter entityType: (path)  
     - parameter tags: (body)  
     - parameter reason: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func postApiV1EntitiesByEntityTypeByEntityIdTagsWithRequestBuilder(entityId: String, entityType: EntityType_postApiV1EntitiesByEntityTypeByEntityIdTags, tags: Tags, reason: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<[String: String]> {
        var localVariablePath = "/api/v1/entities/{entity_type}/{entity_id}/tags"
        let entityIdPreEscape = "\(APIHelper.mapValueToPathItem(entityId))"
        let entityIdPostEscape = entityIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{entity_id}", with: entityIdPostEscape, options: .literal, range: nil)
        let entityTypePreEscape = "\(entityType.rawValue)"
        let entityTypePostEscape = entityTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{entity_type}", with: entityTypePostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: tags)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "reason": (wrappedValue: reason?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter restModelNotification: (body)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1Notify(restModelNotification: RestModelNotification, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> [String: String] {
        return try await postApiV1NotifyWithRequestBuilder(restModelNotification: restModelNotification, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - POST /api/v1/notify
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter restModelNotification: (body)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func postApiV1NotifyWithRequestBuilder(restModelNotification: RestModelNotification, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<[String: String]> {
        let localVariablePath = "/api/v1/notify"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: restModelNotification)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter code: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: EdgeApiDataReferralCodeResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1Referrals(code: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> EdgeApiDataReferralCodeResult {
        return try await postApiV1ReferralsWithRequestBuilder(code: code, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - POST /api/v1/referrals
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter code: (query)  (optional)
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<EdgeApiDataReferralCodeResult> 
     */
    open class func postApiV1ReferralsWithRequestBuilder(code: String? = nil, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<EdgeApiDataReferralCodeResult> {
        let localVariablePath = "/api/v1/referrals"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "code": (wrappedValue: code?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EdgeApiDataReferralCodeResult>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
