//
// AuthControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthControllerAPI {

    /**

     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - parameter coEdgeappServerRestControllerAuthControllerExchangeRequest: (body)  (optional)
     - returns: CoEdgeappServerAuthAuthTokens
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1AuthExchange(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil, coEdgeappServerRestControllerAuthControllerExchangeRequest: CoEdgeappServerRestControllerAuthControllerExchangeRequest? = nil) async throws -> CoEdgeappServerAuthAuthTokens {
        return try await postApiV1AuthExchangeWithRequestBuilder(xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId, coEdgeappServerRestControllerAuthControllerExchangeRequest: coEdgeappServerRestControllerAuthControllerExchangeRequest).execute().body
    }

    /**
     - POST /api/v1/auth/exchange
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - parameter coEdgeappServerRestControllerAuthControllerExchangeRequest: (body)  (optional)
     - returns: RequestBuilder<CoEdgeappServerAuthAuthTokens> 
     */
    open class func postApiV1AuthExchangeWithRequestBuilder(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil, coEdgeappServerRestControllerAuthControllerExchangeRequest: CoEdgeappServerRestControllerAuthControllerExchangeRequest? = nil) -> RequestBuilder<CoEdgeappServerAuthAuthTokens> {
        let localVariablePath = "/api/v1/auth/exchange"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: coEdgeappServerRestControllerAuthControllerExchangeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CoEdgeappServerAuthAuthTokens>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - parameter coEdgeappServerRestControllerAuthControllerLogoutRequest: (body)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1AuthLogout(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil, coEdgeappServerRestControllerAuthControllerLogoutRequest: CoEdgeappServerRestControllerAuthControllerLogoutRequest? = nil) async throws -> [String: String] {
        return try await postApiV1AuthLogoutWithRequestBuilder(xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId, coEdgeappServerRestControllerAuthControllerLogoutRequest: coEdgeappServerRestControllerAuthControllerLogoutRequest).execute().body
    }

    /**
     - POST /api/v1/auth/logout
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - parameter coEdgeappServerRestControllerAuthControllerLogoutRequest: (body)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func postApiV1AuthLogoutWithRequestBuilder(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil, coEdgeappServerRestControllerAuthControllerLogoutRequest: CoEdgeappServerRestControllerAuthControllerLogoutRequest? = nil) -> RequestBuilder<[String: String]> {
        let localVariablePath = "/api/v1/auth/logout"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: coEdgeappServerRestControllerAuthControllerLogoutRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: [String: String]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1AuthLogoutAll(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> [String: String] {
        return try await postApiV1AuthLogoutAllWithRequestBuilder(xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - POST /api/v1/auth/logout-all
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<[String: String]> 
     */
    open class func postApiV1AuthLogoutAllWithRequestBuilder(xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<[String: String]> {
        let localVariablePath = "/api/v1/auth/logout-all"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: String]>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter coEdgeappServerRestControllerAuthControllerRefreshRequest: (body)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: CoEdgeappServerAuthAuthTokens
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postApiV1AuthRefresh(coEdgeappServerRestControllerAuthControllerRefreshRequest: CoEdgeappServerRestControllerAuthControllerRefreshRequest, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) async throws -> CoEdgeappServerAuthAuthTokens {
        return try await postApiV1AuthRefreshWithRequestBuilder(coEdgeappServerRestControllerAuthControllerRefreshRequest: coEdgeappServerRestControllerAuthControllerRefreshRequest, xEdgeAgent: xEdgeAgent, xEdgeState: xEdgeState, xEdgeClientId: xEdgeClientId).execute().body
    }

    /**
     - POST /api/v1/auth/refresh
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter coEdgeappServerRestControllerAuthControllerRefreshRequest: (body)  
     - parameter xEdgeAgent: (header)  (optional)
     - parameter xEdgeState: (header)  (optional)
     - parameter xEdgeClientId: (header)  (optional)
     - returns: RequestBuilder<CoEdgeappServerAuthAuthTokens> 
     */
    open class func postApiV1AuthRefreshWithRequestBuilder(coEdgeappServerRestControllerAuthControllerRefreshRequest: CoEdgeappServerRestControllerAuthControllerRefreshRequest, xEdgeAgent: String? = nil, xEdgeState: String? = nil, xEdgeClientId: String? = nil) -> RequestBuilder<CoEdgeappServerAuthAuthTokens> {
        let localVariablePath = "/api/v1/auth/refresh"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: coEdgeappServerRestControllerAuthControllerRefreshRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": xEdgeAgent?.encodeToJSON(),
            "X-edge-state": xEdgeState?.encodeToJSON(),
            "X-edge-client-id": xEdgeClientId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CoEdgeappServerAuthAuthTokens>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
