//
// StripeControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StripeControllerAPI {

    /**

     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: StripeConfigResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func config(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> StripeConfigResponse {
        return try await configWithRequestBuilder(UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - GET /api/v1/stripe/config
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<StripeConfigResponse> 
     */
    open class func configWithRequestBuilder(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<StripeConfigResponse> {
        let localVariablePath = "/api/v1/stripe/config"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StripeConfigResponse>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter redirectUrl: (query)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: StripeConnectResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func connect(redirectUrl: String? = nil, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> StripeConnectResponse {
        return try await connectWithRequestBuilder(redirectUrl: redirectUrl, UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - GET /api/v1/stripe/connect
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter redirectUrl: (query)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<StripeConnectResponse> 
     */
    open class func connectWithRequestBuilder(redirectUrl: String? = nil, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<StripeConnectResponse> {
        let localVariablePath = "/api/v1/stripe/connect"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "redirectUrl": (wrappedValue: redirectUrl?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StripeConnectResponse>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter paymentId: (path)  
     - parameter body: (body)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: CreatePaymentIntentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createPaymentIntent(paymentId: String, body: AnyCodable, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> CreatePaymentIntentResponse {
        return try await createPaymentIntentWithRequestBuilder(paymentId: paymentId, body: body, UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - POST /api/v1/stripe/payments/{paymentId}/payment-intent
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter paymentId: (path)  
     - parameter body: (body)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<CreatePaymentIntentResponse> 
     */
    open class func createPaymentIntentWithRequestBuilder(paymentId: String, body: AnyCodable, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<CreatePaymentIntentResponse> {
        var localVariablePath = "/api/v1/stripe/payments/{paymentId}/payment-intent"
        let paymentIdPreEscape = "\(APIHelper.mapValueToPathItem(paymentId))"
        let paymentIdPostEscape = paymentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{paymentId}", with: paymentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreatePaymentIntentResponse>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - parameter createSetupIntentRequest: (body)  (optional)
     - returns: CreateSetupIntentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createSetupIntent(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil, createSetupIntentRequest: CreateSetupIntentRequest? = nil) async throws -> CreateSetupIntentResponse {
        return try await createSetupIntentWithRequestBuilder(UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3, createSetupIntentRequest: createSetupIntentRequest).execute().body
    }

    /**
     - POST /api/v1/stripe/setup-intent
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - parameter createSetupIntentRequest: (body)  (optional)
     - returns: RequestBuilder<CreateSetupIntentResponse> 
     */
    open class func createSetupIntentWithRequestBuilder(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil, createSetupIntentRequest: CreateSetupIntentRequest? = nil) -> RequestBuilder<CreateSetupIntentResponse> {
        let localVariablePath = "/api/v1/stripe/setup-intent"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createSetupIntentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateSetupIntentResponse>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: StripeAccountResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getConnectedAccount(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> StripeAccountResponse {
        return try await getConnectedAccountWithRequestBuilder(UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - GET /api/v1/stripe/account
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<StripeAccountResponse> 
     */
    open class func getConnectedAccountWithRequestBuilder(UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<StripeAccountResponse> {
        let localVariablePath = "/api/v1/stripe/account"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StripeAccountResponse>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter stripeSignature: (header)  
     - parameter body: (body)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func stripeWebhookCallback(stripeSignature: String, body: String, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) async throws -> AnyCodable {
        return try await stripeWebhookCallbackWithRequestBuilder(stripeSignature: stripeSignature, body: body, UNKNOWN_PARAMETER_NAME: UNKNOWN_PARAMETER_NAME, UNKNOWN_PARAMETER_NAME2: UNKNOWN_PARAMETER_NAME2, UNKNOWN_PARAMETER_NAME3: UNKNOWN_PARAMETER_NAME3).execute().body
    }

    /**
     - POST /api/v1/stripe/webhook_callback
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: JWT
     - parameter stripeSignature: (header)  
     - parameter body: (body)  
     - parameter UNKNOWN_PARAMETER_NAME: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME2: (header)  (optional)
     - parameter UNKNOWN_PARAMETER_NAME3: (header)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func stripeWebhookCallbackWithRequestBuilder(stripeSignature: String, body: String, UNKNOWN_PARAMETER_NAME: ? = nil, UNKNOWN_PARAMETER_NAME2: ? = nil, UNKNOWN_PARAMETER_NAME3: ? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/stripe/webhook_callback"
        let localVariableURLString = BelongSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Stripe-Signature": stripeSignature.encodeToJSON(),
            "X-edge-agent": UNKNOWN_PARAMETER_NAME?.encodeToJSON(),
            "X-edge-state": UNKNOWN_PARAMETER_NAME2?.encodeToJSON(),
            "X-edge-client-id": UNKNOWN_PARAMETER_NAME3?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = BelongSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
