/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.MetaData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param state 
 * @param description 
 * @param meta 
 * @param createdAt 
 * @param valid 
 * @param stateAsEnum 
 */


data class AccessKeyDef (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "meta")
    val meta: MetaData? = null,

    @Json(name = "createdAt")
    val createdAt: kotlin.Long? = null,

    @Json(name = "valid")
    val valid: kotlin.Boolean? = null,

    @Json(name = "stateAsEnum")
    val stateAsEnum: AccessKeyDef.StateAsEnum? = null

) {

    /**
     * 
     *
     * Values: NONE,ACTIVE,INACTIVE,UNKNOWN
     */
    @JsonClass(generateAdapter = false)
    enum class StateAsEnum(val value: kotlin.String) {
        @Json(name = "NONE") NONE("NONE"),
        @Json(name = "ACTIVE") ACTIVE("ACTIVE"),
        @Json(name = "INACTIVE") INACTIVE("INACTIVE"),
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN");
    }

}

