/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.VideoCallInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param videoCallInfo 
 */


data class AnswerCallResult (

    @Json(name = "status")
    val status: kotlin.Int? = null,

    @Json(name = "videoCallInfo")
    val videoCallInfo: VideoCallInfo? = null

) {


}

