/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param currency 
 * @param type 
 * @param valid 
 * @param typeAsEnum 
 */


data class BudgetCurrency (

    @Json(name = "amount")
    val amount: kotlin.Double? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "valid")
    val valid: kotlin.Boolean? = null,

    @Json(name = "typeAsEnum")
    val typeAsEnum: BudgetCurrency.TypeAsEnum? = null

) {

    /**
     * 
     *
     * Values: NONE,MONEY,POINT,VOUCHER,BADGE,UNKNOWN
     */
    @JsonClass(generateAdapter = false)
    enum class TypeAsEnum(val value: kotlin.String) {
        @Json(name = "NONE") NONE("NONE"),
        @Json(name = "MONEY") MONEY("MONEY"),
        @Json(name = "POINT") POINT("POINT"),
        @Json(name = "VOUCHER") VOUCHER("VOUCHER"),
        @Json(name = "BADGE") BADGE("BADGE"),
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN");
    }

}

