/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.ChemicalInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param viewMode 
 * @param displayName 
 * @param kind 
 * @param categoryCode 
 * @param categoryPath 
 * @param chemicals 
 */


data class CategoryChemicalInfo (

    @Json(name = "viewMode")
    val viewMode: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "kind")
    val kind: kotlin.String? = null,

    @Json(name = "categoryCode")
    val categoryCode: kotlin.String? = null,

    @Json(name = "categoryPath")
    val categoryPath: kotlin.String? = null,

    @Json(name = "chemicals")
    val chemicals: kotlin.collections.Map<kotlin.String, ChemicalInfo>? = null

) {


}

