/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.CoedgeappservermodelSystemInfoAppInfo
import ai.youkno.edgeserversdk.models.CoedgeappservermodelSystemInfoLegalInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param android 
 * @param ios 
 * @param legal 
 */


data class CoedgeappservermodelBaseSettingsSysInfo (

    @Json(name = "android")
    val android: CoedgeappservermodelSystemInfoAppInfo? = null,

    @Json(name = "ios")
    val ios: CoedgeappservermodelSystemInfoAppInfo? = null,

    @Json(name = "legal")
    val legal: CoedgeappservermodelSystemInfoLegalInfo? = null

) {


}

