/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param patientNumber 
 * @param expirationDate 
 */


data class CoedgeappservermodelUserProfileMedicalInfo (

    @Json(name = "patientNumber")
    val patientNumber: kotlin.String? = null,

    @Json(name = "expirationDate")
    val expirationDate: kotlin.String? = null

) {


}

