/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.CoedgeappservermodelUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param from 
 * @param msg 
 * @param rejectedAt 
 */


data class CoedgeappservermodelBountyRejectSnippet (

    @Json(name = "from")
    val from: CoedgeappservermodelUser? = null,

    @Json(name = "msg")
    val msg: kotlin.String? = null,

    @Json(name = "rejectedAt")
    val rejectedAt: kotlin.Long? = null

) {


}

