/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uomId 
 * @param uomName 
 */


data class CoedgeappservermodelPosApiDataUomResp (

    @Json(name = "uomId")
    val uomId: kotlin.String? = null,

    @Json(name = "uomName")
    val uomName: kotlin.String? = null

) {


}

