/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param accessTokenExpiresInSec 
 * @param refreshToken 
 * @param refreshTokenExpiresInSec 
 * @param tokenType 
 */


data class CoedgeappserverauthAuthTokens (

    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "accessTokenExpiresInSec")
    val accessTokenExpiresInSec: kotlin.Long? = null,

    @Json(name = "refreshToken")
    val refreshToken: kotlin.String? = null,

    @Json(name = "refreshTokenExpiresInSec")
    val refreshTokenExpiresInSec: kotlin.Long? = null,

    @Json(name = "tokenType")
    val tokenType: kotlin.String? = null

) {


}

