/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param description 
 * @param language 
 * @param style 
 * @param palette 
 * @param deterministic 
 * @param seed 
 */


data class CoedgeappserveraiuserUserCoverGeneratorInput (

    @Json(name = "userId")
    val userId: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "language")
    val language: kotlin.String? = null,

    @Json(name = "style")
    val style: CoedgeappserveraiuserUserCoverGeneratorInput.Style? = null,

    @Json(name = "palette")
    val palette: CoedgeappserveraiuserUserCoverGeneratorInput.Palette? = null,

    @Json(name = "deterministic")
    val deterministic: kotlin.Boolean? = null,

    @Json(name = "seed")
    val seed: kotlin.Long? = null

) {

    /**
     * 
     *
     * Values: NONE,RETRO,FUTURISTIC,MINIMALIST,CARTOON,NATURE_INSPIRED,ABSTRACT_SHAPES,NEON_GLOW,VINTAGE_POSTER,PIXEL_ART
     */
    @JsonClass(generateAdapter = false)
    enum class Style(val value: kotlin.String) {
        @Json(name = "NONE") NONE("NONE"),
        @Json(name = "RETRO") RETRO("RETRO"),
        @Json(name = "FUTURISTIC") FUTURISTIC("FUTURISTIC"),
        @Json(name = "MINIMALIST") MINIMALIST("MINIMALIST"),
        @Json(name = "CARTOON") CARTOON("CARTOON"),
        @Json(name = "NATURE_INSPIRED") NATURE_INSPIRED("NATURE_INSPIRED"),
        @Json(name = "ABSTRACT_SHAPES") ABSTRACT_SHAPES("ABSTRACT_SHAPES"),
        @Json(name = "NEON_GLOW") NEON_GLOW("NEON_GLOW"),
        @Json(name = "VINTAGE_POSTER") VINTAGE_POSTER("VINTAGE_POSTER"),
        @Json(name = "PIXEL_ART") PIXEL_ART("PIXEL_ART");
    }
    /**
     * 
     *
     * Values: NONE,BOLD,PASTEL,GRAYSCALE,NEON,EARTHY,RETRO,COOL,WARM,MONOCHROME,METALLIC
     */
    @JsonClass(generateAdapter = false)
    enum class Palette(val value: kotlin.String) {
        @Json(name = "NONE") NONE("NONE"),
        @Json(name = "BOLD") BOLD("BOLD"),
        @Json(name = "PASTEL") PASTEL("PASTEL"),
        @Json(name = "GRAYSCALE") GRAYSCALE("GRAYSCALE"),
        @Json(name = "NEON") NEON("NEON"),
        @Json(name = "EARTHY") EARTHY("EARTHY"),
        @Json(name = "RETRO") RETRO("RETRO"),
        @Json(name = "COOL") COOL("COOL"),
        @Json(name = "WARM") WARM("WARM"),
        @Json(name = "MONOCHROME") MONOCHROME("MONOCHROME"),
        @Json(name = "METALLIC") METALLIC("METALLIC");
    }

}

