/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param grantedByEntityId 
 * @param grantedByEntityType 
 * @param sourceType 
 * @param sourceId 
 * @param oneTimeUse 
 * @param durationFromFirstUseMs 
 * @param firstUsedAt 
 * @param grantedByEntityTypeAsEnum 
 */


data class CoedgeappservermodelAccessKeyMetaData (

    @Json(name = "grantedByEntityId")
    val grantedByEntityId: kotlin.String? = null,

    @Json(name = "grantedByEntityType")
    val grantedByEntityType: kotlin.String? = null,

    @Json(name = "sourceType")
    val sourceType: kotlin.String? = null,

    @Json(name = "sourceId")
    val sourceId: kotlin.String? = null,

    @Json(name = "oneTimeUse")
    val oneTimeUse: kotlin.Boolean? = null,

    @Json(name = "durationFromFirstUseMs")
    val durationFromFirstUseMs: kotlin.Long? = null,

    @Json(name = "firstUsedAt")
    val firstUsedAt: kotlin.Long? = null,

    @Json(name = "grantedByEntityTypeAsEnum")
    val grantedByEntityTypeAsEnum: CoedgeappservermodelAccessKeyMetaData.GrantedByEntityTypeAsEnum? = null

) {

    /**
     * 
     *
     * Values: NONE,UNKNOWN,USER,BOUNTY,RESPONSE,COMMENT,CHAT,MESSAGE,ATTACHMENT,PUSH_NOTIFICATION,ADDRESS,SEAT,EVENT,VENUE,TICKET,CATEGORY,SYSTEM
     */
    @JsonClass(generateAdapter = false)
    enum class GrantedByEntityTypeAsEnum(val value: kotlin.String) {
        @Json(name = "NONE") NONE("NONE"),
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN"),
        @Json(name = "USER") USER("USER"),
        @Json(name = "BOUNTY") BOUNTY("BOUNTY"),
        @Json(name = "RESPONSE") RESPONSE("RESPONSE"),
        @Json(name = "COMMENT") COMMENT("COMMENT"),
        @Json(name = "CHAT") CHAT("CHAT"),
        @Json(name = "MESSAGE") MESSAGE("MESSAGE"),
        @Json(name = "ATTACHMENT") ATTACHMENT("ATTACHMENT"),
        @Json(name = "PUSH_NOTIFICATION") PUSH_NOTIFICATION("PUSH_NOTIFICATION"),
        @Json(name = "ADDRESS") ADDRESS("ADDRESS"),
        @Json(name = "SEAT") SEAT("SEAT"),
        @Json(name = "EVENT") EVENT("EVENT"),
        @Json(name = "VENUE") VENUE("VENUE"),
        @Json(name = "TICKET") TICKET("TICKET"),
        @Json(name = "CATEGORY") CATEGORY("CATEGORY"),
        @Json(name = "SYSTEM") SYSTEM("SYSTEM");
    }

}

