/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param jobId 
 * @param companyId 
 * @param phase 
 * @param progressDoneUnits 
 * @param progressTotalUnits 
 * @param menuBountyId 
 * @param createdProductsCount 
 */


data class CoedgeappserverrestcontrollerAIControllerMenuGeneratorStatus (

    @Json(name = "jobId")
    val jobId: java.util.UUID? = null,

    @Json(name = "companyId")
    val companyId: kotlin.String? = null,

    @Json(name = "phase")
    val phase: CoedgeappserverrestcontrollerAIControllerMenuGeneratorStatus.Phase? = null,

    @Json(name = "progressDoneUnits")
    val progressDoneUnits: kotlin.Int? = null,

    @Json(name = "progressTotalUnits")
    val progressTotalUnits: kotlin.Int? = null,

    @Json(name = "menuBountyId")
    val menuBountyId: kotlin.String? = null,

    @Json(name = "createdProductsCount")
    val createdProductsCount: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: INSTRUCTIONS,FINALIZING
     */
    @JsonClass(generateAdapter = false)
    enum class Phase(val value: kotlin.String) {
        @Json(name = "INSTRUCTIONS") INSTRUCTIONS("INSTRUCTIONS"),
        @Json(name = "FINALIZING") FINALIZING("FINALIZING");
    }

}

