/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.PrivateCompanySettingsAnalyticsInfoDataStreamInfo
import ai.youkno.edgeserversdk.models.PrivateCompanySettingsAnalyticsInfoPropertyInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param properties 
 * @param nextValidPropertyInfo 
 * @param propertyInfo 
 * @param dataStreamInfo 
 */


data class PrivateCompanySettingsAnalyticsInfo (

    @Json(name = "properties")
    val properties: kotlin.collections.List<PrivateCompanySettingsAnalyticsInfoPropertyInfo>? = null,

    @Json(name = "nextValidPropertyInfo")
    val nextValidPropertyInfo: PrivateCompanySettingsAnalyticsInfoPropertyInfo? = null,

    @Json(name = "propertyInfo")
    val propertyInfo: PrivateCompanySettingsAnalyticsInfoPropertyInfo? = null,

    @Json(name = "dataStreamInfo")
    val dataStreamInfo: PrivateCompanySettingsAnalyticsInfoDataStreamInfo? = null

) {


}

