/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models

import ai.youkno.edgeserversdk.models.MarkDoc
import ai.youkno.edgeserversdk.models.MetaInfo
import ai.youkno.edgeserversdk.models.Option
import ai.youkno.edgeserversdk.models.StructuredDescription

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param structuredDescription 
 * @param markDoc 
 * @param meta 
 * @param metaError 
 * @param type 
 * @param choiceType 
 * @param rewardType 
 * @param question 
 * @param timeLimit 
 * @param options 
 */


data class Survey (

    @Json(name = "structuredDescription")
    val structuredDescription: StructuredDescription? = null,

    @Json(name = "markDoc")
    val markDoc: MarkDoc? = null,

    @Json(name = "meta")
    val meta: MetaInfo? = null,

    @Json(name = "metaError")
    val metaError: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "choiceType")
    val choiceType: kotlin.String? = null,

    @Json(name = "rewardType")
    val rewardType: kotlin.String? = null,

    @Json(name = "question")
    val question: kotlin.String? = null,

    @Json(name = "timeLimit")
    val timeLimit: kotlin.Long? = null,

    @Json(name = "options")
    val options: kotlin.collections.List<Option>? = null

) {


}

