/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.youkno.edgeserversdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tenantId 
 * @param endpointCount 
 * @param enabledEndpointCount 
 * @param deliveriesLast24h 
 * @param successesLast24h 
 * @param failuresLast24h 
 * @param deadLettersLast24h 
 * @param currentDlqCount 
 * @param openCircuitCount 
 * @param rateLimitedPendingCount 
 * @param mostRecentDeliveryAt 
 */


data class WebhooksWebhookTenantHealthSummaryDto (

    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    @Json(name = "endpointCount")
    val endpointCount: kotlin.Int? = null,

    @Json(name = "enabledEndpointCount")
    val enabledEndpointCount: kotlin.Int? = null,

    @Json(name = "deliveriesLast24h")
    val deliveriesLast24h: kotlin.Int? = null,

    @Json(name = "successesLast24h")
    val successesLast24h: kotlin.Int? = null,

    @Json(name = "failuresLast24h")
    val failuresLast24h: kotlin.Int? = null,

    @Json(name = "deadLettersLast24h")
    val deadLettersLast24h: kotlin.Int? = null,

    @Json(name = "currentDlqCount")
    val currentDlqCount: kotlin.Int? = null,

    @Json(name = "openCircuitCount")
    val openCircuitCount: kotlin.Int? = null,

    @Json(name = "rateLimitedPendingCount")
    val rateLimitedPendingCount: kotlin.Int? = null,

    @Json(name = "mostRecentDeliveryAt")
    val mostRecentDeliveryAt: java.time.OffsetDateTime? = null

) {


}

