//
// AccessReward.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccessReward: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var duration: Int64?

    public init(id: String? = nil, duration: Int64? = nil) {
        self.id = id
        self.duration = duration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case duration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(duration, forKey: .duration)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AccessReward: Identifiable {}
