//
// AuctionInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuctionInfo: Codable, JSONEncodable, Hashable {

    public enum StatusAsEnum: String, Codable, CaseIterable {
        case _none = "NONE"
        case active = "ACTIVE"
        case closed = "CLOSED"
        case unknown = "UNKNOWN"
    }
    public var status: String?
    public var startingBid: Reward?
    public var maxBid: Reward?
    public var currentBid: CurrentBid?
    public var bidSteps: [String: BidStep]?
    public var statusAsEnum: StatusAsEnum?

    public init(status: String? = nil, startingBid: Reward? = nil, maxBid: Reward? = nil, currentBid: CurrentBid? = nil, bidSteps: [String: BidStep]? = nil, statusAsEnum: StatusAsEnum? = nil) {
        self.status = status
        self.startingBid = startingBid
        self.maxBid = maxBid
        self.currentBid = currentBid
        self.bidSteps = bidSteps
        self.statusAsEnum = statusAsEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case startingBid
        case maxBid
        case currentBid
        case bidSteps
        case statusAsEnum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(startingBid, forKey: .startingBid)
        try container.encodeIfPresent(maxBid, forKey: .maxBid)
        try container.encodeIfPresent(currentBid, forKey: .currentBid)
        try container.encodeIfPresent(bidSteps, forKey: .bidSteps)
        try container.encodeIfPresent(statusAsEnum, forKey: .statusAsEnum)
    }
}

