//
// BountyDistributionArea.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BountyDistributionArea: Codable, JSONEncodable, Hashable {

    public enum TypeAsEnum: String, Codable, CaseIterable {
        case _none = "NONE"
        case global = "GLOBAL"
        case group = "GROUP"
        case surveyChoice = "SURVEY_CHOICE"
        case ssoManager = "SSO_MANAGER"
        case geo = "GEO"
        case unknown = "UNKNOWN"
    }
    public var type: String?
    public var exclude: Bool?
    public var text: String?
    public var code: String?
    public var count: Int?
    public var empty: Bool?
    public var typeAsEnum: TypeAsEnum?
    public var global: Bool?

    public init(type: String? = nil, exclude: Bool? = nil, text: String? = nil, code: String? = nil, count: Int? = nil, empty: Bool? = nil, typeAsEnum: TypeAsEnum? = nil, global: Bool? = nil) {
        self.type = type
        self.exclude = exclude
        self.text = text
        self.code = code
        self.count = count
        self.empty = empty
        self.typeAsEnum = typeAsEnum
        self.global = global
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case exclude
        case text
        case code
        case count
        case empty
        case typeAsEnum
        case global
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(exclude, forKey: .exclude)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(empty, forKey: .empty)
        try container.encodeIfPresent(typeAsEnum, forKey: .typeAsEnum)
        try container.encodeIfPresent(global, forKey: .global)
    }
}

