//
// BountyResponseSnippets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BountyResponseSnippets: Codable, JSONEncodable, Hashable {

    public var paymentsRecv: [String: BountyResponsePaymentRecvSnippet]?
    public var review: BountyResponseReviewSnippet?
    public var reject: BountyResponseRejectSnippet?
    public var paymentReceived: Bool?
    public var firstPaymentRecv: BountyResponsePaymentRecvSnippet?

    public init(paymentsRecv: [String: BountyResponsePaymentRecvSnippet]? = nil, review: BountyResponseReviewSnippet? = nil, reject: BountyResponseRejectSnippet? = nil, paymentReceived: Bool? = nil, firstPaymentRecv: BountyResponsePaymentRecvSnippet? = nil) {
        self.paymentsRecv = paymentsRecv
        self.review = review
        self.reject = reject
        self.paymentReceived = paymentReceived
        self.firstPaymentRecv = firstPaymentRecv
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentsRecv
        case review
        case reject
        case paymentReceived
        case firstPaymentRecv
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(paymentsRecv, forKey: .paymentsRecv)
        try container.encodeIfPresent(review, forKey: .review)
        try container.encodeIfPresent(reject, forKey: .reject)
        try container.encodeIfPresent(paymentReceived, forKey: .paymentReceived)
        try container.encodeIfPresent(firstPaymentRecv, forKey: .firstPaymentRecv)
    }
}

