//
// CoEdgeappServerModelEdgeApiDataOrderResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelEdgeApiDataOrderResponse: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var paymentId: String?
    @available(*, deprecated, message: "This property is deprecated.")
    public var alleavesOrderId: String?
    public var posOrderId: String?
    public var bountyId: String?
    public var bountyShortId: String?
    public var bmbEnv: String?
    public var bmbAuthToken: String?
    public var receiptUrl: String?
    public var hasMoneyToCharge: Bool?

    public init(id: String? = nil, paymentId: String? = nil, alleavesOrderId: String? = nil, posOrderId: String? = nil, bountyId: String? = nil, bountyShortId: String? = nil, bmbEnv: String? = nil, bmbAuthToken: String? = nil, receiptUrl: String? = nil, hasMoneyToCharge: Bool? = nil) {
        self.id = id
        self.paymentId = paymentId
        self.alleavesOrderId = alleavesOrderId
        self.posOrderId = posOrderId
        self.bountyId = bountyId
        self.bountyShortId = bountyShortId
        self.bmbEnv = bmbEnv
        self.bmbAuthToken = bmbAuthToken
        self.receiptUrl = receiptUrl
        self.hasMoneyToCharge = hasMoneyToCharge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case paymentId
        case alleavesOrderId
        case posOrderId
        case bountyId
        case bountyShortId
        case bmbEnv
        case bmbAuthToken
        case receiptUrl
        case hasMoneyToCharge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(paymentId, forKey: .paymentId)
        try container.encodeIfPresent(alleavesOrderId, forKey: .alleavesOrderId)
        try container.encodeIfPresent(posOrderId, forKey: .posOrderId)
        try container.encodeIfPresent(bountyId, forKey: .bountyId)
        try container.encodeIfPresent(bountyShortId, forKey: .bountyShortId)
        try container.encodeIfPresent(bmbEnv, forKey: .bmbEnv)
        try container.encodeIfPresent(bmbAuthToken, forKey: .bmbAuthToken)
        try container.encodeIfPresent(receiptUrl, forKey: .receiptUrl)
        try container.encodeIfPresent(hasMoneyToCharge, forKey: .hasMoneyToCharge)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CoEdgeappServerModelEdgeApiDataOrderResponse: Identifiable {}
