//
// CoEdgeappServerModelBaseSettingsPaymentOptionsPaymentOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelBaseSettingsPaymentOptionsPaymentOption: Codable, JSONEncodable, Hashable {

    public enum PaymentTypeAsEnum: String, Codable, CaseIterable {
        case _none = "NONE"
        case withCc = "WITH_CC"
        case atDelivery = "AT_DELIVERY"
        case unknown = "UNKNOWN"
    }
    public var type: String?
    public var order: Int?
    public var requirePhoneNumber: Bool?
    public var paymentTypeAsEnum: PaymentTypeAsEnum?

    public init(type: String? = nil, order: Int? = nil, requirePhoneNumber: Bool? = nil, paymentTypeAsEnum: PaymentTypeAsEnum? = nil) {
        self.type = type
        self.order = order
        self.requirePhoneNumber = requirePhoneNumber
        self.paymentTypeAsEnum = paymentTypeAsEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case order
        case requirePhoneNumber
        case paymentTypeAsEnum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(requirePhoneNumber, forKey: .requirePhoneNumber)
        try container.encodeIfPresent(paymentTypeAsEnum, forKey: .paymentTypeAsEnum)
    }
}

