//
// CoEdgeappServerModelShoppingCartRedemptionInfoExchangeCurrency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelShoppingCartRedemptionInfoExchangeCurrency: Codable, JSONEncodable, Hashable {

    public var redemptionAmount: Int64?
    public var redemptionCurrency: String?
    public var exchangeRate: Double?
    public var exchangeToCurrency: String?
    public var exchangedReward: CoEdgeappServerModelReward?
    public var valid: Bool?
    public var redemptionReward: CoEdgeappServerModelReward?

    public init(redemptionAmount: Int64? = nil, redemptionCurrency: String? = nil, exchangeRate: Double? = nil, exchangeToCurrency: String? = nil, exchangedReward: CoEdgeappServerModelReward? = nil, valid: Bool? = nil, redemptionReward: CoEdgeappServerModelReward? = nil) {
        self.redemptionAmount = redemptionAmount
        self.redemptionCurrency = redemptionCurrency
        self.exchangeRate = exchangeRate
        self.exchangeToCurrency = exchangeToCurrency
        self.exchangedReward = exchangedReward
        self.valid = valid
        self.redemptionReward = redemptionReward
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redemptionAmount
        case redemptionCurrency
        case exchangeRate
        case exchangeToCurrency
        case exchangedReward
        case valid
        case redemptionReward
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(redemptionAmount, forKey: .redemptionAmount)
        try container.encodeIfPresent(redemptionCurrency, forKey: .redemptionCurrency)
        try container.encodeIfPresent(exchangeRate, forKey: .exchangeRate)
        try container.encodeIfPresent(exchangeToCurrency, forKey: .exchangeToCurrency)
        try container.encodeIfPresent(exchangedReward, forKey: .exchangedReward)
        try container.encodeIfPresent(valid, forKey: .valid)
        try container.encodeIfPresent(redemptionReward, forKey: .redemptionReward)
    }
}

