//
// CoEdgeappServerRestControllerAIControllerStartCategoryTreeGenerationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerRestControllerAIControllerStartCategoryTreeGenerationRequest: Codable, JSONEncodable, Hashable {

    public var companyId: String?
    public var input: CoEdgeappServerAiCategoryCategoryGeneratorInput?

    public init(companyId: String? = nil, input: CoEdgeappServerAiCategoryCategoryGeneratorInput? = nil) {
        self.companyId = companyId
        self.input = input
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case companyId
        case input
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(companyId, forKey: .companyId)
        try container.encodeIfPresent(input, forKey: .input)
    }
}

