//
// CoEdgeappServerModelEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelEvent: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var description: String?
    public var venueId: String?
    public var startsAt: Int64?
    public var endsAt: Int64?
    public var capacity: Int?

    public init(id: String? = nil, name: String? = nil, description: String? = nil, venueId: String? = nil, startsAt: Int64? = nil, endsAt: Int64? = nil, capacity: Int? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.venueId = venueId
        self.startsAt = startsAt
        self.endsAt = endsAt
        self.capacity = capacity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case venueId
        case startsAt
        case endsAt
        case capacity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(venueId, forKey: .venueId)
        try container.encodeIfPresent(startsAt, forKey: .startsAt)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encodeIfPresent(capacity, forKey: .capacity)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CoEdgeappServerModelEvent: Identifiable {}
