//
// CoEdgeappServerModelShoppingCartOrderSummaryTaxInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelShoppingCartOrderSummaryTaxInfo: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var scope: String?
    public var use: String?
    public var type: String?
    public var amount: CoEdgeappServerModelMoney?

    public init(name: String? = nil, scope: String? = nil, use: String? = nil, type: String? = nil, amount: CoEdgeappServerModelMoney? = nil) {
        self.name = name
        self.scope = scope
        self.use = use
        self.type = type
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case scope
        case use
        case type
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(use, forKey: .use)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

