//
// CoEdgeappServerModelEdgeApiDataPageCoEdgeappServerModelBaseSettingsReputationDef.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelEdgeApiDataPageCoEdgeappServerModelBaseSettingsReputationDef: Codable, JSONEncodable, Hashable {

    public var totalCount: Int?
    public var start: Int?
    public var length: Int?
    public var hasNextPage: Bool?
    public var list: [CoEdgeappServerModelBaseSettingsReputationDef]?

    public init(totalCount: Int? = nil, start: Int? = nil, length: Int? = nil, hasNextPage: Bool? = nil, list: [CoEdgeappServerModelBaseSettingsReputationDef]? = nil) {
        self.totalCount = totalCount
        self.start = start
        self.length = length
        self.hasNextPage = hasNextPage
        self.list = list
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount
        case start
        case length
        case hasNextPage
        case list
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(start, forKey: .start)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(hasNextPage, forKey: .hasNextPage)
        try container.encodeIfPresent(list, forKey: .list)
    }
}

