//
// CoEdgeappServerModelShoppingCartBalanceCategoryInfoPeriodInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelShoppingCartBalanceCategoryInfoPeriodInfo: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var startDate: String?
    public var endDate: String?

    public init(type: String? = nil, startDate: String? = nil, endDate: String? = nil) {
        self.type = type
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case startDate
        case endDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
    }
}

