//
// CoEdgeappServerModelBaseSettingsEmailSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoEdgeappServerModelBaseSettingsEmailSettings: Codable, JSONEncodable, Hashable {

    public enum SendStatus: String, Codable, CaseIterable {
        case disabled = "DISABLED"
        case enabled = "ENABLED"
        case _none = "NONE"
    }
    public var sendStatus: SendStatus?

    public init(sendStatus: SendStatus? = nil) {
        self.sendStatus = sendStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sendStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sendStatus, forKey: .sendStatus)
    }
}

