//
// CompanyInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompanyInfo: Codable, JSONEncodable, Hashable {

    public var pin: String?
    public var companyId: String?
    public var name: String?
    public var orgType: String?
    public var countryCode: String?
    public var currency: String?
    public var timezone: String?
    public var fee: Double?
    public var feeType: String?
    public var contractType: String?
    public var createdBy: String?
    public var createdAt: Int64?

    public init(pin: String? = nil, companyId: String? = nil, name: String? = nil, orgType: String? = nil, countryCode: String? = nil, currency: String? = nil, timezone: String? = nil, fee: Double? = nil, feeType: String? = nil, contractType: String? = nil, createdBy: String? = nil, createdAt: Int64? = nil) {
        self.pin = pin
        self.companyId = companyId
        self.name = name
        self.orgType = orgType
        self.countryCode = countryCode
        self.currency = currency
        self.timezone = timezone
        self.fee = fee
        self.feeType = feeType
        self.contractType = contractType
        self.createdBy = createdBy
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pin
        case companyId
        case name
        case orgType
        case countryCode
        case currency
        case timezone
        case fee
        case feeType
        case contractType
        case createdBy
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pin, forKey: .pin)
        try container.encodeIfPresent(companyId, forKey: .companyId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(orgType, forKey: .orgType)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(fee, forKey: .fee)
        try container.encodeIfPresent(feeType, forKey: .feeType)
        try container.encodeIfPresent(contractType, forKey: .contractType)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

