//
// EdgeApiDataValidateAddressResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EdgeApiDataValidateAddressResult: Codable, JSONEncodable, Hashable {

    public var status: Int?
    public var errors: [EdgeApiDataValidateAddressResultError]?
    public var address: MailingAddress?

    public init(status: Int? = nil, errors: [EdgeApiDataValidateAddressResultError]? = nil, address: MailingAddress? = nil) {
        self.status = status
        self.errors = errors
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case errors
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(address, forKey: .address)
    }
}

