//
// LikeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LikeRequest: Codable, JSONEncodable, Hashable {

    public var like: Bool?

    public init(like: Bool? = nil) {
        self.like = like
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case like
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(like, forKey: .like)
    }
}

