//
// PointCurrency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PointCurrency: Codable, JSONEncodable, Hashable {

    public var meta: CurrencyMeta?

    public init(meta: CurrencyMeta? = nil) {
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

