//
// Rewards.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Rewards: Codable, JSONEncodable, Hashable {

    public var monies: [String: Money]?
    public var points: [String: Points]?
    public var accessKeys: [String: AccessReward]?

    public init(monies: [String: Money]? = nil, points: [String: Points]? = nil, accessKeys: [String: AccessReward]? = nil) {
        self.monies = monies
        self.points = points
        self.accessKeys = accessKeys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case monies
        case points
        case accessKeys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(monies, forKey: .monies)
        try container.encodeIfPresent(points, forKey: .points)
        try container.encodeIfPresent(accessKeys, forKey: .accessKeys)
    }
}

