//
// SubscriptionTierOptionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionTierOptionView: Codable, JSONEncodable, Hashable {

    public enum Relationship: String, Codable, CaseIterable {
        case current = "CURRENT"
        case upgrade = "UPGRADE"
        case downgrade = "DOWNGRADE"
        case lateral = "LATERAL"
        case unavailable = "UNAVAILABLE"
    }
    public var tier: SubscriptionTierView?
    public var currentTier: Bool?
    public var selectable: Bool?
    public var relationship: Relationship?

    public init(tier: SubscriptionTierView? = nil, currentTier: Bool? = nil, selectable: Bool? = nil, relationship: Relationship? = nil) {
        self.tier = tier
        self.currentTier = currentTier
        self.selectable = selectable
        self.relationship = relationship
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tier
        case currentTier
        case selectable
        case relationship
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tier, forKey: .tier)
        try container.encodeIfPresent(currentTier, forKey: .currentTier)
        try container.encodeIfPresent(selectable, forKey: .selectable)
        try container.encodeIfPresent(relationship, forKey: .relationship)
    }
}

