//
// UserDataAccessKeyChain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserDataAccessKeyChain: Codable, JSONEncodable, Hashable {

    public var accessKeys: [String: AccessKey]?

    public init(accessKeys: [String: AccessKey]? = nil) {
        self.accessKeys = accessKeys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessKeys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessKeys, forKey: .accessKeys)
    }
}

