//
// VisibilityMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VisibilityMode: Codable, JSONEncodable, Hashable {

    public enum VisibilityTypeAsEnum: String, Codable, CaseIterable {
        case _default = "DEFAULT"
        case visible = "VISIBLE"
        case _private = "PRIVATE"
    }
    public var forced: Bool?
    public var visibilityType: String?
    public var visibilityTypeAsEnum: VisibilityTypeAsEnum?
    public var enforced: Bool?
    public var complete: Bool?

    public init(forced: Bool? = nil, visibilityType: String? = nil, visibilityTypeAsEnum: VisibilityTypeAsEnum? = nil, enforced: Bool? = nil, complete: Bool? = nil) {
        self.forced = forced
        self.visibilityType = visibilityType
        self.visibilityTypeAsEnum = visibilityTypeAsEnum
        self.enforced = enforced
        self.complete = complete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case forced
        case visibilityType
        case visibilityTypeAsEnum
        case enforced
        case complete
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(forced, forKey: .forced)
        try container.encodeIfPresent(visibilityType, forKey: .visibilityType)
        try container.encodeIfPresent(visibilityTypeAsEnum, forKey: .visibilityTypeAsEnum)
        try container.encodeIfPresent(enforced, forKey: .enforced)
        try container.encodeIfPresent(complete, forKey: .complete)
    }
}

