/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Input,
  StartStickerGenerationResponse,
  StickerCollectionGeneratorStatus,
  StickerGeneratorMeta,
} from '../models/index';
import {
    InputFromJSON,
    InputToJSON,
    StartStickerGenerationResponseFromJSON,
    StartStickerGenerationResponseToJSON,
    StickerCollectionGeneratorStatusFromJSON,
    StickerCollectionGeneratorStatusToJSON,
    StickerGeneratorMetaFromJSON,
    StickerGeneratorMetaToJSON,
} from '../models/index';

export interface GenerateStickersRequest {
    input: Input;
    UNKNOWN_PARAMETER_NAME?: ;
    UNKNOWN_PARAMETER_NAME2?: ;
    UNKNOWN_PARAMETER_NAME3?: ;
}

export interface GetGenerateStickersStatusRequest {
    bountyId: string;
    UNKNOWN_PARAMETER_NAME?: ;
    UNKNOWN_PARAMETER_NAME2?: ;
    UNKNOWN_PARAMETER_NAME3?: ;
}

export interface MetaRequest {
    UNKNOWN_PARAMETER_NAME?: ;
    UNKNOWN_PARAMETER_NAME2?: ;
    UNKNOWN_PARAMETER_NAME3?: ;
}

/**
 * AiControllerApi - interface
 * 
 * @export
 * @interface AiControllerApiInterface
 */
export interface AiControllerApiInterface {
    /**
     * 
     * @param {Input} input 
     * @param {} [UNKNOWN_PARAMETER_NAME] 
     * @param {} [UNKNOWN_PARAMETER_NAME2] 
     * @param {} [UNKNOWN_PARAMETER_NAME3] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiControllerApiInterface
     */
    generateStickersRaw(requestParameters: GenerateStickersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartStickerGenerationResponse>>;

    /**
     */
    generateStickers(requestParameters: GenerateStickersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartStickerGenerationResponse>;

    /**
     * 
     * @param {string} bountyId 
     * @param {} [UNKNOWN_PARAMETER_NAME] 
     * @param {} [UNKNOWN_PARAMETER_NAME2] 
     * @param {} [UNKNOWN_PARAMETER_NAME3] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiControllerApiInterface
     */
    getGenerateStickersStatusRaw(requestParameters: GetGenerateStickersStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StickerCollectionGeneratorStatus>>;

    /**
     */
    getGenerateStickersStatus(requestParameters: GetGenerateStickersStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StickerCollectionGeneratorStatus>;

    /**
     * 
     * @param {} [UNKNOWN_PARAMETER_NAME] 
     * @param {} [UNKNOWN_PARAMETER_NAME2] 
     * @param {} [UNKNOWN_PARAMETER_NAME3] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiControllerApiInterface
     */
    metaRaw(requestParameters: MetaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StickerGeneratorMeta>>;

    /**
     */
    meta(requestParameters: MetaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StickerGeneratorMeta>;

}

/**
 * 
 */
export class AiControllerApi extends runtime.BaseAPI implements AiControllerApiInterface {

    /**
     */
    async generateStickersRaw(requestParameters: GenerateStickersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartStickerGenerationResponse>> {
        if (requestParameters['input'] == null) {
            throw new runtime.RequiredError(
                'input',
                'Required parameter "input" was null or undefined when calling generateStickers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['UNKNOWN_PARAMETER_NAME'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['UNKNOWN_PARAMETER_NAME']);
        }

        if (requestParameters['UNKNOWN_PARAMETER_NAME2'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['UNKNOWN_PARAMETER_NAME2']);
        }

        if (requestParameters['UNKNOWN_PARAMETER_NAME3'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['UNKNOWN_PARAMETER_NAME3']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/ai/generate/stickers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InputToJSON(requestParameters['input']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartStickerGenerationResponseFromJSON(jsonValue));
    }

    /**
     */
    async generateStickers(requestParameters: GenerateStickersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartStickerGenerationResponse> {
        const response = await this.generateStickersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGenerateStickersStatusRaw(requestParameters: GetGenerateStickersStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StickerCollectionGeneratorStatus>> {
        if (requestParameters['bountyId'] == null) {
            throw new runtime.RequiredError(
                'bountyId',
                'Required parameter "bountyId" was null or undefined when calling getGenerateStickersStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['UNKNOWN_PARAMETER_NAME'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['UNKNOWN_PARAMETER_NAME']);
        }

        if (requestParameters['UNKNOWN_PARAMETER_NAME2'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['UNKNOWN_PARAMETER_NAME2']);
        }

        if (requestParameters['UNKNOWN_PARAMETER_NAME3'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['UNKNOWN_PARAMETER_NAME3']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/ai/generate/stickers/{bountyId}`;
        urlPath = urlPath.replace(`{${"bountyId"}}`, encodeURIComponent(String(requestParameters['bountyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StickerCollectionGeneratorStatusFromJSON(jsonValue));
    }

    /**
     */
    async getGenerateStickersStatus(requestParameters: GetGenerateStickersStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StickerCollectionGeneratorStatus> {
        const response = await this.getGenerateStickersStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async metaRaw(requestParameters: MetaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StickerGeneratorMeta>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['UNKNOWN_PARAMETER_NAME'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['UNKNOWN_PARAMETER_NAME']);
        }

        if (requestParameters['UNKNOWN_PARAMETER_NAME2'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['UNKNOWN_PARAMETER_NAME2']);
        }

        if (requestParameters['UNKNOWN_PARAMETER_NAME3'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['UNKNOWN_PARAMETER_NAME3']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/ai/generate/stickers/meta`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StickerGeneratorMetaFromJSON(jsonValue));
    }

    /**
     */
    async meta(requestParameters: MetaRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StickerGeneratorMeta> {
        const response = await this.metaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
