/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalyticsInfoResult,
} from '../models/index';
import {
    AnalyticsInfoResultFromJSON,
    AnalyticsInfoResultToJSON,
} from '../models/index';

export interface GetApiV1GoogleByCompanyidAnalyticsInfoRequest {
    companyId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

/**
 * GoogleControllerApi - interface
 * 
 * @export
 * @interface GoogleControllerApiInterface
 */
export interface GoogleControllerApiInterface {
    /**
     * 
     * @param {string} companyId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoogleControllerApiInterface
     */
    getApiV1GoogleByCompanyidAnalyticsInfoRaw(requestParameters: GetApiV1GoogleByCompanyidAnalyticsInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsInfoResult>>;

    /**
     */
    getApiV1GoogleByCompanyidAnalyticsInfo(requestParameters: GetApiV1GoogleByCompanyidAnalyticsInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsInfoResult>;

}

/**
 * 
 */
export class GoogleControllerApi extends runtime.BaseAPI implements GoogleControllerApiInterface {

    /**
     */
    async getApiV1GoogleByCompanyidAnalyticsInfoRaw(requestParameters: GetApiV1GoogleByCompanyidAnalyticsInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsInfoResult>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getApiV1GoogleByCompanyidAnalyticsInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/google/{companyId}/analytics_info`;
        urlPath = urlPath.replace(`{${"companyId"}}`, encodeURIComponent(String(requestParameters['companyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsInfoResultFromJSON(jsonValue));
    }

    /**
     */
    async getApiV1GoogleByCompanyidAnalyticsInfo(requestParameters: GetApiV1GoogleByCompanyidAnalyticsInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsInfoResult> {
        const response = await this.getApiV1GoogleByCompanyidAnalyticsInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
