/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangeSubscriptionTierResult,
  RestControllerSubscriptionControllerAdminCancelSubscriptionRequest,
  RestControllerSubscriptionControllerChangeSubscriptionTierRequest,
  RestControllerSubscriptionControllerStartSubscriptionCheckoutRequest,
  ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult,
  StartSubscriptionCheckoutResult,
  SubscriptionCatalogPageView,
  SubscriptionCatalogView,
  SubscriptionMutationResult,
  UserSubscriptionView,
} from '../models/index';
import {
    ChangeSubscriptionTierResultFromJSON,
    ChangeSubscriptionTierResultToJSON,
    RestControllerSubscriptionControllerAdminCancelSubscriptionRequestFromJSON,
    RestControllerSubscriptionControllerAdminCancelSubscriptionRequestToJSON,
    RestControllerSubscriptionControllerChangeSubscriptionTierRequestFromJSON,
    RestControllerSubscriptionControllerChangeSubscriptionTierRequestToJSON,
    RestControllerSubscriptionControllerStartSubscriptionCheckoutRequestFromJSON,
    RestControllerSubscriptionControllerStartSubscriptionCheckoutRequestToJSON,
    ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultFromJSON,
    ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultToJSON,
    StartSubscriptionCheckoutResultFromJSON,
    StartSubscriptionCheckoutResultToJSON,
    SubscriptionCatalogPageViewFromJSON,
    SubscriptionCatalogPageViewToJSON,
    SubscriptionCatalogViewFromJSON,
    SubscriptionCatalogViewToJSON,
    SubscriptionMutationResultFromJSON,
    SubscriptionMutationResultToJSON,
    UserSubscriptionViewFromJSON,
    UserSubscriptionViewToJSON,
} from '../models/index';

export interface GetApiV1SubscriptionsCatalogRequest {
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface GetApiV1SubscriptionsCatalogBySubscriptionbountyidRequest {
    subscriptionBountyId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface GetApiV1SubscriptionsCatalogCodeByCodeRequest {
    code: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface GetApiV1SubscriptionsMeRequest {
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface GetApiV1SubscriptionsMeBySubscriptionbountyidRequest {
    subscriptionBountyId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface GetApiV1SubscriptionsMeCatalogBySubscriptionbountyidRequest {
    subscriptionBountyId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface PostApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRequest {
    subscriptionId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
    restControllerSubscriptionControllerAdminCancelSubscriptionRequest?: RestControllerSubscriptionControllerAdminCancelSubscriptionRequest;
}

export interface PostApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRequest {
    subscriptionId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface PostApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRequest {
    userId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface PostApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRequest {
    subscriptionId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface PostApiV1SubscriptionsMeBySubscriptionidChangeTierRequest {
    subscriptionId: string;
    restControllerSubscriptionControllerChangeSubscriptionTierRequest: RestControllerSubscriptionControllerChangeSubscriptionTierRequest;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface PostApiV1SubscriptionsMeBySubscriptionidReverseCancelRequest {
    subscriptionId: string;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

export interface PostApiV1SubscriptionsMeCheckoutRequest {
    restControllerSubscriptionControllerStartSubscriptionCheckoutRequest: RestControllerSubscriptionControllerStartSubscriptionCheckoutRequest;
    xEdgeAgent?: string;
    xEdgeState?: string;
    xEdgeClientId?: string;
}

/**
 * SubscriptionControllerApi - interface
 * 
 * @export
 * @interface SubscriptionControllerApiInterface
 */
export interface SubscriptionControllerApiInterface {
    /**
     * 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    getApiV1SubscriptionsCatalogRaw(requestParameters: GetApiV1SubscriptionsCatalogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SubscriptionCatalogView>>>;

    /**
     */
    getApiV1SubscriptionsCatalog(requestParameters: GetApiV1SubscriptionsCatalogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SubscriptionCatalogView>>;

    /**
     * 
     * @param {string} subscriptionBountyId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    getApiV1SubscriptionsCatalogBySubscriptionbountyidRaw(requestParameters: GetApiV1SubscriptionsCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionCatalogView>>;

    /**
     */
    getApiV1SubscriptionsCatalogBySubscriptionbountyid(requestParameters: GetApiV1SubscriptionsCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionCatalogView>;

    /**
     * 
     * @param {string} code 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    getApiV1SubscriptionsCatalogCodeByCodeRaw(requestParameters: GetApiV1SubscriptionsCatalogCodeByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionCatalogView>>;

    /**
     */
    getApiV1SubscriptionsCatalogCodeByCode(requestParameters: GetApiV1SubscriptionsCatalogCodeByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionCatalogView>;

    /**
     * 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    getApiV1SubscriptionsMeRaw(requestParameters: GetApiV1SubscriptionsMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserSubscriptionView>>>;

    /**
     */
    getApiV1SubscriptionsMe(requestParameters: GetApiV1SubscriptionsMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserSubscriptionView>>;

    /**
     * 
     * @param {string} subscriptionBountyId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    getApiV1SubscriptionsMeBySubscriptionbountyidRaw(requestParameters: GetApiV1SubscriptionsMeBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSubscriptionView>>;

    /**
     */
    getApiV1SubscriptionsMeBySubscriptionbountyid(requestParameters: GetApiV1SubscriptionsMeBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSubscriptionView>;

    /**
     * 
     * @param {string} subscriptionBountyId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    getApiV1SubscriptionsMeCatalogBySubscriptionbountyidRaw(requestParameters: GetApiV1SubscriptionsMeCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionCatalogPageView>>;

    /**
     */
    getApiV1SubscriptionsMeCatalogBySubscriptionbountyid(requestParameters: GetApiV1SubscriptionsMeCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionCatalogPageView>;

    /**
     * 
     * @param {string} subscriptionId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {RestControllerSubscriptionControllerAdminCancelSubscriptionRequest} [restControllerSubscriptionControllerAdminCancelSubscriptionRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRaw(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionMutationResult>>;

    /**
     */
    postApiV1SubscriptionsAdminBySubscriptionidCancelImmediately(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionMutationResult>;

    /**
     * 
     * @param {string} subscriptionId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRaw(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>>;

    /**
     */
    postApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlements(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>;

    /**
     * 
     * @param {string} userId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRaw(requestParameters: PostApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>>>;

    /**
     */
    postApiV1SubscriptionsAdminUsersByUseridRebuildEntitlements(requestParameters: PostApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>>;

    /**
     * 
     * @param {string} subscriptionId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRaw(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionMutationResult>>;

    /**
     */
    postApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEnd(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionMutationResult>;

    /**
     * 
     * @param {string} subscriptionId 
     * @param {RestControllerSubscriptionControllerChangeSubscriptionTierRequest} restControllerSubscriptionControllerChangeSubscriptionTierRequest 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsMeBySubscriptionidChangeTierRaw(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidChangeTierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangeSubscriptionTierResult>>;

    /**
     */
    postApiV1SubscriptionsMeBySubscriptionidChangeTier(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidChangeTierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangeSubscriptionTierResult>;

    /**
     * 
     * @param {string} subscriptionId 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsMeBySubscriptionidReverseCancelRaw(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidReverseCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionMutationResult>>;

    /**
     */
    postApiV1SubscriptionsMeBySubscriptionidReverseCancel(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidReverseCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionMutationResult>;

    /**
     * 
     * @param {RestControllerSubscriptionControllerStartSubscriptionCheckoutRequest} restControllerSubscriptionControllerStartSubscriptionCheckoutRequest 
     * @param {string} [xEdgeAgent] 
     * @param {string} [xEdgeState] 
     * @param {string} [xEdgeClientId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionControllerApiInterface
     */
    postApiV1SubscriptionsMeCheckoutRaw(requestParameters: PostApiV1SubscriptionsMeCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartSubscriptionCheckoutResult>>;

    /**
     */
    postApiV1SubscriptionsMeCheckout(requestParameters: PostApiV1SubscriptionsMeCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartSubscriptionCheckoutResult>;

}

/**
 * 
 */
export class SubscriptionControllerApi extends runtime.BaseAPI implements SubscriptionControllerApiInterface {

    /**
     */
    async getApiV1SubscriptionsCatalogRaw(requestParameters: GetApiV1SubscriptionsCatalogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SubscriptionCatalogView>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/catalog`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SubscriptionCatalogViewFromJSON));
    }

    /**
     */
    async getApiV1SubscriptionsCatalog(requestParameters: GetApiV1SubscriptionsCatalogRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SubscriptionCatalogView>> {
        const response = await this.getApiV1SubscriptionsCatalogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getApiV1SubscriptionsCatalogBySubscriptionbountyidRaw(requestParameters: GetApiV1SubscriptionsCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionCatalogView>> {
        if (requestParameters['subscriptionBountyId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionBountyId',
                'Required parameter "subscriptionBountyId" was null or undefined when calling getApiV1SubscriptionsCatalogBySubscriptionbountyid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/catalog/{subscriptionBountyId}`;
        urlPath = urlPath.replace(`{${"subscriptionBountyId"}}`, encodeURIComponent(String(requestParameters['subscriptionBountyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionCatalogViewFromJSON(jsonValue));
    }

    /**
     */
    async getApiV1SubscriptionsCatalogBySubscriptionbountyid(requestParameters: GetApiV1SubscriptionsCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionCatalogView> {
        const response = await this.getApiV1SubscriptionsCatalogBySubscriptionbountyidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getApiV1SubscriptionsCatalogCodeByCodeRaw(requestParameters: GetApiV1SubscriptionsCatalogCodeByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionCatalogView>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling getApiV1SubscriptionsCatalogCodeByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/catalog/code/{code}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionCatalogViewFromJSON(jsonValue));
    }

    /**
     */
    async getApiV1SubscriptionsCatalogCodeByCode(requestParameters: GetApiV1SubscriptionsCatalogCodeByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionCatalogView> {
        const response = await this.getApiV1SubscriptionsCatalogCodeByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getApiV1SubscriptionsMeRaw(requestParameters: GetApiV1SubscriptionsMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserSubscriptionView>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserSubscriptionViewFromJSON));
    }

    /**
     */
    async getApiV1SubscriptionsMe(requestParameters: GetApiV1SubscriptionsMeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserSubscriptionView>> {
        const response = await this.getApiV1SubscriptionsMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getApiV1SubscriptionsMeBySubscriptionbountyidRaw(requestParameters: GetApiV1SubscriptionsMeBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSubscriptionView>> {
        if (requestParameters['subscriptionBountyId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionBountyId',
                'Required parameter "subscriptionBountyId" was null or undefined when calling getApiV1SubscriptionsMeBySubscriptionbountyid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me/{subscriptionBountyId}`;
        urlPath = urlPath.replace(`{${"subscriptionBountyId"}}`, encodeURIComponent(String(requestParameters['subscriptionBountyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSubscriptionViewFromJSON(jsonValue));
    }

    /**
     */
    async getApiV1SubscriptionsMeBySubscriptionbountyid(requestParameters: GetApiV1SubscriptionsMeBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSubscriptionView> {
        const response = await this.getApiV1SubscriptionsMeBySubscriptionbountyidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getApiV1SubscriptionsMeCatalogBySubscriptionbountyidRaw(requestParameters: GetApiV1SubscriptionsMeCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionCatalogPageView>> {
        if (requestParameters['subscriptionBountyId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionBountyId',
                'Required parameter "subscriptionBountyId" was null or undefined when calling getApiV1SubscriptionsMeCatalogBySubscriptionbountyid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me/catalog/{subscriptionBountyId}`;
        urlPath = urlPath.replace(`{${"subscriptionBountyId"}}`, encodeURIComponent(String(requestParameters['subscriptionBountyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionCatalogPageViewFromJSON(jsonValue));
    }

    /**
     */
    async getApiV1SubscriptionsMeCatalogBySubscriptionbountyid(requestParameters: GetApiV1SubscriptionsMeCatalogBySubscriptionbountyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionCatalogPageView> {
        const response = await this.getApiV1SubscriptionsMeCatalogBySubscriptionbountyidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRaw(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionMutationResult>> {
        if (requestParameters['subscriptionId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionId',
                'Required parameter "subscriptionId" was null or undefined when calling postApiV1SubscriptionsAdminBySubscriptionidCancelImmediately().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/admin/{subscriptionId}/cancel-immediately`;
        urlPath = urlPath.replace(`{${"subscriptionId"}}`, encodeURIComponent(String(requestParameters['subscriptionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestControllerSubscriptionControllerAdminCancelSubscriptionRequestToJSON(requestParameters['restControllerSubscriptionControllerAdminCancelSubscriptionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionMutationResultFromJSON(jsonValue));
    }

    /**
     */
    async postApiV1SubscriptionsAdminBySubscriptionidCancelImmediately(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionMutationResult> {
        const response = await this.postApiV1SubscriptionsAdminBySubscriptionidCancelImmediatelyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRaw(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>> {
        if (requestParameters['subscriptionId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionId',
                'Required parameter "subscriptionId" was null or undefined when calling postApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlements().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/admin/{subscriptionId}/rebuild-entitlements`;
        urlPath = urlPath.replace(`{${"subscriptionId"}}`, encodeURIComponent(String(requestParameters['subscriptionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultFromJSON(jsonValue));
    }

    /**
     */
    async postApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlements(requestParameters: PostApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult> {
        const response = await this.postApiV1SubscriptionsAdminBySubscriptionidRebuildEntitlementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRaw(requestParameters: PostApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling postApiV1SubscriptionsAdminUsersByUseridRebuildEntitlements().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/admin/users/{userId}/rebuild-entitlements`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResultFromJSON));
    }

    /**
     */
    async postApiV1SubscriptionsAdminUsersByUseridRebuildEntitlements(requestParameters: PostApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceSubscriptionsSubscriptionEntitlementSyncServiceSyncResult>> {
        const response = await this.postApiV1SubscriptionsAdminUsersByUseridRebuildEntitlementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRaw(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionMutationResult>> {
        if (requestParameters['subscriptionId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionId',
                'Required parameter "subscriptionId" was null or undefined when calling postApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEnd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me/{subscriptionId}/cancel-at-period-end`;
        urlPath = urlPath.replace(`{${"subscriptionId"}}`, encodeURIComponent(String(requestParameters['subscriptionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionMutationResultFromJSON(jsonValue));
    }

    /**
     */
    async postApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEnd(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionMutationResult> {
        const response = await this.postApiV1SubscriptionsMeBySubscriptionidCancelAtPeriodEndRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsMeBySubscriptionidChangeTierRaw(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidChangeTierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangeSubscriptionTierResult>> {
        if (requestParameters['subscriptionId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionId',
                'Required parameter "subscriptionId" was null or undefined when calling postApiV1SubscriptionsMeBySubscriptionidChangeTier().'
            );
        }

        if (requestParameters['restControllerSubscriptionControllerChangeSubscriptionTierRequest'] == null) {
            throw new runtime.RequiredError(
                'restControllerSubscriptionControllerChangeSubscriptionTierRequest',
                'Required parameter "restControllerSubscriptionControllerChangeSubscriptionTierRequest" was null or undefined when calling postApiV1SubscriptionsMeBySubscriptionidChangeTier().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me/{subscriptionId}/change-tier`;
        urlPath = urlPath.replace(`{${"subscriptionId"}}`, encodeURIComponent(String(requestParameters['subscriptionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestControllerSubscriptionControllerChangeSubscriptionTierRequestToJSON(requestParameters['restControllerSubscriptionControllerChangeSubscriptionTierRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangeSubscriptionTierResultFromJSON(jsonValue));
    }

    /**
     */
    async postApiV1SubscriptionsMeBySubscriptionidChangeTier(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidChangeTierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangeSubscriptionTierResult> {
        const response = await this.postApiV1SubscriptionsMeBySubscriptionidChangeTierRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsMeBySubscriptionidReverseCancelRaw(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidReverseCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionMutationResult>> {
        if (requestParameters['subscriptionId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionId',
                'Required parameter "subscriptionId" was null or undefined when calling postApiV1SubscriptionsMeBySubscriptionidReverseCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me/{subscriptionId}/reverse-cancel`;
        urlPath = urlPath.replace(`{${"subscriptionId"}}`, encodeURIComponent(String(requestParameters['subscriptionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionMutationResultFromJSON(jsonValue));
    }

    /**
     */
    async postApiV1SubscriptionsMeBySubscriptionidReverseCancel(requestParameters: PostApiV1SubscriptionsMeBySubscriptionidReverseCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionMutationResult> {
        const response = await this.postApiV1SubscriptionsMeBySubscriptionidReverseCancelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postApiV1SubscriptionsMeCheckoutRaw(requestParameters: PostApiV1SubscriptionsMeCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartSubscriptionCheckoutResult>> {
        if (requestParameters['restControllerSubscriptionControllerStartSubscriptionCheckoutRequest'] == null) {
            throw new runtime.RequiredError(
                'restControllerSubscriptionControllerStartSubscriptionCheckoutRequest',
                'Required parameter "restControllerSubscriptionControllerStartSubscriptionCheckoutRequest" was null or undefined when calling postApiV1SubscriptionsMeCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEdgeAgent'] != null) {
            headerParameters['X-edge-agent'] = String(requestParameters['xEdgeAgent']);
        }

        if (requestParameters['xEdgeState'] != null) {
            headerParameters['X-edge-state'] = String(requestParameters['xEdgeState']);
        }

        if (requestParameters['xEdgeClientId'] != null) {
            headerParameters['X-edge-client-id'] = String(requestParameters['xEdgeClientId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JWT authentication
        }


        let urlPath = `/api/v1/subscriptions/me/checkout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestControllerSubscriptionControllerStartSubscriptionCheckoutRequestToJSON(requestParameters['restControllerSubscriptionControllerStartSubscriptionCheckoutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartSubscriptionCheckoutResultFromJSON(jsonValue));
    }

    /**
     */
    async postApiV1SubscriptionsMeCheckout(requestParameters: PostApiV1SubscriptionsMeCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartSubscriptionCheckoutResult> {
        const response = await this.postApiV1SubscriptionsMeCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
